// showcases/vue-showcase/src/components/input/Input.vue
<script setup lang="ts">
import {
	DBInput,
	LabelVariantType,
	ValueLabelType
} from "../../../../../output/vue/src";
import defaultComponentVariants from "../../../../shared/input.json";
import DefaultComponent from "../DefaultComponent.vue";

const getDataList = (
	variant?: LabelVariantType
): string[] | ValueLabelType[] => {
	if (variant === "floating") {
		return ["Test 1", "Test 2"];
	}

	return [
		{ value: "test1", label: "Test 1" },
		{ value: "test2", label: "Test 2" }
	];
};
</script>

<template>
	<DefaultComponent title="DBInput" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInput
				:maxLength="exampleProps?.maxLength"
				:max="exampleProps?.max"
				:min="exampleProps?.min"
				:variant="exampleProps?.variant"
				:show-label="exampleProps?.showLabel"
				:label="exampleProps?.label"
				:message="exampleProps?.message"
				:placeholder="exampleName"
				:minLength="exampleProps?.minLength"
				:required="exampleProps?.required"
				:type="exampleProps?.type"
				:disabled="exampleProps?.disabled"
				:readOnly="exampleProps?.readOnly"
				:value="exampleProps?.value"
				:icon="exampleProps?.icon"
				:iconAfter="exampleProps?.iconAfter"
				:showMessage="exampleProps?.showMessage"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:validation="exampleProps?.validation"
				:dataList="
					exampleProps?.dataList
						? getDataList(exampleProps?.variant)
						: undefined
				"
			></DBInput>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/input/input.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/input.json';
import { DefaultComponent } from '../default.component';
import {
	DBInput,
	LabelVariantType,
	ValueLabelType
} from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-input',
	templateUrl: './input.component.html',
	imports: [
		environment.webComponents
			? [DefaultComponent]
			: [DefaultComponent, DBInput]
	],
	standalone: true,
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class InputComponent {
	variants = defaultComponentVariants;

	getDataList = (variant?: LabelVariantType): string[] | ValueLabelType[] => {
		if (variant === 'floating') {
			return ['Test 1', 'Test 2'];
		}

		return [
			{ value: 'test1', label: 'Test 1' },
			{ value: 'test2', label: 'Test 2' }
		];
	};
}

<app-default-component
	title="Input"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<ng-container *ngIf="exampleIndex === 0">
			<DBInput label="Label" description="Description"></DBInput>
		</ng-container>
		<ng-container *ngIf="variantIndex === 0">
			<ng-container *ngFor="let variant of variantColors; index as index">
				<DBInput
					*ngIf="exampleIndex === index + 1"
					label="Label"
					description="Description"
					[variant]="variant"
				></DBInput>
			</ng-container>
		</ng-container>
		<ng-container *ngIf="variantIndex === 1">
			<ng-container *ngIf="exampleIndex === 1">
				<DBInput
					label="Label"
					description="Description"
					value="Input Text"
				></DBInput>
			</ng-container>
			<ng-container *ngIf="exampleIndex === 2">
				<DBInput
					label="Label"
					description="Description"
					value="123456"
					type="number"
				></DBInput>
			</ng-container>
			<ng-container *ngIf="exampleIndex === 3">
				<DBInput
					label="Label"
					description="Description"
					min-length="5"
					[required]="true"
				></DBInput>
			</ng-container>
			<ng-container *ngIf="exampleIndex === 4">
				<DBInput
					label="Label"
					description="Description"
					[disabled]="true"
				></DBInput>
			</ng-container>
			<ng-container *ngIf="exampleIndex === 5">
				<DBInput
					label="Label"
					description="Description"
					[disabled]="true"
					value="Input Text"
				></DBInput>
			</ng-container>
			<ng-container *ngIf="exampleIndex === 6">
				<DBInput
					label="Label"
					description="Description"
					[required]="true"
					value="Input Text"
				></DBInput>
			</ng-container>
		</ng-container>
		<ng-container *ngIf="variantIndex === 2">
			<ng-container *ngIf="exampleIndex === 1">
				<DBInput
					label="Label"
					description="Description"
					icon-before="account"
				></DBInput>
			</ng-container>
			<ng-container *ngIf="exampleIndex === 2">
				<DBInput
					label="Label"
					description="Description"
					icon-before="account"
					icon-after="edit"
				></DBInput>
			</ng-container>
			<ng-container *ngIf="exampleIndex === 3">
				<DBInput
					label="Label"
					description="Description"
					icon-after="edit"
				></DBInput>
			</ng-container>
			<ng-container *ngIf="exampleIndex === 4">
				<DBInput
					label="Label"
					description="Description"
					icon-after="edit"
					variant="success"
				></DBInput>
			</ng-container>
		</ng-container>
	</ng-template>
</app-default-component>
