// showcases/angular-showcase/src/app/components/default.component.ts
import {
	Component,
	Input,
	NO_ERRORS_SCHEMA,
	type OnInit,
	type TemplateRef
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { type ActivatedRoute } from '@angular/router';
import {
	COLOR,
	COLOR_CONST,
	DBCard,
	DBDivider,
	DBLink,
	DENSITY,
	DENSITY_CONST
} from '../../../../../output/angular/src';
import type {
	DefaultComponentProps,
	DefaultComponentVariants
} from '../../../../shared/default-component-data';

@Component({
	selector: 'app-default-component',
	templateUrl: './default.component.html',
	imports: [DBCard, DBDivider, DBLink, NgTemplateOutlet],
	standalone: true,
	schemas: [NO_ERRORS_SCHEMA]
})
export class DefaultComponent implements OnInit {
	@Input() title: DefaultComponentProps['title'] = '';
	@Input() variants: DefaultComponentProps['variants'] = [];
	@Input() exampleTemplate!: TemplateRef<any>;

	density = DENSITY.REGULAR;
	color = COLOR.NEUTRAL_BG_LEVEL_1;
	page?: string;

	variantRef: DefaultComponentVariants | undefined;
	variantRefIndex = 0;

	constructor(private readonly route: ActivatedRoute) {}

	ngOnInit(): void {
		this.route.queryParams.subscribe((parameters) => {
			if (parameters[DENSITY_CONST]) {
				this.density = parameters[DENSITY_CONST];
			}

			if (parameters['page']) {
				this.page = parameters['page'];

				const foundVariant = this.variants.find(
					(variant) => variant.name.toLowerCase() === this.page
				);

				this.variantRef = foundVariant;
				if (foundVariant) {
					this.variantRefIndex = this.variants.indexOf(foundVariant);
				}
			}

			if (parameters[COLOR_CONST]) {
				this.color = parameters[COLOR_CONST];
			}
		});
	}

	getLink = (variantName: string) => {
		let currentUrl = window.location.href;
		if (!currentUrl.includes('?')) {
			currentUrl += '?';
		}

		if (!currentUrl.includes('color=')) {
			currentUrl += `&color=${this.color || COLOR.NEUTRAL_BG_LEVEL_1}`;
		}

		if (!currentUrl.includes('density=')) {
			currentUrl += `&density=${this.density || DENSITY.REGULAR}`;
		}

		return `${currentUrl}&page=${variantName.toLowerCase()}`;
	};

	getElevation = (): '1' | '2' | '3' =>
		this.color?.includes('3') ? '3' : this.color?.includes('2') ? '2' : '1';
}

<!-- TODO: Content Projection not working for nested components? -> Had to copy paste variant-cards... -->
@if (variantRef) {
	<db-card class="variants-card" [elevationLevel]="getElevation()">
		<!-- Breadcrumb renders its own <nav>; suppress wrapper landmarks to avoid duplicates -->
		<div
			class="variants-list"
			[attr.aria-label]="
				title === 'DBBreadcrumb'
					? undefined
					: variantRef.role
						? variantRef.name
						: undefined
			"
			[attr.role]="title === 'DBBreadcrumb' ? undefined : variantRef.role"
		>
			@for (
				example of variantRef.examples;
				track example;
				let exampleIndex = $index
			) {
				<div
					[style]="example.style"
					[class]="example.class"
					[attr.data-density]="example.density"
				>
					<ng-container
						*ngTemplateOutlet="
							exampleTemplate;
							context: {
								exampleProps: example.props ?? {},
								exampleName: example.name,
								exampleIndex: exampleIndex,
								variantIndex: variantRefIndex
							}
						"
					>
					</ng-container>
				</div>
			}
		</div>
	</db-card>
}

@if (!variantRef) {
	<div class="default-container">
		<div class="component-header">
			<h1>{{ title }}</h1>
		</div>
		@for (variant of variants; track variant; let variantIndex = $index) {
			<div>
				<db-divider></db-divider>
				<db-link
					class="link-headline"
					content="external"
					target="_blank"
					[href]="getLink(variant.name)"
				>
					<span>{{ variant.name }}</span>
				</db-link>

				<db-card
					class="variants-card"
					[elevationLevel]="getElevation()"
				>
					<!-- Breadcrumb renders its own <nav>; suppress wrapper landmarks to avoid duplicates -->
					<div
						class="variants-list"
						[attr.aria-label]="
							title === 'DBBreadcrumb'
								? undefined
								: variant.role
									? variant.name
									: undefined
						"
						[attr.role]="
							title === 'DBBreadcrumb' ? undefined : variant.role
						"
					>
						@for (
							example of variant.examples;
							track example;
							let exampleIndex = $index
						) {
							<div
								[style]="example.style"
								[class]="example.class"
								[attr.data-density]="example.density"
							>
								<ng-container
									*ngTemplateOutlet="
										exampleTemplate;
										context: {
											exampleProps: example.props,
											exampleName: example.name,
											exampleIndex: exampleIndex,
											variantIndex: variantIndex
										}
									"
								>
								</ng-container>
							</div>
						}
					</div>
				</db-card>
			</div>
		}
	</div>
}

// showcases/vue-showcase/src/components/DefaultComponent.vue
<script setup lang="ts">
import { DBCard, DBDivider, DBLink } from "../../../../output/vue/src";
import type {
	DefaultComponentExample,
	DefaultComponentProps,
	DefaultComponentVariants
} from "../../../shared/default-component-data";
import {
	COLOR,
	COLOR_CONST,
	DENSITY,
	DENSITY_CONST
} from "../../../../packages/components/src/shared/constants";
import { useRoute } from "vue-router";
import { Ref, ref, watch } from "vue";

interface DefaultExample extends DefaultComponentExample {
	name?: string;
	example?: any;
	style?: {
		display?: string;
		width?: string;
		height?: string;
	};
	className?: string;
	props?: any;
	code?: {
		html?: string; // We will generate this with reacts 'renderToString'
		angular?: string;
		react?: string;
		vue?: string;
	};
}
interface DefaultVariants extends DefaultComponentVariants {
	name: string;
	examples: DefaultExample[];
	slotCode?: any;
	color?: string;
	role?: string;
}
/* Workaround see: https://vuejs.org/guide/typescript/composition-api.html#typing-component-props */
interface DefaultProps extends DefaultComponentProps {
	title: string;
	variants: DefaultVariants[];
}

const props = defineProps<DefaultProps>();

const route = useRoute();

const variantRef: Ref<DefaultVariants | undefined> = ref();
const variantRefIndex: Ref<number> = ref(-1);
const color = ref(COLOR.NEUTRAL_BG_LEVEL_1);

watch(
	() => route.query,
	async (query: any) => {
		if (query[COLOR_CONST] && query[COLOR_CONST] !== color.value) {
			color.value = query[COLOR_CONST];
		}
	}
);

if (route.query.page) {
	const foundVariant = props.variants.find(
		(variant) => variant.name.toLowerCase() === route.query.page
	);

	variantRef.value = foundVariant;
	if (foundVariant) {
		variantRefIndex.value = props.variants.indexOf(foundVariant);
	}
}

const getLink = (variantName: string) => {
	let currentUrl = window.location.href;
	if (!currentUrl.includes("?")) {
		currentUrl += "?";
	}
	if (!currentUrl.includes("color=")) {
		currentUrl += `&color=${route.query[COLOR_CONST] || COLOR.NEUTRAL_BG_LEVEL_1}`;
	}
	if (!currentUrl.includes("density=")) {
		currentUrl += `&density=${
			route.query[DENSITY_CONST] || DENSITY.REGULAR
		}`;
	}
	return `${currentUrl}&page=${variantName.toLowerCase()}`;
};

const getElevation = (): "1" | "2" | "3" =>
	color.value.includes("3") ? "3" : color.value.includes("2") ? "2" : "1";
</script>

<template>
	<!-- TODO: Slots not working for nested components? -> Had to copy paste variant-cards...	-->
	<DBCard
		v-if="variantRef"
		class="variants-card"
		:elevation-level="getElevation()"
	>
		<div
			:role="variantRef.role"
			:aria-label="variantRef.role ? variantRef.name : undefined"
			class="variants-list"
		>
			<div
				v-for="(example, exampleIndex) in variantRef.examples"
				:style="example.style"
				:class="example.className"
			>
				<slot
					name="example"
					v-bind:exampleProps="example.props"
					v-bind:exampleName="example.name"
					v-bind:exampleIndex="exampleIndex"
					v-bind:variantIndex="variantRefIndex"
				></slot>
			</div>
		</div>
	</DBCard>
	<div v-if="!variantRef" class="default-container">
		<h1>{{ title }}</h1>
		<div v-for="(variant, variantIndex) in variants">
			<DBDivider></DBDivider>
			<DBLink
				class="link-headline"
				content="external"
				target="_blank"
				:href="getLink(variant.name)"
			>
				{{ variant.name }}
			</DBLink>
			<DBCard class="variants-card" :elevation-level="getElevation()">
				<div
					:role="variant.role"
					:aria-label="
						variantRef !== undefined && variantRef.role
							? variantRef?.name
							: undefined
					"
					class="variants-list"
				>
					<div
						v-for="(example, exampleIndex) in variant.examples"
						:style="example.style"
						:class="example.className"
					>
						<slot
							name="example"
							v-bind:exampleProps="example.props"
							v-bind:exampleName="example.name"
							v-bind:exampleIndex="exampleIndex"
							v-bind:variantIndex="variantIndex"
						></slot>
					</div>
				</div>
			</DBCard>
		</div>
	</div>
</template>
