// storybooks/vue-storybook/src/stories/Button.vue
<template>
	<button type="button" :class="classes" @click="onClick" :style="style">
		{{ label }}
	</button>
</template>

<script lang="ts" setup>
import { computed } from "vue";

import "./button.css";

const props = withDefaults(
	defineProps<{
		/**
		 * The label of the button
		 */
		label: string;
		/**
		 * primary or secondary button
		 */
		primary?: boolean;
		/**
		 * size of the button
		 */
		size?: "small" | "medium" | "large";
		/**
		 * background color of the button
		 */
		backgroundColor?: string;
	}>(),
	{ primary: false }
);

const emit = defineEmits<{
	(e: "click", id: number): void;
}>();

const classes = computed(() => ({
	"storybook-button": true,
	"storybook-button--primary": props.primary,
	"storybook-button--secondary": !props.primary,
	[`storybook-button--${props.size || "medium"}`]: true
}));

const style = computed(() => ({
	backgroundColor: props.backgroundColor
}));

const onClick = () => {
	emit("click", 1);
};
</script>

// storybooks/react-storybook/src/stories/Button.tsx
import './button.css';

export type ButtonProps = {
	/** Is this the principal call to action on the page? */
	primary?: boolean;
	/** What background color to use */
	backgroundColor?: string;
	/** How large should the button be? */
	size?: 'small' | 'medium' | 'large';
	/** Button contents */
	label: string;
	/** Optional click handler */
	onClick?: () => void;
};

/** Primary UI component for user interaction */
export const Button = ({
	primary = false,
	size = 'medium',
	backgroundColor,
	label,
	...props
}: ButtonProps) => {
	const mode = primary
		? 'storybook-button--primary'
		: 'storybook-button--secondary';
	return (
		<button
			type="button"
			className={[
				'storybook-button',
				`storybook-button--${size}`,
				mode
			].join(' ')}
			style={{ backgroundColor }}
			{...props}>
			{label}
		</button>
	);
};
