// showcases/vue-showcase/src/components/form/Checkboxes.vue
<script setup lang="ts">
import { DBCheckbox } from "@db-ux/v-core-components/src";
import { ref } from "vue";
import FormWrapper from "./FormWrapper.vue";

const plain = ref(true);
const vModel = ref(true);
</script>

<template>
	<FormWrapper :plain="plain" :vmodel="vModel">
		<DBCheckbox
			name="checkbox-1"
			@change="plain = $event.target.checked"
			:checked="plain"
		>
			Plain
		</DBCheckbox>
		<DBCheckbox name="checkbox-1" v-model:checked="vModel">
			VModel
		</DBCheckbox>
	</FormWrapper>
</template>

// showcases/angular-showcase/src/app/components/form/checkboxes/checkboxes.component.ts
import { Component } from '@angular/core';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { DBCheckbox } from '@components';
import { WrapperComponent } from '../wrapper/wrapper.component';

@Component({
	selector: 'app-checkboxes',
	standalone: true,
	imports: [WrapperComponent, DBCheckbox, FormsModule, ReactiveFormsModule],
	templateUrl: './checkboxes.component.html'
})
export class CheckboxesComponent {
	plain = true;
	ngModel = true;
	formControl: FormControl = new FormControl(true);

	public handlePlainChange(event: Event | void) {
		if (!event) {
			return;
		}
		this.plain = (event.target as HTMLInputElement).checked;
	}
}

<app-form-wrapper
	[control]="formControl.value"
	[model]="ngModel"
	[plain]="plain"
>
	<fieldset>
		<legend>Different form approaches</legend>
		<db-checkbox
			(change)="handlePlainChange($event)"
			[checked]="plain"
			label="Plain"
			name="checkbox"
		></db-checkbox>
		<db-checkbox
			[(ngModel)]="ngModel"
			label="ngModel"
			name="checkbox"
		></db-checkbox>
		<db-checkbox
			[formControl]="formControl"
			label="formControl"
			name="checkbox"
		></db-checkbox>
	</fieldset>
</app-form-wrapper>
