// showcases/vue-showcase/src/components/form/Selects.vue
<script setup lang="ts">
import { DBSelect } from "@db-ux/v-core-components/src";
import { ref } from "vue";
import FormWrapper from "./FormWrapper.vue";

const plain = ref("combobox-2");
const vModel = ref("combobox-2");
</script>

<template>
	<FormWrapper :plain="plain" :vmodel="vModel">
		<DBSelect
			:value="plain"
			label="Plain"
			@change="plain = $event.target.value"
		>
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
		</DBSelect>
		<DBSelect label="VModel" v-model:value="vModel">
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
		</DBSelect>
	</FormWrapper>
</template>

// showcases/angular-showcase/src/app/components/form/selects/selects.component.ts
import { Component } from '@angular/core';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { DBSelect } from '@components';
import { WrapperComponent } from '../wrapper/wrapper.component';

@Component({
	selector: 'app-selects',
	standalone: true,
	imports: [WrapperComponent, DBSelect, FormsModule, ReactiveFormsModule],
	templateUrl: './selects.component.html'
})
export class SelectsComponent {
	plain = 'combobox-2';
	ngModel = 'combobox-2';
	formControl: FormControl = new FormControl('combobox-2');
	public handlePlainChange(event: Event | void) {
		if (!event) return;
		this.plain = (event.target as HTMLSelectElement).value;
	}
}

<app-form-wrapper
	[control]="formControl.value"
	[model]="ngModel"
	[plain]="plain"
	[signalForms]="signalForm.value().value()"
>
	<fieldset>
		<legend>Different form approaches</legend>
		<db-select
			(change)="handlePlainChange($event)"
			[value]="plain"
			label="Plain"
		>
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
			<option value="combobox-3">combobox-3</option>
		</db-select>
		<db-select [(ngModel)]="ngModel" label="ngModel">
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
			<option value="combobox-3">combobox-3</option>
		</db-select>
		<db-select [formControl]="formControl" label="formControl">
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
			<option value="combobox-3">combobox-3</option>
		</db-select>
		<db-select [formField]="signalForm.value" label="signalForms">
			<option value="combobox-0">combobox-0</option>
			<option value="combobox-1">combobox-1</option>
			<option value="combobox-2">combobox-2</option>
			<option value="combobox-3">combobox-3</option>
		</db-select>
	</fieldset>
</app-form-wrapper>
