// showcases/vue-showcase/src/components/form/Radios.vue
<script setup lang="ts">
import { ref } from "vue";
import { DBRadio } from "../../../../../packages/v-core-components/src";
import FormWrapper from "./FormWrapper.vue";

const plain = ref("");
const vModel = ref("");
</script>

<template>
	<FormWrapper :plain="plain" :vmodel="vModel">
		<DBRadio
			name="radio-0"
			value="radio-0"
			@change="plain = $event.target.value"
		>
			Plain
		</DBRadio>
		<DBRadio name="radio-1" value="radio-1" v-model:value="vModel">
			VModel
		</DBRadio>
	</FormWrapper>
</template>

// showcases/angular-showcase/src/app/components/form/radios/radios.component.ts
import { Component } from '@angular/core';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { DBRadio } from '@components';
import { WrapperComponent } from '../wrapper/wrapper.component';

@Component({
	selector: 'app-radios',
	standalone: true,
	imports: [WrapperComponent, DBRadio, FormsModule, ReactiveFormsModule],
	templateUrl: './radios.component.html'
})
export class RadiosComponent {
	plain = '';
	ngModel = '';
	formControl: FormControl = new FormControl('');
	public handlePlainChange(event: Event | void) {
		if (!event) return;
		this.plain = (event.target as HTMLInputElement).value;
	}
}

<app-form-wrapper
	[plain]="plain"
	[model]="ngModel"
	[control]="formControl.value"
	[signalForms]="signalFormsValue()"
>
	<fieldset>
		<legend>Different form approaches</legend>
		<db-radio
			(change)="handlePlainChange($event)"
			value="radio-0"
			name="radio-0"
			label="Plain"
		></db-radio>
		<db-radio
			[(ngModel)]="ngModel"
			value="radio-1"
			name="radio-1"
			label="ngModel"
		></db-radio>
		<db-radio
			[formControl]="formControl"
			value="radio-2"
			name="radio-2"
			label="formControl"
		></db-radio>
		<db-radio
			(change)="handleSignalFormsChange($event)"
			value="radio-3"
			name="radio-3"
			label="signalForms"
		></db-radio>
	</fieldset>
</app-form-wrapper>
