// showcases/vue-showcase/src/components/custom-select/CustomSelect.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/custom-select.json";
import { DBCustomSelect, DBInfotext } from "../../../../../output/vue/src";
import { CustomSelectOptionType } from "@db-ux/core-components/src/components/custom-select/model";

const log = (values: string[]) => {
	// eslint-disable-next-line no-alert
	console.log(values);
};

const getAriaLabel = (exampleProps, exampleName): string => {
	return `${exampleProps.id}-${exampleName}`;
};

const getTransformSelectedLabels = (selectedOptions?: any): string => {
	return selectedOptions.map((option: any) => option.value.at(option.value.length - 1)).join(", ");
};

const getSearchFilter = (option: CustomSelectOptionType, _: string): boolean => option.value === "Option 1";
</script>

<template>
	<DefaultComponent title="DBCustomSelect" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
			<DBInfotext v-if="exampleProps?.info" size="small" semantic="informational">
				{{ exampleName }}
			</DBInfotext>

			<i v-if="exampleProps?.lineBreak" class="line-break" />

			<DBCustomSelect
				v-if="!exampleProps?.lineBreak && !exampleProps?.info"
				:ariaListLabel="getAriaLabel(exampleProps, exampleName)"
				:disabled="exampleProps?.disabled"
				:icon="exampleProps?.icon"
				:showMessage="exampleProps?.showMessage"
				:showIcon="exampleProps?.showIcon"
				:dropdownWidth="exampleProps?.dropdownWidth"
				:showClearSelection="exampleProps?.showClearSelection"
				:showSelectAll="exampleProps?.showSelectAll"
				:showSearch="exampleProps?.showSearch"
				:showLoading="exampleProps?.showLoading"
				:showNoResults="exampleProps?.showNoResults"
				:multiple="exampleProps?.multiple"
				:loadingText="exampleProps?.loadingText"
				:noResultsText="exampleProps?.noResultsText ?? 'No matching filter'"
				:label="exampleName"
				:options="exampleProps?.options"
				:variant="exampleProps?.variant"
				:message="exampleProps?.message"
				:required="exampleProps?.required"
				:placeholder="exampleProps?.placeholder"
				:showLabel="exampleProps?.showLabel"
				:placement="exampleProps?.placement"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:validation="exampleProps?.validation"
				selectAllLabel="Select all"
				searchLabel="Search"
				:searchValue="exampleProps?.searchValue"
				:selectedLabels="exampleProps?.selectedLabels"
				:transformSelectedLabels="exampleProps?.transformSelectedLabels ? getTransformSelectedLabels : undefined"
				:searchFilter="exampleProps?.searchFilter ? getSearchFilter : undefined"
				:selectedType="exampleProps?.selectedType"
				:formFieldWidth="exampleProps?.formFieldWidth"
				:on-option-selected="(values) => log(values)"
			/>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/custom-select/index.tsx
import { useState } from 'react';
import { type CustomSelectOptionType } from '@db-ux/core-components/src/components/custom-select/model';
import { DBCustomSelect, DBInfotext } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/custom-select.json';
import type { DBCustomSelectProps } from '../../../../../output/react/src/components/custom-select/model';
import { getVariants } from '../data';
import type { BaseComponentProps } from '../base-component-data';

const getCustomSelect = ({
	children,
	message,
	variant,
	values,
	required,
	options,
	placeholder,
	selectedType,
	formFieldWidth,
	showLabel,
	placement,
	lineBreak,
	info,
	showLoading,
	showNoResults,
	showSelectAll,
	showClearSelection,
	showSearch,
	noResultsText,
	loadingText,
	multiple,
	dropdownWidth,
	icon,
	showIcon,
	showMessage,
	disabled,
	id,
	searchValue,
	selectedLabels,
	transformSelectedLabels,
	searchFilter,
	validMessage,
	validation,
	invalidMessage
}: DBCustomSelectProps & {
	lineBreak?: boolean;
	info?: boolean;
}) => {
	const [mValue, setValue] = useState<string[] | undefined>(values);

	const getTransformSelectedLabels = (selectedOptions?: any): string => {
		return selectedOptions.map((option: any) => option.value.at(-1)).join(', ');
	};

	const getSearchFilter = (option: CustomSelectOptionType, _: string): boolean => option.value === 'Option 1';

	if (info) {
		return (
			<DBInfotext size="small" semantic="informational">
				{children}
			</DBInfotext>
		);
	}

	if (lineBreak) {
		return <i className="line-break" />;
	}

	return (
		<DBCustomSelect
			disabled={disabled}
			icon={icon}
			showMessage={showMessage}
			showIcon={showIcon}
			dropdownWidth={dropdownWidth}
			showClearSelection={showClearSelection}
			showSelectAll={showSelectAll}
			showSearch={showSearch}
			showLoading={showLoading}
			showNoResults={showNoResults}
			multiple={multiple}
			label={children}
			ariaListLabel={`${id}-${children}`}
			options={options}
			variant={variant}
			message={message}
			required={required}
			placeholder={placeholder}
			showLabel={showLabel}
			placement={placement}
			selectAllLabel="Select all"
			searchLabel="Search"
			selectedType={selectedType}
			formFieldWidth={formFieldWidth}
			loadingText={loadingText}
			noResultsText={noResultsText ?? 'No matching filter'}
			values={mValue}
			searchValue={searchValue}
			selectedLabels={selectedLabels}
			invalidMessage={invalidMessage}
			validMessage={validMessage}
			validation={validation}
			transformSelectedLabels={transformSelectedLabels ? getTransformSelectedLabels : undefined}
			searchFilter={searchFilter ? getSearchFilter : undefined}
			onOptionSelected={(value) => {
				setValue(value);
			}}
		/>
	);
};

const CustomSelectComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent title="DBCustomSelect" variants={getVariants(defaultComponentVariants, getCustomSelect, props.slotCode)}></DefaultComponent>
	);
};

export default CustomSelectComponent;
