// showcases/vue-showcase/src/control-panel/Actions2.vue
<script setup lang="ts">
import { DBButton, DBControlPanelActions2, DBSwitch } from "@components";
import { useLayout } from "../composables/use-layout";

const { shell, onChange } = useLayout();

const onShellToggle = () => {
	onChange({} as Event, "shell");
};
</script>

<template>
	<DBControlPanelActions2>
		<DBSwitch :checked="shell" @change="onShellToggle"> Shell </DBSwitch>
		<DBButton icon="x_placeholder" variant="ghost" noText>
			Notification
		</DBButton>
		<DBButton icon="x_placeholder" variant="ghost" noText> Help </DBButton>
	</DBControlPanelActions2>
</template>

// showcases/react-showcase/src/control-panel/actions-2.tsx
import { DBButton, DBControlPanelActions2, DBSwitch } from '@components';
import useQuery from '../hooks/use-query';

export default function Actions2() {
	const { shell, setShell } = useQuery();

	return (
		<DBControlPanelActions2>
			<DBSwitch
				checked={shell}
				onChange={() => {
					setShell(!shell);
				}}>
				Shell
			</DBSwitch>
			<DBButton icon="x_placeholder" variant="ghost" noText>
				Notification
			</DBButton>
			<DBButton icon="x_placeholder" variant="ghost" noText>
				Help
			</DBButton>
		</DBControlPanelActions2>
	);
}
