// showcases/vue-showcase/src/control-panel/SecondaryActions.vue
<script setup lang="ts">
import {
	DBButton,
	DBControlPanelSecondaryActions
} from "@components";
</script>

<template>
	<DBControlPanelSecondaryActions>
		<DBButton icon="x_placeholder" variant="ghost" noText>
			Profile
		</DBButton>
		<DBButton icon="x_placeholder" variant="ghost" noText>
			Notification
		</DBButton>
		<DBButton icon="x_placeholder" variant="ghost" noText> Help </DBButton>
	</DBControlPanelSecondaryActions>
</template>

// showcases/react-showcase/src/control-panel/secondary-actions.tsx
import { DBButton, DBControlPanelSecondaryActions } from '@components';

const SecondaryActions = () => (
	<DBControlPanelSecondaryActions>
		<DBButton icon="x_placeholder" variant="ghost" noText>
			Profile
		</DBButton>
		<DBButton icon="x_placeholder" variant="ghost" noText>
			Notification
		</DBButton>
		<DBButton icon="x_placeholder" variant="ghost" noText>
			Help
		</DBButton>
	</DBControlPanelSecondaryActions>
);

export default SecondaryActions;
