// showcases/react-showcase/src/components/tab-bar/index.tsx
import { DBTabBar } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/tab-bar.json';
import type { DBTabBarProps } from '../../../../../output/react/src/components/tab-bar/model';
import { getVariants } from '../data';

const getTabBar = ({ children }: DBTabBarProps) => (
	<DBTabBar>
		{children}
	</DBTabBar>
);

const TabBarComponent = () => {
	return (
		<DefaultComponent
			title="DBTabBar"
			variants={getVariants(
                     				defaultComponentVariants,
                     				getTabBar
                     			)}></DefaultComponent>
	);
};

export default TabBarComponent;

// showcases/vue-showcase/src/components/tab-bar/TabBar.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tab-bar.json";
import { DBTabBar } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTabBar" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
            <DBTabBar>{{exampleName}}</DBTabBar>
		</template>
	</DefaultComponent>
</template>
