// showcases/angular-showcase/src/app/components/tab-bar/tab-bar.component.ts
import { Component } from '@angular/core';

import defaultComponentVariants from '../../../../../shared/tab-bar.json';

@Component({
	selector: 'app-tab-bar',
	templateUrl: './tab-bar.component.html'
})
export class TabBarComponent {
	variants = defaultComponentVariants;
}



<app-default-component
	title="DBTabBar"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-tab-bar>{{exampleName}}</db-tab-bar>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/tab-bar/TabBar.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tab-bar.json";
import { DBTabBar } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTabBar" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
            <DBTabBar>{{exampleName}}</DBTabBar>
		</template>
	</DefaultComponent>
</template>
