// showcases/vue-showcase/src/components/infotext/Infotext.vue
<script setup lang="ts">
import { DBInfotext } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/infotext.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBInfotext" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext
				:size="exampleProps?.size"
				:semantic="exampleProps?.semantic"
				:icon="exampleProps?.icon"
				:showIcon="exampleProps?.showIcon"
			>
				{{ exampleName }}
			</DBInfotext>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/infotext/index.tsx
import { DBInfotext } from '@components';
import { type DBInfotextProps } from '@components/src/components/infotext/model';
import defaultComponentVariants from '../../../../shared/infotext.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getInfotext = ({
	semantic,
	size,
	icon,
	children,
	showIcon
}: DBInfotextProps) => (
	<DBInfotext semantic={semantic} size={size} icon={icon} showIcon={showIcon}>
		{children}
	</DBInfotext>
);

const InfotextComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title={'DBInfotext'}
			variants={getVariants(
				defaultComponentVariants,
				getInfotext,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default InfotextComponent;
