// showcases/vue-showcase/src/components/form/Textareas.vue
<script setup lang="ts">
import { DBTextarea } from "@db-ux/v-core-components/src";
import { ref } from "vue";
import FormWrapper from "./FormWrapper.vue";

const plain = ref("test1");
const vModel = ref("test2");
</script>

<template>
	<FormWrapper :plain="plain" :vmodel="vModel">
		<DBTextarea
			label="Plain"
			placeholder="Placeholder"
			message="Description"
			icon="x_placeholder"
			name="textarevalue-name"
			:value="plain"
			@change="plain = $event.target.value"
		/>
		<DBTextarea
			label="VModel"
			placeholder="Placeholder"
			message="Description"
			icon="x_placeholder"
			name="textarea-name"
			v-model:value="vModel"
		/>
	</FormWrapper>
</template>

// showcases/angular-showcase/src/app/components/form/textareas/textareas.component.ts
import {Component} from '@angular/core';
import {FormControl, FormsModule, ReactiveFormsModule} from '@angular/forms';
import {DBTextarea} from '@components';
import {WrapperComponent} from '../wrapper/wrapper.component';

@Component({
	selector: 'app-textareas',
	standalone: true,
	imports: [WrapperComponent, DBTextarea, FormsModule, ReactiveFormsModule],
	templateUrl: './textareas.component.html',
})
export class TextareasComponent {
	plain = 'test1';
	ngModel = 'test2';
	formControl: FormControl = new FormControl('test3');
	public handlePlainChange(event: Event | void) {
		if (!event) {
			return;
		}

		this.plain = (event.target as HTMLTextAreaElement).value;
	}
}

<app-form-wrapper
	[plain]="plain"
	[model]="ngModel"
	[control]="formControl.value"
	[signalForms]="signalForm.value().value()"
>
	<fieldset>
		<legend>Different form approaches</legend>
		<db-textarea
			label="Plain"
			placeholder="Placeholder"
			message="Description"
			name="textarea-name"
			[value]="plain"
			(change)="handlePlainChange($event)"
		/>
		<db-textarea
			label="ngModel"
			placeholder="Placeholder"
			message="Description"
			name="textarea-name"
			[(ngModel)]="ngModel"
		/>
		<db-textarea
			label="formControl"
			placeholder="Placeholder"
			message="Description"
			name="textarea-name"
			[formControl]="formControl"
		/>
		<db-textarea
			label="signalForms"
			placeholder="Placeholder"
			message="Description"
			[formField]="signalForm.value"
		/>
	</fieldset>
</app-form-wrapper>
