// showcases/vue-showcase/src/components/radio/Radio.vue
<script setup lang="ts">
import { DBInfotext, DBRadio } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/radio.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBRadio" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBRadio
				:showRequiredAsterisk="exampleProps?.showRequiredAsterisk"
				:label="exampleProps?.label"
				:size="exampleProps?.size"
				:name="exampleProps?.name"
				:checked="exampleProps?.checked"
				:value="exampleProps?.value"
				:required="exampleProps?.required"
				:show-label="exampleProps?.showLabel"
				:disabled="exampleProps?.disabled"
				:validation="exampleProps?.validation"
			>
				{{ exampleName }}
			</DBRadio>
			<template
				v-if="
					exampleProps?.showLabel !== undefined &&
					!exampleProps?.showLabel
				"
			>
				<DBInfotext
					semantic="informational"
					size="small"
					:showIcon="false"
				>
					{{ exampleName }}
				</DBInfotext>
			</template>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/radio/index.tsx
import { DBInfotext, DBRadio, getBoolean } from '@components';
import { type DBRadioProps } from '@components/src/components/radio/model';
import defaultComponentVariants from '../../../../shared/radio.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getRadio = ({
	label,
	size,
	name,
	checked,
	required,
	children,
	disabled,
	value,
	showLabel,
	validation,
	showRequiredAsterisk
}: DBRadioProps) => (
	<>
		<DBRadio
			showRequiredAsterisk={showRequiredAsterisk}
			label={label}
			size={size}
			name={name}
			defaultChecked={getBoolean(checked)}
			required={required}
			disabled={disabled}
			showLabel={showLabel}
			value={value}
			validation={validation}>
			{children}
		</DBRadio>
		{showLabel !== undefined && !showLabel && (
			<DBInfotext size="small" semantic="informational" showIcon={false}>
				{children}
			</DBInfotext>
		)}
	</>
);

const RadioComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title={'DBRadio'}
			variants={getVariants(
				defaultComponentVariants,
				getRadio,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default RadioComponent;
