// showcases/vue-showcase/src/components/tag/Tag.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tag.json";
import {
	DBTag,
	DBButton,
	DBLink,
	DBCheckbox,
	DBRadio
} from "../../../../../output/vue/vue3/src";

const showAlert = (exampleName: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent title="DBTag" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTag
				:variant="exampleProps.variant"
				:disabled="exampleProps.disabled"
				:icon="exampleProps.icon"
				:noText="exampleProps.noText"
				:behaviour="exampleProps.behaviour"
				:emphasis="exampleProps.emphasis"
				:overflow="exampleProps.overflow"
				:removeButton="exampleProps.removeButton"
				@remove="showAlert(exampleName)"
			>
				<DBButton v-if="exampleProps.component === 'button'">{{
					exampleName
				}}</DBButton>
				<DBLink v-if="exampleProps.component === 'link'" href="#">{{
					exampleName
				}}</DBLink>
				<DBCheckbox
					v-if="exampleProps.component === 'checkbox'"
					:checked="exampleProps.checked"
					>{{ exampleName }}</DBCheckbox
				>
				<DBRadio
					v-if="exampleProps.component === 'radio'"
					name="radio"
					:checked="exampleProps.checked"
					>{{ exampleName }}</DBRadio
				>
				{{ exampleName }}
			</DBTag>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/tag/index.tsx
import {
	DBButton,
	DBCheckbox,
	DBLink,
	DBRadio,
	DBTag
} from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/tag.json';
import { type DBTagProps } from '../../../../../output/react/src/components/tag/model';
import { getVariants } from '../data';

const getTag = ({
	variant,
	disabled,
	children,
	icon,
	overflow,
	noText,
	behaviour,
	emphasis,
	removeButton,
	checked,
	component
}: DBTagProps & {
	checked?: boolean;
	component?: 'button' | 'link' | 'radio' | 'checkbox';
}) => (
	<DBTag
		variant={variant}
		disabled={disabled}
		icon={icon}
		noText={noText}
		behaviour={behaviour}
		emphasis={emphasis}
		overflow={overflow}
		removeButton={removeButton}
		onRemove={() => {
			// eslint-disable-next-line no-alert
			alert(children.toString());
		}}>
		{component === 'button' && <DBButton>{children}</DBButton>}
		{component === 'link' && <DBLink href="#">{children}</DBLink>}
		{component === 'checkbox' && (
			<DBCheckbox checked={checked}>{children}</DBCheckbox>
		)}
		{component === 'radio' && (
			<DBRadio checked={checked} name="radio">
				{children}
			</DBRadio>
		)}
		{!component && <span>{children}</span>}
	</DBTag>
);

const TagComponent = () => {
	return (
		<DefaultComponent
			title="DBTag"
			variants={getVariants(
				defaultComponentVariants,
				getTag
			)}></DefaultComponent>
	);
};

export default TagComponent;
