// showcases/vue-showcase/src/components/breadcrumb-item/BreadcrumbItem.vue
<script setup lang="ts">
import { DBBreadcrumbItem } from "../../../../../output/vue/src";
import defaultComponentVariants from "../../../../shared/breadcrumb-item.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent
		title="DBBreadcrumbItem"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<nav class="db-breadcrumb" aria-label="Breadcrumb">
				<ol>
					<DBBreadcrumbItem
						:href="exampleProps?.href"
						:text="exampleProps?.text"
						:icon="exampleProps?.icon"
						:ariaCurrent="exampleProps?.ariaCurrent"
						:disabled="exampleProps?.disabled"
						:className="exampleProps?.className"
						:id="exampleProps?.id"
					/>
				</ol>
			</nav>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/breadcrumb-item/breadcrumb-item.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBBreadcrumbItem } from '../../../../../../output/angular/src';
import defaultComponentVariants from '../../../../../patternhub/data/breadcrumb-item.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-breadcrumb-item',
	templateUrl: './breadcrumb-item.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBBreadcrumbItem],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : [],
	standalone: true
})
export class BreadcrumbItemComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBBreadcrumbItem"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<nav class="db-breadcrumb" aria-label="Breadcrumb">
			<ol>
				<db-breadcrumb-item
					[href]="exampleProps?.href"
					[text]="exampleProps?.text"
					[icon]="exampleProps?.icon"
					[ariaCurrent]="exampleProps?.ariaCurrent"
					[disabled]="exampleProps?.disabled"
					[className]="exampleProps?.className"
					[id]="exampleProps?.id"
				></db-breadcrumb-item>
			</ol>
		</nav>
	</ng-template>
</app-default-component>
