// showcases/vue-showcase/src/components/switch/Switch.vue
<script setup lang="ts">
import { DBInfotext, DBSwitch } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/switch.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBSwitch" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBSwitch
				:showRequiredAsterisk="exampleProps?.showRequiredAsterisk"
				:visualAid="exampleProps?.visualAid"
				:checked="exampleProps?.checked"
				:disabled="exampleProps?.disabled"
				:required="exampleProps?.required"
				:showLabel="exampleProps?.showLabel"
				:variant="exampleProps?.variant"
				:size="exampleProps?.size"
				:icon="exampleProps?.icon"
				:iconTrailing="exampleProps?.iconTrailing"
				:iconLeading="exampleProps?.iconLeading"
				:validation="exampleProps?.validation"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:message="exampleProps?.message"
				:showMessage="exampleProps?.showMessage"
			>
				{{ exampleName }}
			</DBSwitch>
			<DBInfotext
				v-if="
					exampleProps?.showLabel !== undefined &&
					!exampleProps?.showLabel
				"
				semantic="informational"
				icon="none"
			>
				{{ exampleName }}
			</DBInfotext>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/switch/switch.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DefaultComponent } from '../default.component';
import defaultComponentVariants from '../../../../../shared/switch.json';
import { DBSwitch } from '../../../../../../output/angular/src/components/switch';
import { DBInfotext } from '../../../../../../output/angular/src/components/infotext';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-switch',
	templateUrl: './switch.component.html',
	imports: [
		environment.webComponents
			? [DefaultComponent]
			: [DefaultComponent, DBSwitch, DBInfotext]
	],
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class SwitchComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBSwitch"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-switch
			[showRequiredAsterisk]="exampleProps?.showRequiredAsterisk"
			[visualAid]="exampleProps?.visualAid"
			[checked]="exampleProps?.checked"
			[disabled]="exampleProps?.disabled"
			[required]="exampleProps?.required"
			[showLabel]="exampleProps?.showLabel"
			[labelPosition]="exampleProps?.labelPosition"
			[accent]="exampleProps?.accent"
			[size]="exampleProps?.size"
			[icon]="exampleProps?.icon"
			[iconTrailing]="exampleProps?.iconTrailing"
			[iconLeading]="exampleProps?.iconLeading"
			[validation]="exampleProps?.validation"
			[invalidMessage]="exampleProps?.invalidMessage"
			[validMessage]="exampleProps?.validMessage"
			[message]="exampleProps?.message"
			[showMessage]="exampleProps?.showMessage"
			[label]="exampleProps?.label"
		>
			<!-- eslint-disable-next-line -->
			{{
				exampleProps?.label ? exampleProps?.label : exampleName
			}}</db-switch
		>
		@if (
			exampleProps?.showLabel !== undefined &&
			exampleProps?.showLabel !== null &&
			!exampleProps?.showLabel
		) {
			<db-infotext semantic="informational" icon="none">
				{{ exampleName }}
			</db-infotext>
		}
	</ng-template>
</app-default-component>
