// showcases/vue-showcase/src/components/multi-select/MultiSelect.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/multi-select.json";
import { DBMultiSelect, DBInfotext } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent
		title="DBMultiSelect"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext
				v-if="exampleProps?.info"
				size="small"
				semantic="informational"
			>
				{{ exampleName }}
			</DBInfotext>

			<i v-if="exampleProps?.lineBreak" class="line-break" />

			<DBMultiSelect
				v-if="!exampleProps?.lineBreak && !exampleProps?.info"
				:icon="exampleProps?.icon"
				:showIcon="exampleProps?.showIcon"
				:dropdownWidth="exampleProps?.dropdownWidth"
				:showClearSelection="exampleProps?.showClearSelection"
				:showSelectAll="exampleProps?.showSelectAll"
				:showSearch="exampleProps?.showSearch"
				:showLoading="exampleProps?.showLoading"
				:showNoResults="exampleProps?.showNoResults"
				:multiple="exampleProps?.multiple"
				:loadingText="exampleProps?.loadingText"
				:noResultsText="
					exampleProps?.noResultsText ?? 'No matching filter'
				"
				:label="exampleName"
				:options="exampleProps?.options"
				:variant="exampleProps?.variant"
				:message="exampleProps?.message"
				:required="exampleProps?.required"
				:placeholder="exampleProps?.placeholder"
				:showLabel="exampleProps?.showLabel"
				:placement="exampleProps?.placement"
				selectAllLabel="Select all"
				deSelectAllLabel="Deselect all"
				searchLabel="Search"
				:selectedType="exampleProps?.selectedType"
				:width="exampleProps?.width"
				:values="exampleProps?.mValue"
				:on-select="(event) => console.log(event)"
			/>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/multi-select/multi-select.component.ts
import { Component } from '@angular/core';
import { DefaultComponent } from '../default.component';
import defaultComponentVariants from '../../../../../shared/multi-select.json';
import { environment } from '../../../environments/environment';
import {
	DBInfotext,
	DBMultiSelect
} from '../../../../../../output/angular/src';

@Component({
	selector: 'app-multi-select',
	templateUrl: './multi-select.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBInfotext, DBMultiSelect],
	standalone: true
})
export class MultiSelectComponent {
	variants = defaultComponentVariants;
	protected readonly console = console;
}

<app-default-component
	title="DBMultiSelect"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		@if (exampleProps?.info) {
			<db-infotext size="small" semantic="informational">
				{{ exampleName }}
			</db-infotext>
		} @else if (exampleProps?.lineBreak) {
			<i class="line-break"></i>
		} @else {
			<db-multi-select
				[icon]="exampleProps?.icon"
				[showIcon]="exampleProps?.showIcon"
				[dropdownWidth]="exampleProps?.dropdownWidth"
				[showClearSelection]="exampleProps?.showClearSelection"
				[showSelectAll]="exampleProps?.showSelectAll"
				[showSearch]="exampleProps?.showSearch"
				[showLoading]="exampleProps?.showLoading"
				[showNoResults]="exampleProps?.showNoResults"
				[multiple]="exampleProps?.multiple"
				[loadingText]="exampleProps?.loadingText"
				[noResultsText]="
					exampleProps?.noResultsText ?? 'No matching filter'
				"
				[label]="exampleName"
				[options]="exampleProps?.options"
				[variant]="exampleProps?.variant"
				[message]="exampleProps?.message"
				[required]="exampleProps?.required"
				[placeholder]="exampleProps?.placeholder"
				[showLabel]="exampleProps?.showLabel"
				[placement]="exampleProps?.placement"
				selectAllLabel="Select all"
				deSelectAllLabel="Deselect all"
				searchLabel="Search"
				[selectedType]="exampleProps?.selectedType"
				[width]="exampleProps?.width"
				noResultsText="No matching filter"
				[values]="exampleProps?.mValue"
				(onSelect)="console.log($event)"
			></db-multi-select>
		}
	</ng-template>
</app-default-component>
