// showcases/vue-showcase/src/components/textarea/Textarea.vue
<script setup lang="ts">
import { DBTextarea } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/textarea.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBTextarea" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTextarea
				:showRequiredAsterisk="exampleProps?.showRequiredAsterisk"
				:cols="exampleProps?.cols"
				:disabled="exampleProps?.disabled"
				:show-label="exampleProps?.showLabel"
				:message="exampleProps?.message"
				:required="exampleProps?.required"
				:readOnly="exampleProps?.readOnly"
				:label="exampleProps?.label"
				:placeholder="exampleProps?.placeholder || exampleName"
				:rows="exampleProps?.rows"
				:value="exampleProps?.value"
				:variant="exampleProps?.variant"
				:showMessage="exampleProps?.showMessage"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:validation="exampleProps?.validation"
				:showResizer="exampleProps?.showResizer"
				:fieldSizing="exampleProps?.fieldSizing"
			></DBTextarea>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/textarea/textarea.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBTextarea } from '@components';
import defaultComponentVariants from '../../../../../shared/textarea.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-textarea',
	templateUrl: './textarea.component.html',
	imports: [
		environment.webComponents
			? [DefaultComponent]
			: [DefaultComponent, DBTextarea]
	],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : [],
	standalone: true
})
export class TextareaComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBTextarea"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-textarea
			[showRequiredAsterisk]="exampleProps?.showRequiredAsterisk"
			[variant]="exampleProps?.variant"
			[label]="exampleProps?.label"
			[required]="exampleProps?.required"
			[disabled]="exampleProps?.disabled"
			[readOnly]="exampleProps?.readOnly"
			[value]="exampleProps?.value"
			[cols]="exampleProps?.cols"
			[rows]="exampleProps?.rows"
			[showLabel]="exampleProps?.showLabel"
			[placeholder]="exampleProps?.placeholder || exampleName"
			[message]="exampleProps?.message"
			[showMessage]="exampleProps?.showMessage"
			[invalidMessage]="exampleProps?.invalidMessage"
			[validMessage]="exampleProps?.validMessage"
			[validation]="exampleProps?.validation"
			[showResizer]="exampleProps?.showResizer"
			[fieldSizing]="exampleProps?.fieldSizing"
		></db-textarea>
	</ng-template>
</app-default-component>
