// showcases/vue-showcase/src/components/accordion-item/AccordionItem.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/accordion-item.json";
import { DBAccordionItem } from "../../../../../output/vue/vue3/src";
import { ref } from "vue";

const openId = ref<string | undefined>(undefined);

const getId = (exampleIndex: number, variantIndex: number) =>
	`${variantIndex}${exampleIndex}`;
const toggle = (exampleIndex: number, variantIndex: number) => {
	if (openId.value === getId(exampleIndex, variantIndex)) {
		openId.value = undefined;
	} else {
		openId.value = getId(exampleIndex, variantIndex);
	}
};

const isOpen = (exampleIndex: number, variantIndex: number, open?: boolean) =>
	openId.value === getId(exampleIndex, variantIndex) ? true : open;
</script>

<template>
	<DefaultComponent
		title="DBAccordionItem"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBAccordionItem
				:title="exampleName"
				:disabled="exampleProps.disabled"
				:open="isOpen(exampleIndex, variantIndex, exampleProps.open)"
				@onToggle="toggle(exampleIndex, variantIndex)"
			>
				{{ exampleName }}
			</DBAccordionItem>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/accordion-item/accordion-item.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/accordion-item.json';
import { DBAccordionItem } from '../../../../../../output/angular/src';
import { DefaultComponent } from '../default.component';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-accordion-item',
	templateUrl: './accordion-item.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBAccordionItem],
	standalone: true,
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class AccordionItemComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBAccordionItem"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-accordion-item
			[title]="exampleName"
			[disabled]="exampleProps.disabled"
			[open]="isOpen(exampleIndex, variantIndex, exampleProps.open)"
			(onToggle)="toggle(exampleIndex, variantIndex)"
		>
			{{ exampleName }}
		</db-accordion-item>
	</ng-template>
</app-default-component>
