// showcases/vue-showcase/src/components/infotext/Infotext.vue
<script setup lang="ts">
import { DBInfotext } from "../../../../../packages/v-core-components/src";
import defaultComponentVariants from "../../../../shared/infotext.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBInfotext" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext
				:size="exampleProps?.size"
				:semantic="exampleProps?.semantic"
				:icon="exampleProps?.icon"
				:showIcon="exampleProps?.showIcon"
			>
				{{ exampleName }}
			</DBInfotext>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/infotext/infotext.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBInfotext } from '../../../../../../packages/ngx-core-components/src';
import defaultComponentVariants from '../../../../../shared/infotext.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-infotext',
	templateUrl: './infotext.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBInfotext],
	standalone: true,
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class InfotextComponent {
	variants = defaultComponentVariants;
}

<app-default-component title="DBInfotext" [variants]="variants" [exampleTemplate]="exampleTemplate">
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-infotext [size]="exampleProps?.size" [semantic]="exampleProps?.semantic" [icon]="exampleProps?.icon" [showIcon]="exampleProps?.showIcon">
			{{ exampleName }}
		</db-infotext>
	</ng-template>
</app-default-component>
