// showcases/react-showcase/src/page/page.tsx
import {
	COLORS,
	DBBrand,
	DBButton,
	DBHeader,
	DBPage,
	DBSelect,
	DBSwitch,
	DENSITIES
} from '@components';
import { useState } from 'react';
import { Outlet } from 'react-router-dom';
import useQuery from '../hooks/use-query';
import Navigation from './navigation';

export default function Page() {
	const { density, shell, color, setShell, setDensity, setColor } =
		useQuery();

	const [drawerOpen, setDrawerOpen] = useState(false);

	return (
		<DBPage
			variant="fixed"
			documentOverflow="auto"
			fadeIn
			header={
				<DBHeader
					drawerOpen={drawerOpen}
					onToggle={setDrawerOpen}
					brand={<DBBrand>Showcase</DBBrand>}
					metaNavigation={
						<>
							<DBSelect
								label="Density"
								variant="floating"
								value={density}
								onChange={(event) => {
									setDensity(event?.target?.value);
								}}>
								{DENSITIES.map((ton) => (
									<option
										key={`density-option-${ton}`}
										value={ton}>
										{ton}
									</option>
								))}
							</DBSelect>
							<DBSelect
								label="Color"
								variant="floating"
								value={color}
								onChange={(event) => {
									setColor(event?.target?.value);
								}}>
								{COLORS.map((col) => (
									<option
										key={`color-option-${col}`}
										value={col}>
										{col}
									</option>
								))}
							</DBSelect>
						</>
					}
					primaryAction={
						<DBButton
							icon="magnifying_glass"
							variant="ghost"
							noText>
							Search
						</DBButton>
					}
					secondaryAction={
						<>
							<DBSwitch
								checked={shell}
								onChange={() => {
									setShell(!shell);
								}}>
								Shell
							</DBSwitch>
						</>
					}>
					<Navigation />
				</DBHeader>
			}>
			<div data-density={density} className={`db-${color}`}>
				<Outlet />
			</div>
		</DBPage>
	);
}

// showcases/vue-showcase/src/page/Page.vue
<script setup lang="ts">
import {
	COLORS,
	DBBrand,
	DBButton,
	DBHeader,
	DBPage,
	DBSelect,
	DBSwitch,
	DENSITIES
} from "@components";
import { ref } from "vue";
import { useLayout } from "../composables/use-layout";
import PageNavigation from "./PageNavigation.vue";

const { density, color, shell, onChange } = useLayout();

const drawerOpen = ref(false);

const onToggle = (open: boolean) => {
	drawerOpen.value = open;
};

const onShellToggle = () => {
	onChange({} as Event, "shell");
};
</script>

<template>
	<DBPage variant="fixed" documentOverflow="auto" fadeIn>
		<template #header>
			<DBHeader
				:drawerOpen="drawerOpen"
				:onToggle="onToggle"
				drawerHeaderText="Showcase"
			>
				<template #brand>
					<DBBrand>Showcase</DBBrand>
				</template>
				<template #meta-navigation>
					<DBSelect
						label="Density"
						variant="floating"
						:value="density"
						@change="onChange($event, 'density')"
					>
						<option v-for="ton of DENSITIES" :value="ton">
							{{ ton }}
						</option>
					</DBSelect>
					<DBSelect
						label="Color"
						variant="floating"
						:value="color"
						@change="onChange($event, 'color')"
					>
						<option v-for="col of COLORS" :value="col">
							{{ col }}
						</option>
					</DBSelect>
				</template>
				<template #primary-action>
					<DBButton icon="magnifying_glass" variant="ghost" noText>
						Search
					</DBButton>
				</template>
				<template #secondary-action>
					<DBSwitch :checked="shell" @change="onShellToggle">
						Shell
					</DBSwitch>
				</template>
				<PageNavigation />
			</DBHeader>
		</template>
		<div :data-density="density" :class="`db-${color}`">
			<router-view></router-view>
		</div>
	</DBPage>
</template>
