// showcases/angular-showcase/src/app/page/page-nav-item.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { DBNavigationItem, NavigationContentDirective } from '@components';
import { NavItem } from '../utils/navigation-item';

@Component({
	selector: 'app-page-nav-item',
	templateUrl: './page-nav-item.component.html',
	imports: [
		RouterLink,
		RouterLinkActive,
		DBNavigationItem,
		NavigationContentDirective
	],
	standalone: true
})
export class PageNavItemComponent {
	@Input({ required: true }) navItem!: NavItem;

	getBackButtonText = () => `Back to ${this.navItem.label}`;
}

@if (navItem) {
	<db-navigation-item [backButtonText]="getBackButtonText()">
		@if (navItem.subNavigation) {
			<ng-container slot="subNavigation" sub-navigation>
				@for (item of navItem.subNavigation; track item.label) {
					<app-page-nav-item [navItem]="item" />
				}
			</ng-container>
		}
		<ng-container *dbNavigationContent>
			@if (navItem.component) {
				<a
					[routerLink]="navItem.path"
					[routerLinkActiveOptions]="{ exact: true }"
					ariaCurrentWhenActive="page"
					queryParamsHandling="merge"
					routerLinkActive="active"
				>
					{{ navItem.label }}
				</a>
			}
			@if (!navItem.component) {
				{{ navItem.label }}
			}
		</ng-container>
	</db-navigation-item>
}

// showcases/vue-showcase/src/page/PageNavItem.vue
<script setup lang="ts">
import { DBNavigationItem } from "@components";
import { defineProps } from "vue";
import { type NavItem } from "../utils/navigation-items";

defineProps<{
	navItem: NavItem;
}>();
</script>

<template>
	<DBNavigationItem :backButtonText="`Back to ${navItem.label}`">
		<template v-if="navItem.subNavigation" v-slot:sub-navigation>
			<template v-for="item of navItem.subNavigation">
				<PageNavItem :navItem="item"></PageNavItem>
			</template>
		</template>
		<router-link
			v-if="navItem.component"
			:to="navItem.path"
			ariaCurrentValue="page"
		>
			{{ navItem.label }}
		</router-link>
		<template v-if="!navItem.component">{{ navItem.label }}</template>
	</DBNavigationItem>
</template>
