// showcases/vue-showcase/src/components/form/Custom-Selects.vue
<script setup lang="ts">
import FormWrapper from "./FormWrapper.vue";
import { DBCustomSelect } from "@components";
import { ref } from "vue";

const plain = ref(["combobox-1"]);
const vModel = ref(["combobox-1"]);

const options = [
	{ value: "combobox-0", id: "combobox-0" },
	{ value: "combobox-1", id: "combobox-1" }
];
</script>

<template>
	<FormWrapper :plain="plain" :vmodel="vModel">
		<DBCustomSelect
			:options="options"
			:values="plain"
			label="Plain"
			@optionSelected="(values) => (plain = values)"
		/>
		<DBCustomSelect
			:options="options"
			label="VModel"
			v-model:values="vModel"
		/>
	</FormWrapper>
</template>

// showcases/angular-showcase/src/app/components/form/custom-selects/custom-selects.component.ts
import {Component} from '@angular/core';
import {FormControl, FormsModule, ReactiveFormsModule} from '@angular/forms';
import {DBCustomSelect} from '@components';
import {WrapperComponent} from '../wrapper/wrapper.component';

@Component({
	selector: 'app-custom-selects',
	standalone: true,
	imports: [WrapperComponent, DBCustomSelect, FormsModule, ReactiveFormsModule],
	templateUrl: './custom-selects.component.html',
})
export class CustomSelectsComponent {
	plain = ['combobox-2'];
	ngModel = ['combobox-2'];
	formControl: FormControl = new FormControl(['combobox-2']);

	options = [
		{value: 'combobox-0', id: 'combobox-0'},
		{value: 'combobox-1', id: 'combobox-1'},
		{value: 'combobox-2', id: 'combobox-2'},
	];

	public handlePlainChange(values: string[] | void) {
		if (values) {
			this.plain = values;
		}
	}
}

<app-form-wrapper
	[control]="formControl.value"
	[model]="ngModel"
	[plain]="plain"
>
	<fieldset>
		<legend>Different form approaches</legend>
		<db-custom-select
			(optionSelected)="handlePlainChange($event)"
			[options]="options"
			[values]="plain"
			label="Plain"
		>
		</db-custom-select>
		<db-custom-select [(ngModel)]="ngModel" [options]="options" label="ngModel">
		</db-custom-select>
		<db-custom-select
			[formControl]="formControl"
			[options]="options"
			label="formControl"
		>
		</db-custom-select>
	</fieldset>
</app-form-wrapper>
