// showcases/vue-showcase/src/components/popover/Popover.vue
<script setup lang="ts">
import { DBButton, DBPopover } from "../../../../../output/vue/src";
import defaultComponentVariants from "../../../../shared/popover.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBPopover" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBPopover
				:width="exampleProps?.width"
				:gap="exampleProps?.gap"
				:spacing="exampleProps?.spacing"
				:placement="exampleProps?.placement"
				:animation="exampleProps?.animation"
				:delay="exampleProps?.delay"
				:id="exampleProps?.id"
			>
				<template v-slot:trigger>
					<DBButton>
						{{ exampleName }}
					</DBButton>
				</template>
				<template v-if="exampleProps?.content">{{
					exampleProps?.content
				}}</template>
				<template v-if="!exampleProps?.content">
					<ul class="popover-list">
						<li>Popover Custom Item 1b</li>
						<li>Popover Custom Item 2</li>
					</ul>
					<DBButton>Popover Custom Item 3</DBButton>
				</template>
			</DBPopover>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/popover/index.tsx
import { DBButton, DBPopover } from '../../../../../output/react/src';
import type { DBPopoverProps } from '../../../../../output/react/src/components/popover/model';
import defaultComponentVariants from '../../../../shared/popover.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getPopover = ({
	id,
	children,
	width,
	gap,
	spacing,
	placement,
	delay,
	content,
	animation
}: DBPopoverProps & { content: string }) => (
	<DBPopover
		trigger={<DBButton>{children}</DBButton>}
		width={width}
		gap={gap}
		spacing={spacing}
		placement={placement}
		animation={animation}
		delay={delay}
		id={id}>
		{content ?? (
			<>
				<ul className="popover-list">
					<li>Popover Custom Item 1b</li>
					<li>Popover Custom Item 2</li>
				</ul>
				<DBButton>Popover Custom Item 3</DBButton>
			</>
		)}
	</DBPopover>
);

const PopoverComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBPopover"
			variants={getVariants(
				defaultComponentVariants,
				getPopover,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default PopoverComponent;
