// showcases/angular-showcase/src/app/components/loading-indicator/loading-indicator.component.ts
import { Component } from '@angular/core';

import { DefaultComponent } from '../default.component';
import defaultComponentVariants from '../../../../../shared/loading-indicator.json';
import { DBLoadingIndicator } from '../../../../../../output/angular/src/components/loading-indicator';

@Component({
	selector: 'app-loading-indicator',
	templateUrl: './loading-indicator.component.html',
	imports: [DefaultComponent, DBLoadingIndicator],
	standalone: true
})
export class LoadingIndicatorComponent {
	variants = defaultComponentVariants;
}



<app-default-component
	title="DBLoadingIndicator"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-loading-indicator>{{exampleName}}</db-loading-indicator>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/loading-indicator/LoadingIndicator.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/loading-indicator.json";
import { DBLoadingIndicator } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBLoadingIndicator" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
            <DBLoadingIndicator>{{exampleName}}</DBLoadingIndicator>
		</template>
	</DefaultComponent>
</template>
