// showcases/react-showcase/src/components/switch/index.tsx
import type { DBSwitchProps } from '@db-ux/react-core-components/src';
import {
	DBInfotext,
	DBSwitch,
	getBoolean
} from '../../../../../output/react/src';
import defaultComponentVariants from '../../../../shared/switch.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getSwitch = ({
	children,
	checked,
	visualAid,
	disabled,
	showLabel,
	size,
	icon,
	iconTrailing,
	iconLeading,
	required,
	showRequiredAsterisk,
	validation,
	invalidMessage,
	validMessage,
	message,
	messageIcon,
	showMessage,
	variant
}: DBSwitchProps) => (
	<>
		<DBSwitch
			visualAid={visualAid}
			defaultChecked={getBoolean(checked)}
			disabled={disabled}
			showRequiredAsterisk={showRequiredAsterisk}
			showLabel={showLabel}
			variant={variant}
			size={size}
			icon={icon}
			iconTrailing={iconTrailing}
			iconLeading={iconLeading}
			required={required}
			validation={validation}
			invalidMessage={invalidMessage}
			validMessage={validMessage}
			message={message}
			messageIcon={messageIcon}
			showMessage={showMessage}>
			{children}
		</DBSwitch>
		{showLabel !== undefined && !showLabel && (
			<DBInfotext semantic="informational" icon="none">
				{children}
			</DBInfotext>
		)}
	</>
);

const SwitchComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBSwitch"
			variants={getVariants(
				defaultComponentVariants,
				getSwitch,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default SwitchComponent;

// showcases/vue-showcase/src/components/switch/Switch.vue
<script setup lang="ts">
import { DBInfotext, DBSwitch } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/switch.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBSwitch" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBSwitch
				:showRequiredAsterisk="exampleProps?.showRequiredAsterisk"
				:visualAid="exampleProps?.visualAid"
				:checked="exampleProps?.checked"
				:disabled="exampleProps?.disabled"
				:required="exampleProps?.required"
				:showLabel="exampleProps?.showLabel"
				:variant="exampleProps?.variant"
				:size="exampleProps?.size"
				:icon="exampleProps?.icon"
				:iconTrailing="exampleProps?.iconTrailing"
				:iconLeading="exampleProps?.iconLeading"
				:validation="exampleProps?.validation"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:message="exampleProps?.message"
				:showMessage="exampleProps?.showMessage"
			>
				{{ exampleName }}
			</DBSwitch>
			<DBInfotext
				v-if="
					exampleProps?.showLabel !== undefined &&
					!exampleProps?.showLabel
				"
				semantic="informational"
				icon="none"
			>
				{{ exampleName }}
			</DBInfotext>
		</template>
	</DefaultComponent>
</template>
