// showcases/vue-showcase/src/components/tab-item/TabItem.vue
<script setup lang="ts">
import { DBTabItem, DBTabList } from "../../../../../output/vue/src";
import defaultComponentVariants from "../../../../shared/tab-item.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBTabItem" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTabList
				><DBTabItem
					:active="exampleProps?.active"
					:noText="exampleProps?.noText"
					:icon="exampleProps?.icon"
					:iconTrailing="exampleProps?.iconTrailing"
					:showIcon="exampleProps?.showIcon"
					:showIconTrailing="exampleProps?.showIconTrailing"
					:isDisabled="exampleProps?.isDisabled"
				>
					{{ exampleName }}
				</DBTabItem>
			</DBTabList>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/tab-item/tab-item.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBTabItem, DBTabList } from '../../../../../../output/angular/src';
import defaultComponentVariants from '../../../../../shared/tab-item.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-tab',
	templateUrl: './tab-item.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBTabItem, DBTabList],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : [],
	standalone: true
})
export class TabItemComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBTabItem"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
		><db-tab-list>
			<db-tab-item
				[active]="exampleProps?.active"
				[noText]="exampleProps?.noText"
				[icon]="exampleProps?.icon"
				[iconTrailing]="exampleProps?.iconTrailing"
				[showIcon]="exampleProps?.showIcon"
				[showIconTrailing]="exampleProps?.showIconTrailing"
				[isDisabled]="exampleProps?.isDisabled"
			>
				{{ exampleName }}
			</db-tab-item>
		</db-tab-list>
	</ng-template>
</app-default-component>
