// showcases/vue-showcase/src/control-panel/MetaNavigation.vue
<script setup lang="ts">
import { DBControlPanelMeta, DBLink } from "@components";
</script>

<template>
	<DBControlPanelMeta class="meta-workaround">
		<DBLink size="small" href="#"> Link 1 </DBLink>
		<DBLink size="small" href="#"> Link 2 </DBLink>
		<DBLink size="small" href="#"> Link 3 </DBLink>
	</DBControlPanelMeta>
</template>

// showcases/angular-showcase/src/app/control-panel/meta-navigation/meta-navigation.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DBControlPanelMeta, DBLink } from '@components';

@Component({
	selector: 'app-meta-navigation',
	schemas: [],
	imports: [DBControlPanelMeta, DBLink, FormsModule],
	templateUrl: './meta-navigation.component.html'
})
export class MetaNavigationComponent {}

<db-control-panel-meta>
	<db-link size="small" href="#"> Link 1 </db-link>
	<db-link size="small" href="#"> Link 2 </db-link>
	<db-link size="small" href="#"> Link 3 </db-link>
</db-control-panel-meta>
