// showcases/react-showcase/src/components/button/index.tsx
import { DBButton } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/button';
import { type DefaultComponentExample } from '../../../../shared/default-component-data';
import { type DBButtonProps } from '../../../../../output/react/src/components/button/model';

const getButton = ({
	variant,
	state,
	size,
	icntxt,
	icon,
	width
}: DBButtonProps) => (
	<DBButton
		variant={variant}
		state={state}
		size={size}
		icntxt={icntxt}
		icon={icon}
		width={width}>
		Button
	</DBButton>
);

const exampleMatrix: DefaultComponentExample[][] = [
	[
		{ example: getButton({}) },
		{ example: getButton({ variant: 'primary' }) },
		{ example: getButton({ variant: 'transparent' }) },
		{ example: getButton({ variant: 'semi-transparent' }) }
	],
	[{ example: getButton({}) }, { example: getButton({ state: 'loading' }) }],
	[{ example: getButton({}) }, { example: getButton({ size: 'small' }) }],
	[
		{ example: getButton({}) },
		{
			example: getButton({ icon: 'account', icntxt: true })
		},
		{ example: getButton({ icon: 'account' }) }
	],
	[{ example: getButton({}) }, { example: getButton({ width: 'full' }) }]
];
const variants = defaultComponentVariants.map((variant, index) => ({
	...variant,
	examples: variant.examples.map((example, exampleIndex) => ({
		...example,
		...exampleMatrix[index][exampleIndex]
	}))
}));

const ButtonComponent = () => {
	return (
		<DefaultComponent
			title="DBButton"
			variants={variants}></DefaultComponent>
	);
};

export default ButtonComponent;

// showcases/vue-showcase/src/components/button/Button.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/button";
import { DBButton } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="Button" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex }">
			<template v-if="exampleIndex === 0">
				<DBButton>Button</DBButton>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 0">
				<DBButton variant="primary"> Button</DBButton>
			</template>
			<template v-if="exampleIndex === 2 && variantIndex === 0">
				<DBButton variant="transparent"> Button</DBButton>
			</template>
			<template v-if="exampleIndex === 3 && variantIndex === 0">
				<DBButton variant="semi-transparent"> Button</DBButton>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 1">
				<DBButton state="loading"> Button</DBButton>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 2">
				<DBButton size="small"> Button</DBButton>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 3">
				<DBButton icon="account" :icntxt="true"> Button</DBButton>
			</template>
			<template v-if="exampleIndex === 2 && variantIndex === 3">
				<DBButton icon="account"> Button</DBButton>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 4">
				<DBButton width="full"> Button</DBButton>
			</template>
		</template>
	</DefaultComponent>
</template>
