// showcases/react-showcase/src/components/drawer/index.tsx
import { useState } from 'react';
import { DBButton, DBDrawer } from '../../../../../output/react/src';
import defaultComponentVariants from '../../../../shared/drawer.json';
import type { DBDrawerProps } from '../../../../../output/react/src/components/drawer/model';
import DefaultComponent from '../index';
import { getVariants } from '../data';

type AdditionalDrawerProps = {
	openDrawer: string;
	setOpenDrawer: (id?: string) => void;
};
const getDrawer = ({
	id,
	width,
	rounded,
	noBackdrop,
	withCloseButton,
	size,
	openDrawer,
	setOpenDrawer,
	direction,
	children
}: DBDrawerProps & AdditionalDrawerProps) => (
	<div>
		<DBDrawer
			noBackdrop={noBackdrop}
			withCloseButton={withCloseButton}
			rounded={rounded}
			width={width}
			size={size}
			direction={direction}
			open={openDrawer === id}
			onClose={() => {
				setOpenDrawer(undefined);
			}}>
			{children}
		</DBDrawer>
		<DBButton
			onClick={() => {
				setOpenDrawer(id);
			}}>
			Open: {children}
		</DBButton>
	</div>
);

const DrawerComponent = () => {
	const [openDrawer, setOpenDrawer] = useState<string | undefined>(undefined);
	return (
		<DefaultComponent
			title={'DBDrawer'}
			variants={getVariants(defaultComponentVariants, (props: any) =>
				getDrawer({
					...props,
					openDrawer,
					setOpenDrawer
				})
			)}></DefaultComponent>
	);
};

export default DrawerComponent;

// showcases/vue-showcase/src/components/drawer/Drawer.vue
<script setup lang="ts">
import { ref } from "vue";
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/drawer.json";
import { DBDrawer, DBButton } from "../../../../../output/vue/vue3/src";

const openDrawer = ref<string | undefined>(undefined);

const toggleDrawer = (example?: string) => {
	openDrawer.value = example;
};
</script>

<template>
	<DefaultComponent title="Drawer" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBDrawer
				:noBackdrop="exampleProps.noBackdrop"
				:withCloseButton="exampleProps.withCloseButton"
				:rounded="exampleProps.rounded"
				:width="exampleProps.width"
				:size="exampleProps.size"
				:direction="exampleProps.direction"
				:open="openDrawer && openDrawer === exampleName"
				@close="toggleDrawer(undefined)"
			>
				{{ exampleName }}
			</DBDrawer>
			<DBButton @click="toggleDrawer(exampleName)">
				Open: {{ exampleName }}
			</DBButton>
		</template>
	</DefaultComponent>
</template>
