// showcases/vue-showcase/src/components/card/Card.vue
<script setup lang="ts">
import { DBCard } from "../../../../../packages/v-core-components/src";
import defaultComponentVariants from "../../../../shared/card.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBCard" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<button
				type="button"
				v-if="exampleProps?.behavior === 'interactive'"
			>
				<DBCard
					:behavior="exampleProps?.behavior"
					:elevationLevel="exampleProps?.elevationLevel"
					:spacing="exampleProps?.spacing"
				>
					<strong>{{ exampleName }}</strong>
				</DBCard>
			</button>
			<DBCard
				v-if="exampleProps?.behavior !== 'interactive'"
				:behavior="exampleProps?.behavior"
				:elevationLevel="exampleProps?.elevationLevel"
				:spacing="exampleProps?.spacing"
			>
				<strong>{{ exampleName }}</strong>
			</DBCard>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/card/card.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBCard } from '../../../../../../packages/ngx-core-components/src';
import defaultComponentVariants from '../../../../../shared/card.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-card',
	templateUrl: './card.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBCard],
	standalone: true,
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class CardComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBCard"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		@if (exampleProps?.behavior === "interactive") {
			<button type="button" aria-label="button copy">
				<db-card
					[behavior]="exampleProps?.behavior"
					[elevationLevel]="exampleProps?.elevationLevel"
					[spacing]="exampleProps?.spacing"
				>
					<strong>{{ exampleName }}</strong>
				</db-card>
			</button>
		} @else {
			<db-card
				[behavior]="exampleProps?.behavior"
				[elevationLevel]="exampleProps?.elevationLevel"
				[spacing]="exampleProps?.spacing"
			>
				<strong>{{ exampleName }}</strong>
			</db-card>
		}
	</ng-template>
</app-default-component>
