// showcases/vue-showcase/src/components/link/Link.vue
<script setup lang="ts">
import { DBLink } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/link.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBLink" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBLink
				:variant="exampleProps?.variant"
				:href="exampleProps?.href"
				:disabled="exampleProps?.disabled"
				:size="exampleProps?.size"
				:content="exampleProps?.content"
				:showIcon="exampleProps?.showIcon"
				:wrap="exampleProps?.wrap"
			>
				{{ exampleName }}
			</DBLink>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/link/index.tsx
import { DBLink } from '@components';
import { type DBLinkProps } from '@components/src/components/link/model';
import defaultComponentVariants from '../../../../shared/link.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getLink = ({
	href,
	variant,
	disabled,
	size,
	content,
	children,
	showIcon,
	wrap
}: DBLinkProps) => (
	<DBLink
		href={href}
		variant={variant}
		disabled={disabled}
		size={size}
		content={content}
		showIcon={showIcon}
		wrap={wrap}>
		{children}
	</DBLink>
);

const LinkComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title={'DBLink'}
			variants={getVariants(
				defaultComponentVariants,
				getLink,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default LinkComponent;
