// showcases/react-showcase/src/components/select/index.tsx
import { DBSelect } from '@components';
import type { DBSelectProps } from '@components/src/components/select/model';
import { useState } from 'react';
import defaultComponentVariants from '../../../../shared/select.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getSelect = ({
	placeholder,
	label,
	options,
	icon,
	message,
	disabled,
	value,
	required,
	variant,
	showLabel,
	showMessage,
	invalidMessage,
	validMessage,
	validation,
	showRequiredAsterisk
}: DBSelectProps) => {
	const [mValue, setValue] = useState<string>(value);
	return (
		<DBSelect
			label={label}
			placeholder={placeholder}
			options={options}
			disabled={disabled}
			variant={variant}
			showLabel={showLabel}
			icon={icon}
			value={mValue}
			showRequiredAsterisk={showRequiredAsterisk}
			onChange={(event) => {
				setValue(event.target.value);
			}}
			message={message}
			required={required}
			showMessage={showMessage}
			invalidMessage={invalidMessage}
			validMessage={validMessage}
			validation={validation}
		/>
	);
};

const SelectComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBSelect"
			variants={getVariants(
				defaultComponentVariants,
				getSelect,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default SelectComponent;

// showcases/vue-showcase/src/components/select/Select.vue
<script setup lang="ts">
import { DBSelect } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/select.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBSelect" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBSelect
				:showRequiredAsterisk="exampleProps?.showRequiredAsterisk"
				:label="exampleProps?.label"
				:placeholder="exampleProps?.placeholder"
				:variant="exampleProps?.variant"
				:show-label="exampleProps?.showLabel"
				:options="exampleProps?.options"
				:disabled="exampleProps?.disabled"
				:icon="exampleProps?.icon"
				:value="exampleProps?.value"
				:message="exampleProps?.message"
				:required="exampleProps?.required"
				:showMessage="exampleProps?.showMessage"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:validation="exampleProps?.validation"
			/>
		</template>
	</DefaultComponent>
</template>
