// showcases/angular-showcase/src/app/components/form/form.component.ts
import { Component, type OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
	selector: 'app-form',
	templateUrl: './form.component.html',
	styleUrls: ['./form.component.scss']
})
export class FormComponent implements OnInit {
	input = '';
	checkbox = false;
	radio = '';
	select = '';
	textarea = '';
	toggle = false;

	checkboxControl = new FormControl();
	radioControl = new FormControl();
	selectControl = new FormControl();
	textareaControl = new FormControl();

	radioButtons = ['Radio 01', 'Radio 02', 'Radio 03'];

	ngOnInit(): void {
		this.checkboxControl.valueChanges.subscribe((value) => {
			this.checkbox = value;
		});
		this.radioControl.valueChanges.subscribe((value) => {
			this.radio = value;
		});
		this.selectControl.valueChanges.subscribe((value) => {
			this.select = value;
		});
		this.textareaControl.valueChanges.subscribe((value) => {
			this.textarea = value;
		});
	}

	showValues(): void {
		// eslint-disable-next-line no-alert
		alert(
			JSON.stringify({
				input: this.input,
				checkbox: this.checkbox,
				radio: this.radio,
				select: this.select,
				textarea: this.textarea,
				toggle: this.toggle
			})
		);
	}
}

<div class="form-container">
	<fieldset>
		<form>
			<p>DbInput:</p>
			<DBInput
				[(ngModel)]="input"
				name="username"
				label="Textinput"
				placeholder="Placeholder"
				description="Description"
				iconBefore="edit"
				ngDefaultControl
			></DBInput>
		</form>
	</fieldset>
	<fieldset>
		<p>DbButton:</p>
		<DBButton variant="primary" (click)="showValues()">
			Hi from Showcase!
		</DBButton>
		<h2>Output</h2>
		<dl>
			<dt>inputs value</dt>
			<dd>{{ input ? input : "No Input set" }}</dd>
		</dl>
	</fieldset>
</div>

// showcases/vue-showcase/src/components/form/Form.vue
<script setup lang="ts">
import { DBButton, DBInput, DBRadio } from "../../../../../output/vue/vue3/src";

import { ref } from "vue";
const input = ref("");
const radio = ref("");

const radioNames = ["X", "Y", "Z"];

// eslint-disable-next-line no-alert
const logAll = () => {
	alert(
		JSON.stringify({
			input: input.value,
			radio: radio.value
		})
	);
};
</script>

<template>
	<div class="form-container">
		<div>
			<form>
				<fieldset>
					<p>Input:</p>
					<DBInput
						label="Textinput"
						placeholder="Placeholder"
						description="Description"
						icon="edit"
						name="input-name"
						class="fullWidth"
						v-model:value="input"
					/>
					<p>Radio:</p>
					<ul>
						<li v-for="radioName in radioNames">
							<DBRadio
								@change="radio = radioName"
								name="radio-group"
								>Radio {{ radioName }}</DBRadio
							>
						</li>
					</ul>
					<p>Button:</p>
					<DBButton type="button" variant="primary" @click="logAll()">
						Hi from Showcase!
					</DBButton>
				</fieldset>
			</form>
		</div>
		<div>
			<h2>Output</h2>
			<dl>
				<dt>inputs value</dt>
				<dd>{{ input ? input : "No Input set" }}</dd>
			</dl>
			<dl>
				<dt>radio value</dt>
				<dd>{{ radio ? radio : "No radio set" }}</dd>
			</dl>
		</div>
	</div>
</template>
