// showcases/react-showcase/src/components/form/form-wrapper.tsx
import { DBButton } from '@db-ux/react-core-components/src';
import { type PropsWithChildren } from 'react';

const FormWrapper = ({
	children,
	uncontrolled,
	controlled
}: PropsWithChildren<{
	controlled: string | boolean | string[];
	uncontrolled: string | boolean | string[];
}>) => {
	return (
		<div className="form-container">
			<form>
				<fieldset>{children}</fieldset>
				<DBButton type="reset" data-testid="reset-button">
					Reset
				</DBButton>
			</form>
			<dl data-testid="data-list">
				<dt>Controlled:</dt>
				<dd>{controlled.toString()}</dd>
				<dt>Uncontrolled:</dt>
				<dd>{uncontrolled.toString()}</dd>
			</dl>
		</div>
	);
};

export default FormWrapper;

// showcases/vue-showcase/src/components/form/FormWrapper.vue
<script setup lang="ts">
const props = defineProps(["plain", "vmodel"]);
import { DBButton } from "@db-ux/v-core-components/src";
</script>

<template>
	<div class="form-container">
		<form>
			<fieldset><slot /></fieldset>
			<DBButton type="reset" data-testid="reset-button">Reset</DBButton>
		</form>
		<dl data-testid="data-list">
			<dt>Plain:</dt>
			<dd>{{ plain?.toString() }}</dd>
			<dt>VModel:</dt>
			<dd>{{ vmodel?.toString() }}</dd>
		</dl>
	</div>
</template>
