// showcases/angular-showcase/src/app/components/form/switches/switches.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { DBSwitch } from '../../../../../../../packages/ngx-core-components/src';
import { environment } from '../../../../environments/environment';
import { WrapperComponent } from '../wrapper/wrapper.component';

@Component({
	selector: 'app-switches',
	standalone: true,
	imports: environment.webComponents
		? [WrapperComponent, FormsModule, ReactiveFormsModule]
		: [WrapperComponent, DBSwitch, FormsModule, ReactiveFormsModule],
	templateUrl: './switches.component.html',
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class SwitchesComponent {
	plain = true;
	ngModel = true;
	formControl: FormControl = new FormControl(true);

	public handlePlainChange(event: Event | void) {
		if (!event) return;
		this.plain = (event.target as HTMLInputElement).checked;
	}
}

<app-form-wrapper
	[control]="formControl.value"
	[model]="ngModel"
	[plain]="plain"
	[signalForms]="signalForm.checked().value()"
>
	<fieldset>
		<legend>Different form approaches</legend>
		<db-switch
			(change)="handlePlainChange($event)"
			[checked]="plain"
			label="Plain"
			name="switch"
		></db-switch>
		<db-switch
			[(ngModel)]="ngModel"
			label="ngModel"
			name="switch"
		></db-switch>
		<db-switch
			[formControl]="formControl"
			label="formControl"
			name="switch"
		></db-switch>
		<db-switch
			[formField]="signalForm.checked"
			label="signalForms"
		></db-switch>
	</fieldset>
</app-form-wrapper>

// showcases/vue-showcase/src/components/form/Switches.vue
<script setup lang="ts">
import { ref } from "vue";
import { DBSwitch } from "../../../../../packages/v-core-components/src";
import FormWrapper from "./FormWrapper.vue";

const plain = ref(true);
const vModel = ref(true);
</script>

<template>
	<FormWrapper :plain="plain" :vmodel="vModel">
		<DBSwitch
			name="switch-1"
			@change="plain = $event.target.checked"
			:checked="plain"
		>
			Plain
		</DBSwitch>
		<DBSwitch name="switch-1" v-model:checked="vModel"> VModel </DBSwitch>
	</FormWrapper>
</template>
