// showcases/vue-showcase/src/components/DefaultComponent.vue
<script setup lang="ts">
import { inject, type Ref, ref, watch } from "vue";
import { useRoute } from "vue-router";
import { DBCard, DBDivider, DBLink } from "../../../../output/vue/src";
import {
	COLOR,
	COLOR_CONST,
	DENSITY,
	DENSITY_CONST
} from "../../../../packages/components/src/shared/constants";
import type {
	DefaultComponentExample,
	DefaultComponentProps,
	DefaultComponentVariants
} from "../../../shared/default-component-data";

interface DefaultExample extends DefaultComponentExample {
	name?: string;
	example?: any;
	style?: {
		display?: string;
		width?: string;
		height?: string;
	};
	className?: string;
	props?: any;
	code?: {
		html?: string; // We will generate this with reacts 'renderToString'
		angular?: string;
		react?: string;
		vue?: string;
	};
	children?: DefaultExample[];
	density?: string;
}
interface DefaultVariants extends DefaultComponentVariants {
	name: string;
	children?: DefaultExample[];
	examples: DefaultExample[];
	slotCode?: any;
}
/* Workaround see: https://vuejs.org/guide/typescript/composition-api.html#typing-component-props */
interface DefaultProps extends DefaultComponentProps {
	title: string;
	variants: DefaultVariants[];
}

const props = defineProps<DefaultProps>();

const route = useRoute();

const variantRef: Ref<DefaultVariants | undefined> = ref();
const variantRefIndex: Ref<number> = ref(-1);
const showcaseVariant = inject("$showcaseVariant");
const color = ref(COLOR.NEUTRAL_BG_LEVEL_1);

watch(
	() => route.query,
	async (query: any) => {
		if (query[COLOR_CONST] && query[COLOR_CONST] !== color.value) {
			color.value = query[COLOR_CONST];
		}
	}
);

if (route.query.page) {
	const foundVariant = props.variants.find(
		(variant) => variant.name.toLowerCase() === route.query.page
	);

	variantRef.value = foundVariant;
	if (foundVariant) {
		variantRefIndex.value = props.variants.indexOf(foundVariant);
	}
}

const createLinkFromVariantAndUrl = (variantName: string) => {
	let currentUrl = window.location.href;

	if (!currentUrl.includes("?")) {
		currentUrl += "?";
	}
	if (!currentUrl.includes("color=")) {
		currentUrl += `&color=${route.query[COLOR_CONST] || COLOR.NEUTRAL_BG_LEVEL_1}`;
	}
	if (!currentUrl.includes("density=")) {
		currentUrl += `&density=${
			route.query[DENSITY_CONST] || DENSITY.REGULAR
		}`;
	}
	return `${currentUrl}&page=${variantName.toLowerCase()}`;
};

const getLink = (variantName: string) => {
	return window && showcaseVariant === "vue"
		? createLinkFromVariantAndUrl(variantName)
		: "";
};

const openVariantLink = (event: MouseEvent, variantName: string) => {
	if (window) {
		event.preventDefault();
		window.open(createLinkFromVariantAndUrl(variantName), "_blank");
	}
};

const getElevation = (): "1" | "2" | "3" =>
	color.value.includes("3") ? "3" : color.value.includes("2") ? "2" : "1";
</script>

<template>
	<!-- TODO: Slots not working for nested components? -> Had to copy paste variant-cards...	-->
	<DBCard
		v-if="variantRef"
		class="variants-card"
		:elevation-level="getElevation()"
	>
		<div
			:role="variantRef.role"
			:aria-label="variantRef.role ? variantRef.name : undefined"
			class="variants-list"
		>
			<div
				v-for="(example, exampleIndex) in variantRef.examples"
				:style="example.style"
				:class="example.className"
				:data-density="example.density"
			>
				<slot
					name="example"
					v-bind:exampleProps="example.props ?? {}"
					v-bind:exampleName="example.name"
					v-bind:exampleIndex="exampleIndex"
					v-bind:variantIndex="variantRefIndex"
				></slot>
			</div>
		</div>
	</DBCard>
	<div v-if="!variantRef" class="default-container">
		<h1>{{ title }}</h1>
		<div v-for="(variant, variantIndex) in variants">
			<DBDivider></DBDivider>
			<DBLink
				class="link-headline"
				content="external"
				target="_blank"
				:href="getLink(variant.name)"
				@click="(event) => openVariantLink(event, variant.name)"
			>
				{{ variant.name }}
			</DBLink>
			<DBCard class="variants-card" :elevation-level="getElevation()">
				<div
					:role="variant.role"
					:aria-label="variant.role ? variant?.name : undefined"
					class="variants-list"
				>
					<div
						v-for="(example, exampleIndex) in variant.examples"
						:style="example.style"
						:class="example.className"
						:data-density="example.density"
					>
						<slot
							name="example"
							v-bind:exampleProps="example.props"
							v-bind:exampleName="example.name"
							v-bind:exampleIndex="exampleIndex"
							v-bind:variantIndex="variantIndex"
						></slot>
					</div>
				</div>
			</DBCard>
		</div>
	</div>
</template>

// showcases/react-showcase/src/components/default-component.tsx
import React, { useCallback, useState } from 'react';
import { DBCard, DBDivider, DBLink } from '../../../../output/react/src';
import useQuery from '../hooks/use-query';
import type {
	ReactDefaultComponentProps,
	ReactDefaultComponentVariants
} from '../../../shared/react-default-component-data';

const VariantList = ({
	name,
	examples,
	color,
	role,
	SlotCode
}: ReactDefaultComponentVariants) => {
	const getElevation = useCallback(
		() => (color?.includes('3') ? '3' : color?.includes('2') ? '2' : '1'),
		[color]
	);

	const [open, setOpen] = useState<boolean>();

	return (
		<DBCard
			className="variants-card db-code-docs"
			elevationLevel={getElevation()}>
			<div
				role={role}
				aria-label={role ? name : undefined}
				className="variants-list">
				{examples.map((example, exampleIndex) => (
					<div
						key={`${example.name}-${exampleIndex}`}
						style={example.style}
						className={example.className}>
						{example.example}
					</div>
				))}
			</div>

			{SlotCode && (
				<details
					className="code-details"
					onToggle={() => {
						setOpen(!open);
					}}>
					<summary
						className="db-button code-button"
						data-size="small"
						data-variant="filled">
						{open ? 'Hide code' : 'Show code'}
					</summary>
					<div data-density="functional">
						<div className="backdrop" />
						<DBCard className="code" spacing="small">
							<SlotCode />
						</DBCard>
					</div>
				</details>
			)}
		</DBCard>
	);
};

const DefaultComponent = ({
	title,
	variants,
	subComponent,
	isSubComponent,
	componentName
}: ReactDefaultComponentProps) => {
	const redirectURLSearchParams = process?.env?.REDIRECT_URL_SEARCH_PARAMS
		? process.env.REDIRECT_URL_SEARCH_PARAMS === 'true'
		: true;
	const pageName = useQuery(redirectURLSearchParams)[4];
	const color = useQuery(redirectURLSearchParams)[2];

	const getHref = (variantName: string): string => {
		if (typeof window !== 'undefined') {
			const searchParams = new URLSearchParams(
				window.location.href.split('?')[1]
			);
			searchParams.set('page', variantName.toLowerCase());
			return `${window.location.href.split('?')[0]}?${searchParams.toString()}`;
		}

		return '';
	};

	const openVariantInNewWindow = (
		event: React.MouseEvent<HTMLAnchorElement>,
		variantName: string
	) => {
		if (
			typeof window === 'undefined' ||
			!window.location.origin ||
			!window.location.href
		) {
			return;
		}

		const currentUrl = window.location.href.split('?');
		const rawComponentUrl = currentUrl[0];
		const searchParams = new URLSearchParams(currentUrl[1] ?? '');
		searchParams.set('page', variantName.toLowerCase());

		const regexComponentOverviewFragment = /\/[a-z\d\-_]*\/overview/;

		const openUrl = componentName
			? `${rawComponentUrl.replace(regexComponentOverviewFragment, `/${componentName}/overview`)}?${searchParams.toString()}`
			: `${currentUrl[0]}?${searchParams.toString()}`;

		window.open(openUrl, '_blank');
	};

	if (pageName) {
		const foundVariant = variants.find(
			(variant) => variant.name.toLowerCase() === pageName
		);
		if (foundVariant) {
			return <VariantList {...foundVariant} color={color} />;
		}
	}

	const HeadlineTag = isSubComponent ? 'h2' : 'h1';

	return (
		<>
			<div className="default-container">
				<HeadlineTag>{title}</HeadlineTag>
				{variants?.map((variant, index) => (
					<div key={`${variant.name}-${index}`}>
						<DBDivider></DBDivider>
						<DBLink
							className="link-headline"
							content="external"
							target="_blank"
							onClick={(event) => {
								openVariantInNewWindow(event, variant.name);
							}}
							href={getHref(variant.name)}>
							{variant.name}
						</DBLink>
						<VariantList {...variant} color={color} />
					</div>
				))}
			</div>
			{subComponent}
		</>
	);
};

export default DefaultComponent;
