// showcases/vue-showcase/src/components/tab/Tab.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tab.json";
import { DBTab } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTab" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTab
				:name="exampleName"
				:index="exampleProps.index"
				:active="exampleProps.active"
				:noText="exampleProps.noText"
				:icon="exampleProps.icon"
				:iconAfter="exampleProps.iconAfter"
				:width="exampleProps.width"
				:alignment="exampleProps.alignment"
			>
				{{ exampleName }}
			</DBTab>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/tab/index.tsx
import { DBTab } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/tab.json';
import type { DBTabProps } from '../../../../../output/react/src/components/tab/model';
import { getVariants } from '../data';

const getTab = ({
	children,
	active,
	noText,
	icon,
	iconAfter,
	width,
	alignment,
	index
}: DBTabProps) => (
	<DBTab
		name={children}
		index={index}
		active={active}
		noText={noText}
		icon={icon}
		iconAfter={iconAfter}
		width={width}
		alignment={alignment}>
		{children}
	</DBTab>
);

const TabComponent = () => {
	return (
		<DefaultComponent
			title="DBTab"
			variants={getVariants(
				defaultComponentVariants,
				getTab
			)}></DefaultComponent>
	);
};

export default TabComponent;
