// showcases/react-showcase/src/components/alert/index.tsx
import { DBAlert } from "../../../../../output/react/src";
import DefaultComponent from "../index";
import type { DefaultComponentVariants } from "../data";

const variants: DefaultComponentVariants[] = [
	{
		name: "Type",
		examples: [
			{
				name: "(Default) Alert",
				style: { width: "100%" },
				example: (
					<DBAlert
						type="alert"
						headline="Headline"
						link={{ href: "#" }}
						slotLink="Link">
						Type Something
					</DBAlert>
				),
				code: '<DBAlert type="alert" headline="Headline" link={{ href: "#" }} slotLink="Link">Type Something</DBAlert>',
			},
			{
				name: "Inline",
				style: { width: "100%" },
				example: (
					<DBAlert
						type="inline"
						headline="Headline"
						link={{ href: "#" }}
						slotLink="Link">
						Type Something
					</DBAlert>
				),
				code: '<DBAlert type="inline" headline="Headline" link={{ href: "#" }} slotLink="Link">Type Something</DBAlert>',
			},
		],
	},
	{
		name: "Variant",
		examples: [
			{
				name: "(Default) Adaptive",
				style: { width: "100%" },
				example: (
					<DBAlert
						icon="account"
						headline="Headline"
						link={{ href: "#" }}
						slotLink="Link">
						Type Something
					</DBAlert>
				),
				code: '<DBAlert icon="account" headline="Headline" link={{ href: "#" }} slotLink="Link">Type Something</DBAlert>',
			},
			{
				name: "Critical",
				style: { width: "100%" },
				example: (
					<DBAlert
						variant="critical"
						headline="Headline"
						link={{ href: "#" }}
						slotLink="Link">
						Type Something
					</DBAlert>
				),
				code: '<DBAlert variant="critical" headline="Headline" link={{ href: "#" }} slotLink="Link">Type Something</DBAlert>',
			},
			{
				name: "Information",
				style: { width: "100%" },
				example: (
					<DBAlert
						variant="informational"
						headline="Headline"
						link={{ href: "#" }}
						slotLink="Link">
						Type Something
					</DBAlert>
				),
				code: '<DBAlert variant="informational" headline="Headline" link={{ href: "#" }} slotLink="Link">Type Something</DBAlert>',
			},
			{
				name: "Success",
				style: { width: "100%" },
				example: (
					<DBAlert
						variant="successful"
						headline="Headline"
						link={{ href: "#" }}
						slotLink="Link">
						Type Something
					</DBAlert>
				),
				code: '<DBAlert variant="successful" headline="Headline" link={{ href: "#" }} slotLink="Link">Type Something</DBAlert>',
			},
			{
				name: "Warning",
				style: { width: "100%" },
				example: (
					<DBAlert
						variant="warning"
						headline="Headline"
						link={{ href: "#" }}
						slotLink="Link">
						Type Something
					</DBAlert>
				),
				code: '<DBAlert variant="warning" headline="Headline" link={{ href: "#" }} slotLink="Link">Type Something</DBAlert>',
			},
		],
	},
	{
		name: "Content",
		examples: [
			{
				name: "Headline & Text & Link & Icon",
				style: { width: "100%" },
				example: (
					<DBAlert
						headline="Headline"
						link={{ href: "#" }}
						slotLink="Link"
						icon="account">
						Type Something
					</DBAlert>
				),
				code: '<DBAlert icon="account" headline="Headline" link={{ href: "#" }} slotLink="Link">Type Something</DBAlert>',
			},
			{
				name: "Headline & Text & Link",
				style: { width: "100%" },
				example: (
					<DBAlert
						headline="Headline"
						link={{ href: "#" }}
						slotLink="Link">
						Type Something
					</DBAlert>
				),
				code: '<DBAlert headline="Headline" link={{ href: "#" }} slotLink="Link">Type Something</DBAlert>',
			},
			{
				name: "Text & Link",
				style: { width: "100%" },
				example: (
					<DBAlert link={{ href: "#" }} slotLink="Link">
						Type Something
					</DBAlert>
				),
				code: '<DBAlert link={{ href: "#" }} slotLink="Link">Type Something</DBAlert>',
			},
			{
				name: "Text",
				style: { width: "100%" },
				example: <DBAlert>Type Something</DBAlert>,
				code: "<DBAlert>Type Something</DBAlert>",
			},
		],
	},
	{
		name: "Behaviour",
		examples: [
			{
				name: "Closable",
				style: { width: "100%" },
				example: (
					<DBAlert
						headline="Headline"
						link={{ href: "#" }}
						slotLink="Link"
						onClick={() => {
							/* eslint-disable-next-line no-alert */
							alert("click close button");
						}}>
						Type Something
					</DBAlert>
				),
				code: '<DBAlert headline="Headline" link={{ href: "#" }} slotLink="Link" onClick={()=>{alert("click close button")}}>Type Something</DBAlert>',
			},
		],
	},
];

const AlertComponent = () => {
	return (
		<DefaultComponent
			title={"DBAlert"}
			variants={variants}></DefaultComponent>
	);
};

export default AlertComponent;

// showcases/vue-showcase/src/components/alert/Alert.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/alert";
import { DBAlert } from "../../../../../output/vue/vue3/src";
import { DefaultComponentVariants } from "../../../../shared/default-component-data";

defaultComponentVariants.forEach((variant) => {
	variant.examples[0].code = "<Alert>Alert</Alert>";
});

const linkSlot = "<template v-slot:link>Link</template>";

// Type
defaultComponentVariants[0].examples[0].code = `<DBAlert type="alert" headline="Headline" :link=\"{href: "#"}\">Alert ${linkSlot}</DBAlert>`;
defaultComponentVariants[0].examples[1].code = `<DBAlert type="inline" headline="Headline" :link=\"{href: "#"}\">Alert ${linkSlot}</DBAlert>`;

// Variant
defaultComponentVariants[1].examples[0].code = `<DBAlert icon="account" type="alert" headline="Headline" :link=\"{href: "#"}\">Alert ${linkSlot}</DBAlert>`;

defaultComponentVariants[1].examples[1].code = `<DBAlert variant="critical" headline="Headline" :link=\"{href: "#"}\">Alert ${linkSlot}</DBAlert>`;

defaultComponentVariants[1].examples[2].code = `<DBAlert variant="informational" headline="Headline" :link=\"{href: "#"}\">Alert ${linkSlot}</DBAlert>`;
defaultComponentVariants[1].examples[3].code = `<DBAlert variant="successful" headline="Headline" :link=\"{href: "#"}\">Alert ${linkSlot}</DBAlert>`;

defaultComponentVariants[1].examples[4].code = `<DBAlert variant="warning" headline="Headline" :link=\"{href: "#"}\">Alert ${linkSlot}</DBAlert>`;

// Content
defaultComponentVariants[2].examples[0].code = `<DBAlert icon="account" headline="Headline" :link=\"{href: "#"}\">Headline & Text & Link & Icon ${linkSlot}</DBAlert>`;
defaultComponentVariants[2].examples[1].code = `<DBAlert headline="Headline" :link=\"{href: "#"}\">Headline & Text & Link ${linkSlot}</DBAlert>`;
defaultComponentVariants[2].examples[2].code = `<DBAlert :link=\"{href: "#"}\">Text & Link ${linkSlot}</DBAlert>`;
defaultComponentVariants[2].examples[3].code = `<DBAlert>Text</DBAlert>`;

// Behaviour
defaultComponentVariants[3].examples[0].code = `<DBAlert headline="Headline" :link=\"{href: "#"}\" onClick={()=>{alert("click close button")}}>Alert ${linkSlot}</DBAlert>`;
defaultComponentVariants[3].examples[1].code = `<DBAlert headline="Headline" :link=\"{href: "#"}\" behaviour="permanent">Alert ${linkSlot}</DBAlert>`;

const onClick = () => {
	alert("click close button");
};
</script>

<template>
	<DefaultComponent title="DBAlert" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName }">
			<template v-if="exampleIndex === 0 && variantIndex === 0">
				<DBAlert type="alert" headline="Headline" :link="{ href: '#' }">
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 0">
				<DBAlert
					type="inline"
					headline="Headline"
					:link="{ href: '#' }"
				>
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>

			<template v-if="exampleIndex === 0 && variantIndex === 1">
				<DBAlert
					icon="account"
					type="alert"
					headline="Headline"
					:link="{ href: '#' }"
				>
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 1">
				<DBAlert
					variant="critical"
					headline="Headline"
					:link="{ href: '#' }"
				>
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>
			<template v-if="exampleIndex === 2 && variantIndex === 1">
				<DBAlert
					variant="informational"
					headline="Headline"
					:link="{ href: '#' }"
				>
					{{ exampleName }}
					<template v-slot:link>Link</template>
				</DBAlert>
			</template>
			<template v-if="exampleIndex === 3 && variantIndex === 1">
				<DBAlert
					variant="successful"
					headline="Headline"
					:link="{ href: '#' }"
				>
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>
			<template v-if="exampleIndex === 4 && variantIndex === 1">
				<DBAlert
					variant="warning"
					headline="Headline"
					:link="{ href: '#' }"
				>
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>

			<template v-if="exampleIndex === 0 && variantIndex === 2">
				<DBAlert
					icon="account"
					headline="Headline"
					:link="{ href: '#' }"
				>
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 2">
				<DBAlert headline="Headline" :link="{ href: '#' }">
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>
			<template v-if="exampleIndex === 2 && variantIndex === 2">
				<DBAlert :link="{ href: '#' }">
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>
			<template v-if="exampleIndex === 3 && variantIndex === 2">
				<DBAlert>{{ exampleName }}</DBAlert>
			</template>

			<template v-if="exampleIndex === 0 && variantIndex === 3">
				<DBAlert
					headline="Headline"
					@click="onClick()"
					:link="{ href: '#' }"
				>
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 3">
				<DBAlert
					headline="Headline"
					:link="{ href: '#' }"
					behaviour="permanent"
				>
					{{ exampleName }}
					<template v-slot:link> Link </template>
				</DBAlert>
			</template>
		</template>
	</DefaultComponent>
</template>
