// storybooks/vue-storybook/src/templates/table-kitchen-sink/components/DebouncedInput.vue
<script setup lang="ts">
import { DBInput } from "@components";
import { ref, watch } from "vue";

interface Props {
	label: string;
	placeholder: string;
	modelValue: string | number;
	debounce?: number;
}

const props = withDefaults(defineProps<Props>(), {
	debounce: 500
});

const emit = defineEmits<{
	"update:modelValue": [value: string | number];
}>();

const value = ref<string | number>(props.modelValue);

watch(
	() => props.modelValue,
	(newVal) => {
		value.value = newVal;
	}
);

let timeout: ReturnType<typeof setTimeout>;
watch(value, (newVal) => {
	clearTimeout(timeout);
	timeout = setTimeout(() => {
		emit("update:modelValue", newVal);
	}, props.debounce);
});
</script>

<template>
	<DBInput
		variant="floating"
		:label="label"
		:placeholder="placeholder"
		v-model="value"
	/>
</template>

// storybooks/angular-storybook/src/templates/table-kitchen-sink/components/debounced-input.component.ts
import {
	Component,
	EventEmitter,
	Input,
	OnDestroy,
	OnInit,
	Output
} from '@angular/core';
import { DBInput } from '@components';

@Component({
	selector: 'app-debounced-input',
	standalone: true,
	imports: [DBInput],
	template: `
		<db-input
			[variant]="'floating'"
			[label]="label"
			[placeholder]="placeholder"
			[value]="value"
			(valueChange)="onValueChange($event)" />
	`
})
export class DebouncedInputComponent implements OnInit, OnDestroy {
	@Input() label = '';
	@Input() placeholder = '';
	@Input() value: string | number = '';
	@Input() debounce = 500;
	@Output() valueChange = new EventEmitter<string | number>();

	private timeout?: ReturnType<typeof setTimeout>;

	ngOnInit() {}

	ngOnDestroy() {
		if (this.timeout) {
			clearTimeout(this.timeout);
		}
	}

	onValueChange(newValue: string | number) {
		this.value = newValue;
		if (this.timeout) {
			clearTimeout(this.timeout);
		}
		this.timeout = setTimeout(() => {
			this.valueChange.emit(newValue);
		}, this.debounce);
	}
}
