// storybooks/vue-storybook/src/templates/table-kitchen-sink/components/Filter.vue
<script setup lang="ts" generic="T extends RowData">
import { DBButton, DBPopover, DBStack, DBTooltip } from "@components";
import type {
	Column,
	RowData,
	StockFeatures,
	Table
} from "@tanstack/vue-table";
import { computed, defineProps } from "vue";
import DebouncedInput from "./DebouncedInput.vue";

interface Props {
	column: Column<StockFeatures, T, unknown>;
	table: Table<StockFeatures, T>;
}

const props = defineProps<Props>();

const firstValue = computed(() =>
	props.table.getPreFilteredRowModel().flatRows[0]?.getValue(props.column.id)
);

const columnFilterValue = computed(() => props.column.getFilterValue());
const uniqueValues = computed(() => props.column.getFacetedUniqueValues());

const sortedUniqueValues = computed(() =>
	typeof firstValue.value === "number"
		? []
		: Array.from(uniqueValues.value.keys()).sort()
);

const minMax = computed(() => props.column.getFacetedMinMaxValues());
const min = computed(() => Number(minMax.value?.[0] ?? ""));
const max = computed(() => Number(minMax.value?.[1]));

const updateMinFilter = (value: string | number) => {
	props.column.setFilterValue((old: [number, number]) => [value, old?.[1]]);
};

const updateMaxFilter = (value: string | number) => {
	props.column.setFilterValue((old: [number, number]) => [old?.[0], value]);
};
</script>

<template>
	<DBPopover placement="top" :trigger="() => $refs.triggerButton">
		<template #trigger>
			<DBButton
				ref="triggerButton"
				size="small"
				variant="ghost"
				noText
				icon="funnel"
			>
				Filter
				<DBTooltip placement="right">Filter</DBTooltip>
			</DBButton>
		</template>
		<DBStack v-if="typeof firstValue === 'number'">
			<DebouncedInput
				type="number"
				:min="min"
				:max="max"
				:modelValue="(columnFilterValue as [number, number])?.[0] ?? ''"
				@update:modelValue="updateMinFilter"
				label="Minimum"
				:placeholder="`Min ${minMax?.[0] ? `(${min})` : ''}`"
			/>
			<DebouncedInput
				type="number"
				:min="min"
				:max="max"
				:modelValue="(columnFilterValue as [number, number])?.[1] ?? ''"
				@update:modelValue="updateMaxFilter"
				label="Maximum"
				:placeholder="`Max ${minMax?.[1] ? `(${max})` : ''}`"
			/>
		</DBStack>
		<template v-else>
			<datalist :id="column.id + 'list'">
				<option
					v-for="value in sortedUniqueValues.slice(0, 5000)"
					:key="value"
					:value="value"
				/>
			</datalist>
			<DebouncedInput
				type="text"
				:modelValue="(columnFilterValue as string) ?? ''"
				@update:modelValue="column.setFilterValue"
				:placeholder="`Search... (${uniqueValues.size})`"
				label="Search"
				:list="column.id + 'list'"
			/>
		</template>
	</DBPopover>
</template>

// storybooks/angular-storybook/src/templates/table-kitchen-sink/components/filter.component.ts
import { Component, Input } from '@angular/core';
import { DBButton, DBPopover, DBStack, DBTooltip } from '@components';
import type {
	Column,
	RowData,
	StockFeatures,
	Table
} from '@tanstack/angular-table';
import { DebouncedInputComponent } from './debounced-input.component';

@Component({
	selector: 'app-filter',
	standalone: true,
	imports: [DBButton, DBPopover, DBStack, DBTooltip, DebouncedInputComponent],
	template: `
		<db-popover [placement]="'top'">
			<db-button
				trigger
				[size]="'small'"
				[variant]="'ghost'"
				[noText]="true"
				[icon]="'funnel'">
				Filter
				<db-tooltip [placement]="'right'">Filter</db-tooltip>
			</db-button>
			@if (isNumber) {
				<db-stack>
					<app-debounced-input
						[label]="'Minimum'"
						[placeholder]="minPlaceholder"
						[value]="minValue"
						(valueChange)="updateMinFilter($event)" />
					<app-debounced-input
						[label]="'Maximum'"
						[placeholder]="maxPlaceholder"
						[value]="maxValue"
						(valueChange)="updateMaxFilter($event)" />
				</db-stack>
			} @else {
				<datalist [id]="column.id + 'list'">
					@for (
						value of sortedUniqueValues.slice(0, 5000);
						track value
					) {
						<option [value]="value"></option>
					}
				</datalist>
				<app-debounced-input
					[label]="'Search'"
					[placeholder]="searchPlaceholder"
					[value]="stringValue"
					(valueChange)="column.setFilterValue($event)" />
			}
		</db-popover>
	`
})
export class FilterComponent<T extends RowData> {
	@Input() column!: Column<StockFeatures, T, unknown>;
	@Input() table!: Table<StockFeatures, T>;

	get firstValue() {
		return this.table
			.getPreFilteredRowModel()
			.flatRows[0]?.getValue(this.column.id);
	}

	get isNumber() {
		return typeof this.firstValue === 'number';
	}

	get columnFilterValue() {
		return this.column.getFilterValue();
	}

	get uniqueValues() {
		return this.column.getFacetedUniqueValues();
	}

	get sortedUniqueValues() {
		return this.isNumber ? [] : Array.from(this.uniqueValues.keys()).sort();
	}

	get minMax() {
		return this.column.getFacetedMinMaxValues();
	}

	get min() {
		return Number(this.minMax?.[0] ?? '');
	}

	get max() {
		return Number(this.minMax?.[1]);
	}

	get minValue() {
		return (this.columnFilterValue as [number, number])?.[0] ?? '';
	}

	get maxValue() {
		return (this.columnFilterValue as [number, number])?.[1] ?? '';
	}

	get stringValue() {
		return (this.columnFilterValue as string) ?? '';
	}

	get minPlaceholder() {
		return 'Min ' + (this.minMax?.[0] ? '(' + this.min + ')' : '');
	}

	get maxPlaceholder() {
		return 'Max ' + (this.minMax?.[1] ? '(' + this.max + ')' : '');
	}

	get searchPlaceholder() {
		return 'Search... (' + this.uniqueValues.size + ')';
	}

	updateMinFilter(value: string | number) {
		this.column.setFilterValue((old: [number, number]) => [
			value,
			old?.[1]
		]);
	}

	updateMaxFilter(value: string | number) {
		this.column.setFilterValue((old: [number, number]) => [
			old?.[0],
			value
		]);
	}
}
