// showcases/react-showcase/src/control-panel/secondary-actions.tsx
import {
	DBButton,
	DBControlPanelSecondaryActions
} from '@db-ux/react-core-components/src';

const SecondaryActions = () => {
	return (
		<DBControlPanelSecondaryActions>
			<DBButton icon="x_placeholder" variant="ghost" noText>
				Profile
			</DBButton>
			<DBButton icon="x_placeholder" variant="ghost" noText>
				Notification
			</DBButton>
			<DBButton icon="x_placeholder" variant="ghost" noText>
				Help
			</DBButton>
		</DBControlPanelSecondaryActions>
	);
};

export default SecondaryActions;

// showcases/angular-showcase/src/app/control-panel/secondary-actions/secondary-actions.component.ts
import { Component } from '@angular/core';
import { DBButton, DBControlPanelSecondaryActions } from '@components';

@Component({
	selector: 'app-secondary-actions',
	schemas: [],
	imports: [DBControlPanelSecondaryActions, DBButton],
	templateUrl: './secondary-actions.component.html'
})
export class SecondaryActionsComponent {}

<db-control-panel-secondary-actions>
	<db-button [noText]="true" icon="x_placeholder" variant="ghost">
		Profile
	</db-button>
	<db-button [noText]="true" icon="x_placeholder" variant="ghost">
		Notification
	</db-button>
	<db-button [noText]="true" icon="x_placeholder" variant="ghost">
		Help
	</db-button>
</db-control-panel-secondary-actions>
