// storybooks/vue-storybook/src/templates/table-kitchen-sink/components/CustomTable.vue
<script setup lang="ts" generic="T extends RowData">
import {
	DBButton,
	DBTable,
	DBTableBody,
	DBTableDataCell,
	DBTableFooter,
	DBTableHead,
	DBTableHeaderCell,
	DBTableRow,
	DBTooltip
} from "@components";
import {
	FlexRender,
	type RowData,
	type StockFeatures,
	type Table
} from "@tanstack/vue-table";
import Filter from "./Filter.vue";

interface Props {
	table: Table<StockFeatures, T>;
}

defineProps<Props>();

const getSortIcon = (isSorted: false | "asc" | "desc") => {
	if (!isSorted) return "arrows_vertical";
	return isSorted === "asc" ? "sort_down" : "sort_up";
};

const getSortTooltip = (isSorted: false | "asc" | "desc") => {
	if (!isSorted) return "Sort ascending";
	return isSorted === "asc" ? "Sort descending" : "Sort ascending";
};
</script>

<template>
	<DBTable
		:columnSizes="{ 0: 'min-content', 4: 'min-content', 5: 'min-content' }"
	>
		<DBTableHead>
			<DBTableRow
				v-for="headerGroup in table.getHeaderGroups()"
				:key="headerGroup.id"
				interactive
			>
				<DBTableHeaderCell
					v-for="header in headerGroup.headers"
					:key="header.id"
					:colSpan="header.colSpan"
					class="relative"
				>
					<div
						v-if="!header.isPlaceholder"
						style="
							display: inline-flex;
							gap: var(--db-spacing-fixed-3xs);
							overflow: hidden;
							inline-size: fit-content;
							block-size: fit-content;
						"
					>
						<span style="white-space: nowrap">
							<FlexRender
								:render="header.column.columnDef.header"
								:props="header.getContext()"
							/>
						</span>
						<DBButton
							v-if="header.column.getCanSort()"
							variant="ghost"
							size="small"
							@click="
								header.column.getToggleSortingHandler()?.(
									$event
								)
							"
							noText
							:icon="getSortIcon(header.column.getIsSorted())"
						>
							<DBTooltip placement="top">
								{{
									getSortTooltip(header.column.getIsSorted())
								}}
							</DBTooltip>
						</DBButton>
						<Filter
							v-if="header.column.getCanFilter()"
							:column="header.column"
							:table="table"
						/>
					</div>
				</DBTableHeaderCell>
			</DBTableRow>
		</DBTableHead>
		<DBTableBody>
			<DBTableRow
				v-for="row in table.getRowModel().rows"
				:key="row.id"
				interactive
			>
				<DBTableDataCell
					v-for="cell in row.getVisibleCells()"
					:key="cell.id"
				>
					<FlexRender
						:render="cell.column.columnDef.cell"
						:props="cell.getContext()"
					/>
				</DBTableDataCell>
			</DBTableRow>
		</DBTableBody>
		<DBTableFooter>
			<DBTableRow
				v-for="footerGroup in table.getFooterGroups()"
				:key="footerGroup.id"
			>
				<DBTableHeaderCell
					v-for="header in footerGroup.headers"
					:key="header.id"
					:colSpan="header.colSpan"
				>
					<FlexRender
						v-if="!header.isPlaceholder"
						:render="header.column.columnDef.footer"
						:props="header.getContext()"
					/>
				</DBTableHeaderCell>
			</DBTableRow>
		</DBTableFooter>
	</DBTable>
</template>

// storybooks/react-storybook/src/templates/table-kitchen-sink/components/CustomTable.tsx
import {
	DBButton,
	DBTable,
	DBTableBody,
	DBTableDataCell,
	DBTableFooter,
	DBTableHead,
	DBTableHeaderCell,
	DBTableRow,
	DBTooltip
} from '@components';
import {
	flexRender,
	type HeaderGroup,
	type Row,
	type RowData,
	type StockFeatures,
	type Table
} from '@tanstack/react-table';
import Filter from './Filter';

function getTableHeaderGroups<T extends RowData>(
	table: Table<StockFeatures, T>
): [HeaderGroup<StockFeatures, T>[], HeaderGroup<StockFeatures, T>[]] {
	return [table.getHeaderGroups(), table.getFooterGroups()];
}

function getRowGroup<T extends RowData>(row: Row<StockFeatures, T>) {
	return row.getVisibleCells();
}

type Props<T extends RowData> = {
	table: Table<StockFeatures, T>;
};

export function CustomTable<T extends RowData>({ table }: Props<T>) {
	const [headerGroups, footerGroup] = getTableHeaderGroups(table);

	return (
		<DBTable
			columnSizes={{
				0: 'min-content',
				4: 'min-content',
				5: 'min-content'
			}}>
			<DBTableHead>
				{headerGroups.map((headerGroup) => (
					<DBTableRow interactive key={headerGroup.id}>
						{headerGroup.headers.map((header) => (
							<DBTableHeaderCell
								className="relative"
								key={header.id}
								colSpan={header.colSpan}>
								{header.isPlaceholder ? null : (
									<div
										style={{
											display: 'inline-flex',
											gap: 'var(--db-spacing-fixed-3xs)',
											overflow: 'hidden',
											inlineSize: 'fit-content',
											blockSize: 'fit-content'
										}}>
										<span style={{ whiteSpace: 'nowrap' }}>
											{flexRender(
												header.column.columnDef.header,
												header.getContext()
											)}
										</span>
										{header.column.getCanSort() && (
											<DBButton
												variant="ghost"
												size="small"
												onClick={header.column.getToggleSortingHandler()}
												noText
												icon={
													header.column.getIsSorted()
														? header.column.getIsSorted() ===
															'asc'
															? 'sort_down'
															: 'sort_up'
														: 'arrows_vertical'
												}>
												<DBTooltip placement="top">
													{header.column.getIsSorted()
														? header.column.getIsSorted() ===
															'asc'
															? 'Sort descending'
															: 'Sort ascending'
														: 'Sort ascending'}
												</DBTooltip>
											</DBButton>
										)}

										{header.column.getCanFilter() ? (
											<Filter
												column={header.column}
												table={table}
											/>
										) : null}
									</div>
								)}
							</DBTableHeaderCell>
						))}
					</DBTableRow>
				))}
			</DBTableHead>
			<DBTableBody>
				{table.getRowModel().rows.map((row) => (
					<DBTableRow interactive key={row.id}>
						{getRowGroup(row).map((cell) => (
							<DBTableDataCell key={cell.id}>
								{flexRender(
									cell.column.columnDef.cell,
									cell.getContext()
								)}
							</DBTableDataCell>
						))}
					</DBTableRow>
				))}
			</DBTableBody>
			<DBTableFooter>
				{footerGroup.map((footerGroup) => (
					<DBTableRow key={footerGroup.id}>
						{footerGroup.headers.map((header) => (
							<DBTableHeaderCell
								key={header.id}
								colSpan={header.colSpan}>
								{header.isPlaceholder
									? null
									: flexRender(
											header.column.columnDef.footer,
											header.getContext()
										)}
							</DBTableHeaderCell>
						))}
					</DBTableRow>
				))}
			</DBTableFooter>
		</DBTable>
	);
}

export default CustomTable;
