// storybooks/vue-storybook/src/templates/table-kitchen-sink/components/Filter.vue
<script setup lang="ts" generic="T extends RowData">
import { DBButton, DBPopover, DBStack, DBTooltip } from "@components";
import type {
	Column,
	RowData,
	StockFeatures,
	Table
} from "@tanstack/vue-table";
import { computed, defineProps } from "vue";
import DebouncedInput from "./DebouncedInput.vue";

interface Props {
	column: Column<StockFeatures, T, unknown>;
	table: Table<StockFeatures, T>;
}

const props = defineProps<Props>();

const firstValue = computed(() =>
	props.table.getPreFilteredRowModel().flatRows[0]?.getValue(props.column.id)
);

const columnFilterValue = computed(() => props.column.getFilterValue());
const uniqueValues = computed(() => props.column.getFacetedUniqueValues());

const sortedUniqueValues = computed(() =>
	typeof firstValue.value === "number"
		? []
		: Array.from(uniqueValues.value.keys()).sort()
);

const minMax = computed(() => props.column.getFacetedMinMaxValues());
const min = computed(() => Number(minMax.value?.[0] ?? ""));
const max = computed(() => Number(minMax.value?.[1]));

const updateMinFilter = (value: string | number) => {
	props.column.setFilterValue((old: [number, number]) => [value, old?.[1]]);
};

const updateMaxFilter = (value: string | number) => {
	props.column.setFilterValue((old: [number, number]) => [old?.[0], value]);
};
</script>

<template>
	<DBPopover placement="top" :trigger="() => $refs.triggerButton">
		<template #trigger>
			<DBButton
				ref="triggerButton"
				size="small"
				variant="ghost"
				noText
				icon="funnel"
			>
				Filter
				<DBTooltip placement="right">Filter</DBTooltip>
			</DBButton>
		</template>
		<DBStack v-if="typeof firstValue === 'number'">
			<DebouncedInput
				type="number"
				:min="min"
				:max="max"
				:modelValue="(columnFilterValue as [number, number])?.[0] ?? ''"
				@update:modelValue="updateMinFilter"
				label="Minimum"
				:placeholder="`Min ${minMax?.[0] ? `(${min})` : ''}`"
			/>
			<DebouncedInput
				type="number"
				:min="min"
				:max="max"
				:modelValue="(columnFilterValue as [number, number])?.[1] ?? ''"
				@update:modelValue="updateMaxFilter"
				label="Maximum"
				:placeholder="`Max ${minMax?.[1] ? `(${max})` : ''}`"
			/>
		</DBStack>
		<template v-else>
			<datalist :id="column.id + 'list'">
				<option
					v-for="value in sortedUniqueValues.slice(0, 5000)"
					:key="value"
					:value="value"
				/>
			</datalist>
			<DebouncedInput
				type="text"
				:modelValue="(columnFilterValue as string) ?? ''"
				@update:modelValue="column.setFilterValue"
				:placeholder="`Search... (${uniqueValues.size})`"
				label="Search"
				:list="column.id + 'list'"
			/>
		</template>
	</DBPopover>
</template>

// storybooks/react-storybook/src/templates/table-kitchen-sink/components/Filter.tsx
import { DBButton, DBPopover, DBStack, DBTooltip } from '@components';
import type {
	Column,
	RowData,
	StockFeatures,
	Table
} from '@tanstack/react-table';
import { type FC, Fragment, useMemo } from 'react';
import DebouncedInput from './DebouncedInput';

type NumberInputProps = {
	columnFilterValue: [number, number];
	getFacetedMinMaxValues: () => [number, number] | undefined;
	setFilterValue: (updater: any) => void;
};

const NumberInput: FC<NumberInputProps> = ({
	columnFilterValue,
	getFacetedMinMaxValues,
	setFilterValue
}) => {
	const minOpt = getFacetedMinMaxValues()?.[0];
	const min = Number(minOpt ?? '');

	const maxOpt = getFacetedMinMaxValues()?.[1];
	const max = Number(maxOpt);

	return (
		<DBStack>
			<DebouncedInput
				type="number"
				min={min}
				max={max}
				value={columnFilterValue?.[0] ?? ''}
				onChange={(value) =>
					setFilterValue((old: [number, number]) => [value, old?.[1]])
				}
				label="Minimum"
				placeholder={`Min ${minOpt ? `(${min})` : ''}`}
			/>
			<DebouncedInput
				type="number"
				min={min}
				max={max}
				value={columnFilterValue?.[1] ?? ''}
				onChange={(value) =>
					setFilterValue((old: [number, number]) => [old?.[0], value])
				}
				label="Maximum"
				placeholder={`Max ${maxOpt ? `(${max})` : ''}`}
			/>
		</DBStack>
	);
};

type TextInputProps = {
	columnId: string;
	columnFilterValue: string;
	columnSize: number;
	setFilterValue: (updater: any) => void;
	sortedUniqueValues: any[];
};

const TextInput: FC<TextInputProps> = ({
	columnId,
	columnFilterValue,
	columnSize,
	setFilterValue,
	sortedUniqueValues
}) => {
	const dataListId = columnId + 'list';

	return (
		<Fragment>
			<datalist id={dataListId}>
				{sortedUniqueValues.slice(0, 5000).map((value: any) => (
					<option value={value} key={value} />
				))}
			</datalist>
			<DebouncedInput
				type="text"
				value={columnFilterValue ?? ''}
				onChange={(value) => setFilterValue(value)}
				placeholder={`Search... (${columnSize})`}
				label="Search"
				list={dataListId}
			/>
		</Fragment>
	);
};

type Props<T extends RowData> = {
	column: Column<StockFeatures, T, unknown>;
	table: Table<StockFeatures, T>;
};

export function Filter<T extends RowData>({ column, table }: Props<T>) {
	const firstValue = table
		.getPreFilteredRowModel()
		.flatRows[0]?.getValue(column.id);

	const columnFilterValue = column.getFilterValue();
	const uniqueValues = column.getFacetedUniqueValues();

	const sortedUniqueValues = useMemo(
		() =>
			typeof firstValue === 'number'
				? []
				: Array.from(uniqueValues.keys()).sort(),
		[uniqueValues]
	);

	return (
		<DBPopover
			placement="top"
			trigger={
				<DBButton size="small" variant="ghost" noText icon="funnel">
					Filter<DBTooltip placement="right">Filter</DBTooltip>
				</DBButton>
			}>
			{typeof firstValue === 'number' ? (
				<NumberInput
					columnFilterValue={columnFilterValue as [number, number]}
					getFacetedMinMaxValues={() =>
						column.getFacetedMinMaxValues()
					}
					setFilterValue={(updater) => column.setFilterValue(updater)}
				/>
			) : (
				<TextInput
					columnId={column.id}
					columnFilterValue={columnFilterValue as string}
					columnSize={uniqueValues.size}
					setFilterValue={(updater) => column.setFilterValue(updater)}
					sortedUniqueValues={sortedUniqueValues}
				/>
			)}
		</DBPopover>
	);
}

export default Filter;
