// showcases/vue-showcase/src/components/brand/Brand.vue
<script setup lang="ts">
import { DBBrand } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/brand.json";
import DefaultComponent from "../DefaultComponent.vue";
import imageUrl from "/assets/images/placeholder.jpg";
</script>

<template>
	<DefaultComponent title="DBBrand" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBBrand :hideLogo="exampleProps?.hideLogo">
				<img
					v-if="exampleProps?.customLogo"
					:src="imageUrl"
					alt="this is a fancy placeholder logo"
				/>
				{{ exampleName }}
			</DBBrand>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/brand/brand.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/brand.json';
import { DefaultComponent } from '../default.component';
import { DBBrand } from '../../../../../../output/angular/src/components/brand';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-button',
	templateUrl: './brand.component.html',
	imports: environment.webComponents ? [DefaultComponent] : [DefaultComponent, DBBrand],
	standalone: true,
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class BrandComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBBrand"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-control-panel-brand>
			@if (exampleProps?.customLogo) {
				<img
					src="./assets/images/placeholder.jpg"
					alt="this is a fancy placeholder logo"
				/>
			}
			{{ exampleName }}
		</db-control-panel-brand>
	</ng-template>
</app-default-component>
