// showcases/angular-showcase/src/app/components/navigation-item/navigation-item.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBNavigationItem, DBNavigationItemGroup } from '@components';
import defaultComponentVariants from '../../../../../shared/navigation-item.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-navigation-item',
	templateUrl: './navigation-item.component.html',
	imports: [
		environment.webComponents
			? [DefaultComponent]
			: [DefaultComponent, DBNavigationItem, DBNavigationItemGroup]
	],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : [],
	standalone: true
})
export class NavigationItemComponent {
	variants = defaultComponentVariants;

	showAlert = (exampleName: string) => {
		// eslint-disable-next-line no-alert
		alert(exampleName);
	};
}

<app-default-component
	title="DBNavigationItem"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<ul class="nav-item-list">
			<db-navigation-item
				[icon]="exampleProps?.icon"
				[showIcon]="exampleProps?.showIcon"
				[width]="exampleProps?.width"
				[disabled]="exampleProps?.disabled"
				[active]="exampleProps?.active"
				[wrap]="exampleProps?.wrap"
				(click)="showAlert(exampleName)"
			>
				<ng-container *dbNavigationContent>
					@if (exampleProps?.areaPopup) {
						{{ exampleName }}
					}
					@if (!exampleProps?.areaPopup) {
						<a href="#">{{ exampleName }}</a>
					}
				</ng-container>

				@if (exampleProps?.areaPopup) {
					<ng-container sub-navigation>
						<db-navigation-item
							[icon]="exampleProps?.icon"
							[showIcon]="exampleProps?.showIcon"
						>
							<ng-container *dbNavigationContent>
								<a href="#">Test1</a>
							</ng-container>
						</db-navigation-item>
						<db-navigation-item
							[icon]="exampleProps?.icon"
							[showIcon]="exampleProps?.showIcon"
						>
							<ng-container *dbNavigationContent>
								<a href="#">Test2</a>
							</ng-container>
						</db-navigation-item>
						<db-navigation-item
							[icon]="exampleProps?.icon"
							[showIcon]="exampleProps?.showIcon"
						>
							<ng-container *dbNavigationContent>
								<a href="#">Test3</a>
							</ng-container>
						</db-navigation-item>
					</ng-container>
				}
			</db-navigation-item>
		</ul>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/navigation-item/NavigationItem.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/navigation-item.json";
import { DBNavigationItem } from "../../../../../output/vue/src";

const log = (exampleName?: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent
		title="DBNavigationItem"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<ul class="nav-item-list">
				<DBNavigationItem
					:icon="exampleProps?.icon"
					:showIcon="exampleProps?.showIcon"
					:width="exampleProps?.width"
					:disabled="exampleProps?.disabled"
					:active="exampleProps?.active"
					:areaPopup="exampleProps?.areaPopup"
					:wrap="exampleProps?.wrap"
					@click="log(exampleName)"
				>
					<template v-if="exampleProps?.areaPopup" #sub-navigation>
						<ul>
							<DBNavigationItem
								><a href="#">Test1</a></DBNavigationItem
							>
							<DBNavigationItem
								><a href="#">Test2</a></DBNavigationItem
							>
							<DBNavigationItem
								><a href="#">Test3</a></DBNavigationItem
							>
						</ul>
					</template>
					<template v-if="exampleProps?.areaPopup">
						{{ exampleName }}
					</template>
					<a v-if="!exampleProps?.areaPopup" href="#">{{
						exampleName
					}}</a>
				</DBNavigationItem>
			</ul>
		</template>
	</DefaultComponent>
</template>
