// showcases/react-showcase/src/components/navigation-item/index.tsx
import { DBNavigationItem, DBButton } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/navigation-item.json';
import type { DBNavigationItemProps } from '../../../../../output/react/src/components/navigation-item/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getNavigationItem = ({
	children,
	icon,
	disabled,
	active,
	width,
	areaPopup,
	showIcon,
	wrap
}: DBNavigationItemProps & { areaPopup: boolean }) => (
	<ul className="nav-item-list">
		<DBNavigationItem
			icon={icon}
			disabled={disabled}
			active={active}
			width={width}
			onClick={() => {
				// eslint-disable-next-line no-alert
				alert(children.toString());
			}}
			showIcon={showIcon}
			wrap={wrap}
			subNavigation={
				areaPopup && (
					<>
						<DBNavigationItem
							icon={icon}
							showIcon={showIcon}
							subNavigation={
								<>
									<DBNavigationItem
										icon={icon}
										showIcon={showIcon}>
										<a href="#">Navigation-Item 2</a>
									</DBNavigationItem>
								</>
							}>
							Also a navigation item with longer label
						</DBNavigationItem>
						<DBNavigationItem icon={icon} showIcon={showIcon}>
							<a href="#">Navigation-Item 1</a>
						</DBNavigationItem>
					</>
				)
			}>
			{areaPopup ? children : <a href="#">{children}</a>}
		</DBNavigationItem>
	</ul>
);

const NavigationItemComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBNavigationItem"
			isSubComponent={props.isSubComponent}
			componentName={props.componentName}
			variants={getVariants(
				defaultComponentVariants,
				getNavigationItem,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default NavigationItemComponent;

// showcases/vue-showcase/src/components/navigation-item/NavigationItem.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/navigation-item.json";
import { DBNavigationItem } from "../../../../../output/vue/src";

const log = (exampleName?: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent title="DBNavigationItem" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
			<ul class="nav-item-list">
				<DBNavigationItem
					:icon="exampleProps?.icon"
					:showIcon="exampleProps?.showIcon"
					:width="exampleProps?.width"
					:disabled="exampleProps?.disabled"
					:active="exampleProps?.active"
					:areaPopup="exampleProps?.areaPopup"
					:wrap="exampleProps?.wrap"
					@click="log(exampleName)"
				>
					<template v-if="exampleProps?.areaPopup" #sub-navigation>
						<DBNavigationItem :icon="exampleProps?.icon" :showIcon="exampleProps?.showIcon">
							Also a navigation item with longer label
							<template v-slot:sub-navigation>
								<DBNavigationItem :icon="exampleProps?.icon" :showIcon="exampleProps?.showIcon">
									<a href="#">Navigation Item 2</a>
								</DBNavigationItem>
							</template>
						</DBNavigationItem>
						<DBNavigationItem :icon="exampleProps?.icon" :showIcon="exampleProps?.showIcon"><a href="#">Navigation Item 1</a></DBNavigationItem>
					</template>
					<template v-if="exampleProps?.areaPopup">
						{{ exampleName }}
					</template>
					<a v-if="!exampleProps?.areaPopup" href="#">{{ exampleName }}</a>
				</DBNavigationItem>
			</ul>
		</template>
	</DefaultComponent>
</template>
