// showcases/vue-showcase/src/page/Page.vue
<script setup lang="ts">
import {
	COLORS,
	DBBrand,
	DBButton,
	DBHeader,
	DBPage,
	DBSelect,
	DBSwitch,
	DENSITIES
} from "@components";
import { ref } from "vue";
import { useLayout } from "../composables/use-layout";
import PageNavigation from "./PageNavigation.vue";

const { density, color, shell, onChange } = useLayout();

const drawerOpen = ref(false);

const onToggle = (open: boolean) => {
	drawerOpen.value = open;
};

const onShellToggle = () => {
	onChange({} as Event, "shell");
};
</script>

<template>
	<DBPage variant="fixed" documentOverflow="auto" fadeIn>
		<template #header>
			<DBHeader
				:drawerOpen="drawerOpen"
				:onToggle="onToggle"
				drawerHeaderText="Showcase"
			>
				<template #brand>
					<DBBrand>Showcase</DBBrand>
				</template>
				<template #meta-navigation>
					<DBSelect
						label="Density"
						variant="floating"
						:value="density"
						@change="onChange($event, 'density')"
					>
						<option v-for="ton of DENSITIES" :value="ton">
							{{ ton }}
						</option>
					</DBSelect>
					<DBSelect
						label="Color"
						variant="floating"
						:value="color"
						@change="onChange($event, 'color')"
					>
						<option v-for="col of COLORS" :value="col">
							{{ col }}
						</option>
					</DBSelect>
				</template>
				<template #primary-action>
					<DBButton icon="magnifying_glass" variant="ghost" noText>
						Search
					</DBButton>
				</template>
				<template #secondary-action>
					<DBSwitch :checked="shell" @change="onShellToggle">
						Shell
					</DBSwitch>
				</template>
				<PageNavigation />
			</DBHeader>
		</template>
		<div :data-density="density" :class="`db-${color}`">
			<router-view></router-view>
		</div>
	</DBPage>
</template>

// showcases/angular-showcase/src/app/page/page.component.ts
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterOutlet } from '@angular/router';
import {
	COLOR_CONST,
	COLORS,
	DBBrand,
	DBButton,
	DBHeader,
	DBNavigation,
	DBPage,
	DBSelect,
	DBSwitch,
	DENSITIES,
	DENSITY,
	DENSITY_CONST,
	MetaNavigationDirective,
	NavigationDirective,
	SecondaryActionDirective,
	SEMANTIC
} from '@components';
import {
	getSortedNavigationItems,
	NAVIGATION_ITEMS,
	NavItem
} from '../utils/navigation-item';
import { PageNavItemComponent } from './page-nav-item.component';

@Component({
	selector: 'app-page',
	standalone: true,
	imports: [
		FormsModule,
		RouterOutlet,
		DBPage,
		DBHeader,
		DBBrand,
		DBNavigation,
		DBSelect,
		DBButton,
		DBSwitch,
		MetaNavigationDirective,
		NavigationDirective,
		SecondaryActionDirective,
		PageNavItemComponent
	],
	templateUrl: './page.component.html'
})
export class PageComponent implements OnInit {
	drawerOpen = false;
	navigationItems: NavItem[] = getSortedNavigationItems(NAVIGATION_ITEMS);

	densities = DENSITIES;
	colors = COLORS;

	density = DENSITY.REGULAR;
	color = SEMANTIC.NEUTRAL;
	shell = true;

	constructor(
		private readonly router: Router,
		private readonly route: ActivatedRoute
	) {}

	ngOnInit(): void {
		this.route.queryParams.subscribe((parameters) => {
			if (parameters[DENSITY_CONST]) {
				this.density = parameters[DENSITY_CONST];
			}

			if (parameters[COLOR_CONST]) {
				this.color = parameters[COLOR_CONST];
			}

			if (parameters['shell'] !== undefined) {
				this.shell = parameters['shell'] === 'true';
			}
		});
	}

	onToggle(open: boolean | void): void {
		this.drawerOpen = Boolean(open);
	}

	onChange(_event?: any): void {
		void this.updateQuery();
	}

	onShellToggle(): void {
		this.shell = !this.shell;
		void this.updateQuery();
	}

	private async updateQuery(): Promise<void> {
		await this.router.navigate([], {
			relativeTo: this.route,
			queryParams: {
				[DENSITY_CONST]: this.density,
				[COLOR_CONST]: this.color,
				shell: String(this.shell)
			},
			queryParamsHandling: 'merge'
		});
	}
}

<db-page variant="fixed" documentOverflow="auto" [fadeIn]="true">
	<db-header
		header
		[drawerOpen]="drawerOpen"
		(toggle)="onToggle($event)"
		drawerHeaderText="Showcase"
	>
		<db-brand brand>Showcase</db-brand>
		<db-navigation *dbNavigation aria-label="main-navigation">
			@for (item of navigationItems; track item.label) {
				<app-page-nav-item [navItem]="item"> </app-page-nav-item>
			}
		</db-navigation>
		<ng-container *dbMetaNavigation>
			<db-select
				(change)="onChange($event)"
				[(ngModel)]="density"
				label="Density"
				variant="floating"
			>
				@for (t of densities; track t) {
					<option>
						{{ t }}
					</option>
				}
			</db-select>
			<db-select
				(change)="onChange($event)"
				[(ngModel)]="color"
				label="Color"
				variant="floating"
			>
				@for (c of colors; track c) {
					<option>
						{{ c }}
					</option>
				}
			</db-select>
		</ng-container>
		<ng-container primary-action>
			<db-button [noText]="true" icon="magnifying_glass" variant="ghost"
				>Search</db-button
			>
		</ng-container>
		<ng-container *dbSecondaryAction>
			<db-switch [checked]="shell" (change)="onShellToggle()">
				Shell
			</db-switch>
			<db-button [noText]="true" icon="x_placeholder" variant="ghost">
				Notification
			</db-button>
			<db-button [noText]="true" icon="x_placeholder" variant="ghost">
				Help
			</db-button>
		</ng-container>
	</db-header>
	<div [attr.data-density]="density" [class]="'db-' + color">
		<router-outlet></router-outlet>
	</div>
</db-page>
