// showcases/angular-showcase/src/app/components/radio/radio.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBInfotext, DBRadio } from '@db-ux/ngx-core-components/src';
import defaultComponentVariants from '../../../../../shared/radio.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-radio',
	standalone: true,
	templateUrl: './radio.component.html',
	imports: [
		environment.webComponents
			? [DefaultComponent]
			: [DefaultComponent, DBRadio, DBInfotext]
	],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class RadioComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBRadio"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-radio
			[showRequiredAsterisk]="exampleProps?.showRequiredAsterisk"
			[label]="exampleProps?.label"
			[size]="exampleProps?.size"
			[name]="exampleProps?.name"
			[value]="exampleProps?.value"
			[checked]="exampleProps?.checked"
			[required]="exampleProps?.required"
			[disabled]="exampleProps?.disabled"
			[showLabel]="exampleProps?.showLabel"
			[validation]="exampleProps?.validation"
		>
			{{ exampleName }}
		</db-radio>
		@if (
			exampleProps?.showLabel !== undefined &&
			exampleProps?.showLabel !== null &&
			!exampleProps?.showLabel
		) {
			<db-infotext
				semantic="informational"
				size="small"
				[showIcon]="false"
			>
				{{ exampleName }}
			</db-infotext>
		}
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/radio/Radio.vue
<script setup lang="ts">
import { DBInfotext, DBRadio } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/radio.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBRadio" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBRadio
				:showRequiredAsterisk="exampleProps?.showRequiredAsterisk"
				:label="exampleProps?.label"
				:size="exampleProps?.size"
				:name="exampleProps?.name"
				:checked="exampleProps?.checked"
				:value="exampleProps?.value"
				:required="exampleProps?.required"
				:show-label="exampleProps?.showLabel"
				:disabled="exampleProps?.disabled"
				:validation="exampleProps?.validation"
			>
				{{ exampleName }}
			</DBRadio>
			<template
				v-if="
					exampleProps?.showLabel !== undefined &&
					!exampleProps?.showLabel
				"
			>
				<DBInfotext
					semantic="informational"
					size="small"
					:showIcon="false"
				>
					{{ exampleName }}
				</DBInfotext>
			</template>
		</template>
	</DefaultComponent>
</template>
