// showcases/angular-showcase/src/app/control-panel/actions-2/actions-2.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { DBButton, DBControlPanelActions2, DBSwitch } from '@components';

@Component({
	selector: 'app-actions-2',
	schemas: [],
	imports: [DBControlPanelActions2, DBButton, DBSwitch],
	templateUrl: './actions-2.component.html'
})
export class Actions2Component {
	shell = true;

	constructor(
		private readonly router: Router,
		private readonly route: ActivatedRoute
	) {
		this.route.queryParams.subscribe((parameters) => {
			if (parameters['shell'] !== undefined) {
				this.shell = parameters['shell'] === 'true';
			}
		});
	}

	onShellToggle(): void {
		this.shell = !this.shell;
		void this.router.navigate([], {
			relativeTo: this.route,
			queryParams: { shell: String(this.shell) },
			queryParamsHandling: 'merge'
		});
	}
}

<db-control-panel-actions-2>
	<db-switch (change)="onShellToggle()" [checked]="shell"> Shell </db-switch>
	<db-button [noText]="true" icon="x_placeholder" variant="ghost">
		Notification
	</db-button>
	<db-button [noText]="true" icon="x_placeholder" variant="ghost">
		Help
	</db-button>
</db-control-panel-actions-2>

// showcases/vue-showcase/src/control-panel/Actions2.vue
<script setup lang="ts">
import { DBButton, DBControlPanelActions2, DBSwitch } from "@components";
import { useLayout } from "../composables/use-layout";

const { shell, onChange } = useLayout();

const onShellToggle = () => {
	onChange({} as Event, "shell");
};
</script>

<template>
	<DBControlPanelActions2>
		<DBSwitch :checked="shell" @change="onShellToggle"> Shell </DBSwitch>
		<DBButton icon="x_placeholder" variant="ghost" noText>
			Notification
		</DBButton>
		<DBButton icon="x_placeholder" variant="ghost" noText> Help </DBButton>
	</DBControlPanelActions2>
</template>
