// showcases/react-showcase/src/control-panel/meta-navigation.tsx
import { DBControlPanelMeta, DBLink } from '@components';

export default function MetaNavigation() {
	return (
		<DBControlPanelMeta className="meta-workaround">
			<DBLink size="small" href="#">
				Link 1
			</DBLink>
			<DBLink size="small" href="#">
				Link 2
			</DBLink>
			<DBLink size="small" href="#">
				Link 3
			</DBLink>
		</DBControlPanelMeta>
	);
}

// showcases/vue-showcase/src/control-panel/MetaNavigation.vue
<script setup lang="ts">
import { DBControlPanelMeta, DBLink } from "@components";
</script>

<template>
	<DBControlPanelMeta class="meta-workaround">
		<DBLink size="small" href="#"> Link 1 </DBLink>
		<DBLink size="small" href="#"> Link 2 </DBLink>
		<DBLink size="small" href="#"> Link 3 </DBLink>
	</DBControlPanelMeta>
</template>
