// showcases/react-showcase/src/control-panel/primary-actions.tsx
import {
	DBButton,
	DBControlPanelPrimaryActions,
	DBDivider,
	DBDrawer,
	DBDrawerHeader,
	DBSelect,
	DBTooltip,
	DENSITIES,
	SEMANTICS
} from '@components';
import { Fragment, useState } from 'react';
import {
	type DefaultSettings,
	defaultSettingsMapping
} from '../../../settings';

export type PrimaryActionsProps = {
	color: string;
	density: string;
	settings: DefaultSettings;
	onDensityChange: (density: string) => void;
	onColorChange: (color: string) => void;
	onSettingsChange: (settings: DefaultSettings) => void;
};

const PrimaryActions = ({
	onSettingsChange,
	onDensityChange,
	onColorChange,
	color,
	density,
	settings
}: PrimaryActionsProps) => {
	const [open, setOpen] = useState<boolean>(false);

	return (
		<DBControlPanelPrimaryActions>
			<DBDrawer
				header={<DBDrawerHeader>Settings</DBDrawerHeader>}
				open={open}
				onClose={() => {
					setOpen(false);
				}}>
				<DBSelect
					label="Density"
					variant="floating"
					value={density}
					onChange={(event) => {
						onDensityChange(event?.target?.value);
					}}>
					{DENSITIES.map((ton) => (
						<option key={`density-option-${ton}`} value={ton}>
							{ton}
						</option>
					))}
				</DBSelect>
				<DBSelect
					label="Color"
					variant="floating"
					value={color}
					onChange={(event) => {
						onColorChange(event?.target?.value);
					}}>
					{SEMANTICS.map((col) => (
						<option key={`color-option-${col}`} value={col}>
							{col}
						</option>
					))}
				</DBSelect>
				<DBDivider />

				{Object.entries(defaultSettingsMapping).map(
					([key, value], index) => (
						<Fragment key={key}>
							<DBSelect
								label={key}
								variant="floating"
								value={settings[key]}
								onChange={(event) => {
									onSettingsChange({
										...settings,
										[key]: event.target.value
									});
								}}>
								{value.map((option) => (
									<option
										key={`${key}-option-${option}`}
										value={option}>
										{option}
									</option>
								))}
							</DBSelect>
							{(index === 1 || index === 3) && <DBDivider />}
						</Fragment>
					)
				)}
			</DBDrawer>
			<DBButton
				icon="gear_wheel"
				variant="ghost"
				noText
				onClick={() => {
					setOpen(true);
				}}>
				Settings
				<DBTooltip>Settings</DBTooltip>
			</DBButton>
		</DBControlPanelPrimaryActions>
	);
};

export default PrimaryActions;

// showcases/vue-showcase/src/control-panel/PrimaryActions.vue
<script setup lang="ts">
import {
	DBButton,
	DBControlPanelPrimaryActions,
	DBDivider,
	DBDrawer,
	DBDrawerHeader,
	DBSelect,
	DBTooltip,
	DENSITIES,
	SEMANTICS
} from "@components";
import { ref } from "vue";
import { defaultSettingsMapping } from "../../../settings";
import { useLayout } from "../composables/use-layout";

const { density, color, onChange, settings } = useLayout();

const sendSettings = (event: any, key: string) => {
	onChange(
		{
			...settings.value,
			[key]: event?.target?.value
		},
		"settings"
	);
};

const open = ref(false);
</script>

<template>
	<DBControlPanelPrimaryActions>
		<DBDrawer :open="open" @close="() => (open = false)"
			><template v-slot:header>
				<DBDrawerHeader>Settings</DBDrawerHeader></template
			>
			<DBSelect
				label="Density"
				variant="floating"
				:value="density"
				@change="onChange($event, 'density')"
			>
				<option v-for="ton of DENSITIES" :value="ton">
					{{ ton }}
				</option>
			</DBSelect>
			<DBSelect
				label="Color"
				variant="floating"
				:value="color"
				@change="onChange($event, 'color')"
			>
				<option v-for="col of SEMANTICS" :value="col">
					{{ col }}
				</option>
			</DBSelect>
			<DBDivider />
			<template
				v-for="([key, value], index) of Object.entries(
					defaultSettingsMapping
				)"
			>
				<DBSelect
					:label="key"
					variant="floating"
					:value="settings[key]"
					@change="sendSettings($event, key)"
				>
					<option v-for="col of value" :value="col">
						{{ col }}
					</option>
				</DBSelect>
				<template v-if="index === 1 || index === 3"
					><DBDivider
				/></template>
			</template>
		</DBDrawer>
		<DBButton
			icon="gear_wheel"
			variant="ghost"
			no-text
			@click="() => (open = true)"
		>
			Settings
			<DBTooltip>Settings</DBTooltip>
		</DBButton>
	</DBControlPanelPrimaryActions>
</template>
