// showcases/vue-showcase/src/components/tooltip/Tooltip.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tooltip.json";
import { DBButton, DBTooltip } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTooltip" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBButton>
				{{ exampleName }}
				<DBTooltip
					:width="exampleProps.width"
					:emphasis="exampleProps.emphasis"
					:placement="exampleProps.placement"
					:behaviour="exampleProps.behaviour"
					:delay="exampleProps.delay"
					:variant="exampleProps.variant"
				>
					{{ exampleProps.content }}
				</DBTooltip>
			</DBButton>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/tooltip/index.tsx
import { DBTooltip, DBButton } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/tooltip.json';
import type { DBTooltipProps } from '../../../../../output/react/src/components/tooltip/model';
import { getVariants } from '../data';

const getTooltip = ({
	children,
	width,
	emphasis,
	placement,
	delay,
	content,
	behaviour,
	variant
}: DBTooltipProps & { content: string }) => (
	<DBButton>
		{children}
		<DBTooltip
			width={width}
			emphasis={emphasis}
			placement={placement}
			behaviour={behaviour}
			delay={delay}
			variant={variant}>
			{content}
		</DBTooltip>
	</DBButton>
);

const TooltipComponent = () => {
	return (
		<DefaultComponent
			title="DBTooltip"
			variants={getVariants(
				defaultComponentVariants,
				getTooltip
			)}></DefaultComponent>
	);
};

export default TooltipComponent;
