// showcases/react-showcase/src/components/home/index.tsx
import {
	DBTabItem,
	DBTabList,
	DBTabPanel,
	DBTabs
} from '../../../../../output/react/src';
import FormComponent from '../form';
import FormCheckboxes from '../form/checkbox';
import FormCustomSelects from '../form/custom-select';
import FormInputs from '../form/input';
import FormRadios from '../form/radio';
import FormSelects from '../form/select';
import FormTextareas from '../form/textarea';

const Home = () => {
	return (
		<DBTabs data-testid="tabs">
			<DBTabList>
				<DBTabItem>All</DBTabItem>
				<DBTabItem data-testid="tab-inputs">Input</DBTabItem>
				<DBTabItem data-testid="tab-textareas">Textarea</DBTabItem>
				<DBTabItem data-testid="tab-selects">Select</DBTabItem>
				<DBTabItem data-testid="tab-checkboxes">Checkbox</DBTabItem>
				<DBTabItem data-testid="tab-radios">Radios</DBTabItem>
				<DBTabItem data-testid="tab-custom-selects">
					Custom Selects
				</DBTabItem>
			</DBTabList>
			<DBTabPanel>
				<FormComponent />
			</DBTabPanel>
			<DBTabPanel>
				<FormInputs />
			</DBTabPanel>
			<DBTabPanel>
				<FormTextareas />
			</DBTabPanel>
			<DBTabPanel>
				<FormSelects />
			</DBTabPanel>
			<DBTabPanel>
				<FormCheckboxes />
			</DBTabPanel>
			<DBTabPanel>
				<FormRadios />
			</DBTabPanel>
			<DBTabPanel>
				<FormCustomSelects />
			</DBTabPanel>
		</DBTabs>
	);
};

export default Home;

// showcases/vue-showcase/src/components/home/Home.vue
<script setup lang="ts">
import {
	DBTabItem,
	DBTabList,
	DBTabPanel,
	DBTabs
} from "../../../../../output/vue/src";
import Form from "../form/Form.vue";
import Textareas from "../form/Textareas.vue";
import Selects from "../form/Selects.vue";
import Checkboxes from "../form/Checkboxes.vue";
import Inputs from "../form/Inputs.vue";
import Radios from "../form/Radios.vue";
import CustomSelects from "../form/Custom-Selects.vue";
</script>

<template>
	<DBTabs data-testid="tabs">
		<DBTabList>
			<DBTabItem>All</DBTabItem>
			<DBTabItem data-testid="tab-inputs">Input</DBTabItem>
			<DBTabItem data-testid="tab-textareas">Textarea</DBTabItem>
			<DBTabItem data-testid="tab-selects">Select</DBTabItem>
			<DBTabItem data-testid="tab-checkboxes">Checkbox</DBTabItem>
			<DBTabItem data-testid="tab-radios">Radios</DBTabItem>
			<DBTabItem data-testid="tab-custom-selects"
				>Custom Selects</DBTabItem
			>
		</DBTabList>
		<DBTabPanel>
			<Form />
		</DBTabPanel>
		<DBTabPanel>
			<Inputs />
		</DBTabPanel>
		<DBTabPanel>
			<Textareas />
		</DBTabPanel>
		<DBTabPanel>
			<Selects />
		</DBTabPanel>
		<DBTabPanel>
			<Checkboxes />
		</DBTabPanel>
		<DBTabPanel>
			<Radios />
		</DBTabPanel>
		<DBTabPanel>
			<CustomSelects />
		</DBTabPanel>
	</DBTabs>
</template>
