// showcases/angular-showcase/src/app/components/home/home.component.ts
import {Component} from '@angular/core';
import {DBTabItem, DBTabList, DBTabPanel, DBTabs} from '@components';
import {CheckboxesComponent} from '../form/checkboxes/checkboxes.component';
import {CustomSelectsComponent} from '../form/custom-selects/custom-selects.component';
import {FormComponent} from '../form/form.component';
import {InputsComponent} from '../form/inputs/inputs.component';
import {RadiosComponent} from '../form/radios/radios.component';
import {SelectsComponent} from '../form/selects/selects.component';
import {SwitchesComponent} from '../form/switches/switches.component';
import {TextareasComponent} from '../form/textareas/textareas.component';

@Component({
	selector: 'app-home',
	templateUrl: './home.component.html',
	standalone: true,
	imports: [
		InputsComponent,
		FormComponent,
		TextareasComponent,
		SelectsComponent,
		CheckboxesComponent,
		RadiosComponent,
		CustomSelectsComponent,
		SwitchesComponent,
		DBTabs,
		DBTabItem,
		DBTabList,
		DBTabPanel,
	],
})
export class HomeComponent {}

<db-tabs data-testid="tabs">
	<db-tab-list>
		<db-tab-item>All</db-tab-item>
		<db-tab-item data-testid="tab-inputs">Input</db-tab-item>
		<db-tab-item data-testid="tab-textareas">Textarea</db-tab-item>
		<db-tab-item data-testid="tab-selects">Select</db-tab-item>
		<db-tab-item data-testid="tab-checkboxes">Checkbox</db-tab-item>
		<db-tab-item data-testid="tab-radios">Radios</db-tab-item>
		<db-tab-item data-testid="tab-custom-selects">
			Custom Selects
		</db-tab-item>
		<db-tab-item data-testid="tab-switches">Switches</db-tab-item>
	</db-tab-list>
	<db-tab-panel>
		<app-form />
	</db-tab-panel>
	<db-tab-panel>
		<app-inputs />
	</db-tab-panel>
	<db-tab-panel>
		<app-textareas />
	</db-tab-panel>
	<db-tab-panel>
		<app-selects />
	</db-tab-panel>
	<db-tab-panel>
		<app-checkboxes />
	</db-tab-panel>
	<db-tab-panel>
		<app-radios />
	</db-tab-panel>
	<db-tab-panel>
		<app-custom-selects />
	</db-tab-panel>
	<db-tab-panel>
		<app-switches />
	</db-tab-panel>
</db-tabs>

// showcases/vue-showcase/src/components/home/Home.vue
<script setup lang="ts">
import {
	DBTabItem,
	DBTabList,
	DBTabPanel,
	DBTabs
} from "../../../../../packages/v-core-components/src";
import Checkboxes from "../form/Checkboxes.vue";
import CustomSelects from "../form/Custom-Selects.vue";
import Form from "../form/Form.vue";
import Inputs from "../form/Inputs.vue";
import Radios from "../form/Radios.vue";
import Selects from "../form/Selects.vue";
import Switches from "../form/Switches.vue";
import Textareas from "../form/Textareas.vue";
</script>

<template>
	<DBTabs data-testid="tabs">
		<DBTabList>
			<DBTabItem>All</DBTabItem>
			<DBTabItem data-testid="tab-inputs">Input</DBTabItem>
			<DBTabItem data-testid="tab-textareas">Textarea</DBTabItem>
			<DBTabItem data-testid="tab-selects">Select</DBTabItem>
			<DBTabItem data-testid="tab-checkboxes">Checkbox</DBTabItem>
			<DBTabItem data-testid="tab-radios">Radios</DBTabItem>
			<DBTabItem data-testid="tab-custom-selects"
				>Custom Selects</DBTabItem
			>
			<DBTabItem data-testid="tab-switches">Switches</DBTabItem>
		</DBTabList>
		<DBTabPanel>
			<Form />
		</DBTabPanel>
		<DBTabPanel>
			<Inputs />
		</DBTabPanel>
		<DBTabPanel>
			<Textareas />
		</DBTabPanel>
		<DBTabPanel>
			<Selects />
		</DBTabPanel>
		<DBTabPanel>
			<Checkboxes />
		</DBTabPanel>
		<DBTabPanel>
			<Radios />
		</DBTabPanel>
		<DBTabPanel>
			<CustomSelects />
		</DBTabPanel>
		<DBTabPanel>
			<Switches />
		</DBTabPanel>
	</DBTabs>
</template>
