// showcases/angular-showcase/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterOutlet } from '@angular/router';
import {
	COLOR_CONST,
	DBControlPanelBrand,
	DBControlPanelDesktop,
	DBControlPanelMobile,
	DBControlPanelNavigation,
	DBShell,
	DBShellContent,
	DBShellSubNavigation,
	DENSITY,
	DENSITY_CONST,
	SEMANTIC
} from '@components';
import { defaultSettings, DefaultSettings } from '../../../settings';
import { MetaNavigationComponent } from './control-panel/meta-navigation/meta-navigation.component';
import { PrimaryActionsComponent } from './control-panel/primary-actions/primary-actions.component';
import { SecondaryActionsComponent } from './control-panel/secondary-actions/secondary-actions.component';
import { NavItemComponent } from './nav-item/nav-item.component';
import {
	getSortedNavigationItems,
	NAVIGATION_ITEMS,
	NavItem
} from './utils/navigation-item';

@Component({
	selector: 'app-root',
	standalone: true,
	schemas: [],
	imports: [
		FormsModule,
		RouterOutlet,
		MetaNavigationComponent,
		PrimaryActionsComponent,
		SecondaryActionsComponent,
		NavItemComponent,
		DBShell,
		DBShellContent,
		DBControlPanelBrand,
		DBControlPanelDesktop,
		DBControlPanelMobile,
		DBControlPanelNavigation,
		DBShellSubNavigation
	],
	templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
	drawerOpen = false;
	navigationItems: NavItem[] = getSortedNavigationItems(NAVIGATION_ITEMS);

	density = DENSITY.REGULAR;
	color = SEMANTIC.NEUTRAL;
	settings: DefaultSettings = defaultSettings;

	page?: string;
	fullscreen = false;

	constructor(private readonly route: ActivatedRoute) {}

	ngOnInit(): void {
		this.route.queryParams.subscribe((parameters) => {
			if (parameters[DENSITY_CONST]) {
				this.density = parameters[DENSITY_CONST];
			}

			if (parameters[COLOR_CONST]) {
				this.color = parameters[COLOR_CONST];
			}

			if (parameters['page']) {
				this.page = parameters['page'];
			}

			if (parameters['fullscreen']) {
				this.fullscreen = parameters['fullscreen'];
			}

			if (
				parameters['settings'] &&
				JSON.stringify(this.settings) !== parameters['settings']
			) {
				this.settings = JSON.parse(parameters['settings']);
			}
		});
	}

	getChangeableClasses = () =>
		`db-density-${this.density} db-color-${this.color}`;

	getFullscreenClasses = () =>
		`fullscreen-container ${this.getChangeableClasses()}`;
}

@if (page) {
	<div [class]="getChangeableClasses()">
		<router-outlet></router-outlet>
	</div>
}
@if (!page) {
	<db-shell
		[fadeIn]="true"
		[controlPanelDesktopPosition]="settings.controlPanelDesktopPosition"
		[controlPanelMobilePosition]="settings.controlPanelMobilePosition"
		[subNavigationDesktopPosition]="settings.subNavigationDesktopPosition"
		[subNavigationMobilePosition]="settings.subNavigationMobilePosition"
	>
		@if (settings.subNavigation === "true") {
			<db-navigation
				sub-navigation
				slot="subNavigation"
				aria-label="sub-navigation"
				[variant]="settings.subNavigationVariant"
			>
				@for (item of navigationItems; track item.label) {
					<app-nav-item [navItem]="item"> </app-nav-item>
				}
			</db-navigation>
		}
		<db-control-panel-desktop
			control-panel-desktop
			slot="controlPanelDesktop"
		>
			<db-control-panel-brand brand slot="brand">
				Showcase
			</db-control-panel-brand>
			<app-meta-navigation
				meta-navigation
				slot="metaNavigation"
				[density]="density"
				[color]="color"
				[settings]="settings"
			/>
			<app-primary-actions
				primary-actions
				slot="primaryActions"
			></app-primary-actions>
			<app-secondary-actions
				secondary-actions
				slot="secondaryActions"
			></app-secondary-actions>
			<db-navigation
				aria-label="desktop-navigation"
				[variant]="settings.navigationDesktopVariant"
			>
				@for (item of navigationItems; track item.label) {
					<app-nav-item [navItem]="item"> </app-nav-item>
				}
			</db-navigation>
		</db-control-panel-desktop>
		<db-control-panel-mobile control-panel-mobile slot="controlPanelMobile">
			<db-control-panel-brand brand slot="brand">
				Showcase
			</db-control-panel-brand>
			<app-meta-navigation
				meta-navigation
				slot="metaNavigation"
				[density]="density"
				[color]="color"
				[settings]="settings"
			/>
			<app-primary-actions
				primary-actions
				slot="primaryActions"
			></app-primary-actions>
			<app-secondary-actions
				secondary-actions
				slot="secondaryActions"
			></app-secondary-actions>
			<db-navigation
				aria-label="mobile-navigation"
				[variant]="settings.navigationMobileVariant"
			>
				@for (item of navigationItems; track item.label) {
					<app-nav-item [navItem]="item"> </app-nav-item>
				}
			</db-navigation>
		</db-control-panel-mobile>
		<div [class]="getChangeableClasses()">
			<router-outlet></router-outlet>
		</div>
	</db-shell>
}

// showcases/vue-showcase/src/App.vue
<script setup lang="ts">
import {
	DBControlPanelBrand,
	DBControlPanelDesktop,
	DBControlPanelMobile,
	DBControlPanelNavigation,
	DBShell,
	DBShellContent,
	DBShellSubNavigation
} from "@components";
import NavItemComponent from "./NavItemComponent.vue";

import { useLayout } from "./composables/use-layout";
import MetaNavigation from "./control-panel/MetaNavigation.vue";
import PrimaryActions from "./control-panel/PrimaryActions.vue";
import SecondaryActions from "./control-panel/SecondaryActions.vue";
import Page from "./page/Page.vue";

const { page, fullscreen, classNames, sortedNavigation, settings, shell } =
	useLayout();
</script>

<template>
	<div
		v-if="page || fullscreen"
		:class="`fullscreen-container ${classNames}`"
	>
		<router-view></router-view>
	</div>
	<Page v-else-if="!shell" />
	<DBShell
		v-if="!page && !fullscreen && shell"
		fadeIn
		:controlPanelDesktopPosition="settings.controlPanelDesktopPosition"
		:controlPanelMobilePosition="settings.controlPanelMobilePosition"
		:subNavigationDesktopPosition="settings.subNavigationDesktopPosition"
		:subNavigationMobilePosition="settings.subNavigationMobilePosition"
		:show-sub-navigation="settings.subNavigation === 'true'"
	>
		<DBShellSubNavigation>
			<DBControlPanelNavigation
				:variant="settings.subNavigationVariant"
				aria-label="sub navigation"
			>
				<template v-for="item of sortedNavigation">
					<NavItemComponent :navItem="item"></NavItemComponent>
				</template>
			</DBControlPanelNavigation>
		</DBShellSubNavigation>
		<DBControlPanelDesktop>
			<template v-slot:brand>
				<DBControlPanelBrand>Showcase</DBControlPanelBrand>
			</template>
			<DBControlPanelNavigation
				:variant="settings.navigationDesktopVariant"
				aria-label="main navigation desktop"
			>
				<template v-for="item of sortedNavigation">
					<NavItemComponent :navItem="item"></NavItemComponent>
				</template>
			</DBControlPanelNavigation>
			<template v-slot:primary-actions>
				<PrimaryActions />
			</template>
			<template v-slot:secondary-actions>
				<SecondaryActions />
			</template>
			<template v-slot:meta>
				<MetaNavigation />
			</template>
		</DBControlPanelDesktop>
		<DBControlPanelMobile drawerHeaderText="Showcase">
			<template v-slot:brand>
				<DBControlPanelBrand>Showcase</DBControlPanelBrand>
			</template>
			<DBControlPanelNavigation
				:variant="settings.navigationMobileVariant"
				aria-label="main navigation mobile"
			>
				<template v-for="item of sortedNavigation">
					<NavItemComponent :navItem="item"></NavItemComponent>
				</template>
			</DBControlPanelNavigation>
			<template v-slot:primary-actions>
				<PrimaryActions />
			</template>
			<template v-slot:secondary-actions>
				<SecondaryActions />
			</template>
			<template v-slot:meta>
				<MetaNavigation />
			</template>
		</DBControlPanelMobile>
		<DBShellContent :class="classNames">
			<router-view></router-view>
		</DBShellContent>
	</DBShell>
</template>
