// showcases/patternhub/components/navigation/nav-item.tsx
import { useRouter } from 'next/router';
import Link from 'next/link';
import { DBNavigationItem } from '../../../../output/react/src';
import type { NavigationItem } from '../../data/routes';

const NavItem = ({ navItem }: { navItem: NavigationItem }) => {
	const router = useRouter();

	const isActive =
		navItem.path === '/'
			? router.pathname === '/'
			: router.pathname.includes(navItem.path ?? '');

	return (
		<DBNavigationItem
			active={isActive}
			backButtonText={`Back to ${navItem.label}`}
			slotSubNavigation={
				navItem.subNavigation && (
					<>
						{navItem?.subNavigation.map(
							(subItem: NavigationItem) => (
								<>
									{subItem.subNavigation ? (
										<NavItem navItem={subItem}></NavItem>
									) : (
										<Link
											key={`router-path-${subItem.path}`}
											href={subItem.path ?? ''}>
											<NavItem
												navItem={subItem}></NavItem>
										</Link>
									)}
								</>
							)
						)}
					</>
				)
			}>
			{navItem.label}
		</DBNavigationItem>
	);
};

export default NavItem;

// showcases/vue-showcase/src/NavItemComponent.vue
<script setup lang="ts">
import {
	DBNavigationItem,
	DBSubNavigation
} from "../../../output/vue/vue3/src";
import { NavItem } from "./utils/navigation-items";
import { useRoute } from "vue-router";

defineProps<{
	navItem?: NavItem;
}>();

const route = useRoute();

const isActive = (navItem: NavItem) =>
	navItem.path !== "/"
		? route.path.includes(navItem.path)
		: route.path === "/";
</script>

<template>
	<DBNavigationItem
		:backButtonText="`Back to ${navItem.label}`"
		:active="isActive(navItem)"
	>
		<template v-if="navItem.subNavigation" v-slot:subnavigation>
			<template v-for="item of navItem.subNavigation">
				<NavItemComponent :navItem="item"></NavItemComponent>
			</template>
		</template>
		<router-link v-if="navItem.component" :to="navItem.path">
			{{ navItem.label }}
		</router-link>
		<template v-if="!navItem.component">{{ navItem.label }}</template>
	</DBNavigationItem>
</template>
