// showcases/react-showcase/src/nav-item.tsx
import { Link, useLocation } from 'react-router-dom';
import { DBNavigationItem } from '../../../output/react/src';
import type { NavigationItem } from './utils/navigation-item';

const NavItem = ({ navItem }: { navItem: NavigationItem }) => {
	const location = useLocation();

	const isActive =
		navItem.path === ''
			? location.pathname === '/'
			: location.pathname.includes(navItem.path);

	return (
		<DBNavigationItem
			active={isActive}
			slotSubNavigation={
				navItem.subNavigation && (
					<>
						{navItem.subNavigation
							.map((subItem) => ({
								...subItem,
								path: `${navItem.path}/${subItem.path}`
							}))
							.map((subItem) =>
								subItem.component ? (
									<Link
										key={`router-path-${subItem.path}`}
										to={subItem.path}>
										<NavItem navItem={subItem}></NavItem>
									</Link>
								) : (
									<NavItem
										key={`router-path-${subItem.path}`}
										navItem={subItem}></NavItem>
								)
							)}
					</>
				)
			}>
			{navItem.label}
		</DBNavigationItem>
	);
};

export default NavItem;

// showcases/vue-showcase/src/NavItemComponent.vue
<script setup lang="ts">
import {
	DBNavigationItem,
	DBSubNavigation
} from "../../../output/vue/vue3/src";
import { NavItem } from "./utils/navigation-items";
import { useRoute } from "vue-router";

defineProps<{
	navItem?: NavItem;
}>();

const route = useRoute();

const isActive = (navItem: NavItem) =>
	navItem.path !== "/"
		? route.path.includes(navItem.path)
		: route.path === "/";
</script>

<template>
	<DBNavigationItem
		:backButtonText="`Back to ${navItem.label}`"
		:active="isActive(navItem)"
	>
		<template v-if="navItem.subNavigation" v-slot:subnavigation>
			<template v-for="item of navItem.subNavigation">
				<NavItemComponent :navItem="item"></NavItemComponent>
			</template>
		</template>
		<router-link v-if="navItem.component" :to="navItem.path">
			{{ navItem.label }}
		</router-link>
		<template v-if="!navItem.component">{{ navItem.label }}</template>
	</DBNavigationItem>
</template>
