// showcases/react-showcase/src/components/main-navigation/index.tsx
import {
	DBMainNavigation,
	DBNavigationItem
} from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/main-navigation.json';
import type { DBMainNavigationProps } from '../../../../../output/react/src/components/main-navigation/model';
import { getVariants } from '../data';

const getMainNavigation = ({ children }: DBMainNavigationProps) => (
	<div>
		<h6>{children}:</h6>
		<DBMainNavigation>
			<DBNavigationItem
				active
				subNavigation={
					<>
						<DBNavigationItem
							active
							subNavigation={
								<>
									<DBNavigationItem active>
										<a href="#">Sub-Sub-Navi-Item 1</a>
									</DBNavigationItem>
									<DBNavigationItem>
										<a href="#">Sub-Sub-Navi-Item 2</a>
									</DBNavigationItem>
								</>
							}>
							Sub-Navi-Item 1
						</DBNavigationItem>
						<DBNavigationItem>
							<a href="#">Sub-Navi-Item 2</a>
						</DBNavigationItem>
					</>
				}>
				Navi-Item 1
			</DBNavigationItem>
			<DBNavigationItem icon="user">
				<a href="#">Navi-Item 2</a>
			</DBNavigationItem>
			<DBNavigationItem disabled>
				<a href="#">Navi-Item 3</a>
			</DBNavigationItem>
		</DBMainNavigation>
	</div>
);

const MainNavigationComponent = () => {
	return (
		<DefaultComponent
			title="DBMainNavigation"
			variants={getVariants(
				defaultComponentVariants,
				getMainNavigation
			)}></DefaultComponent>
	);
};

export default MainNavigationComponent;

// showcases/vue-showcase/src/components/main-navigation/MainNavigation.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/main-navigation.json";
import {
	DBMainNavigation,
	DBNavigationItem
} from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent
		title="DBMainNavigation"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<div>
				<h6>{{ exampleName }}</h6>
				<DBMainNavigation>
					<DBNavigationItem :active="true">
						Navi-Item 1
						<template v-slot:subnavigation>
							<DBNavigationItem :active="true">
								Sub-Navi-Item 1

								<template v-slot:subnavigation>
									<DBNavigationItem :active="true">
										<a href="#">Sub-Sub-Navi-Item 1</a>
									</DBNavigationItem>
									<DBNavigationItem>
										<a href="#">Sub-Sub-Navi-Item 2</a>
									</DBNavigationItem>
								</template>
							</DBNavigationItem>
							<DBNavigationItem>
								<a href="#">Sub-Navi-Item 2</a>
							</DBNavigationItem>
						</template>
					</DBNavigationItem>
					<DBNavigationItem icon="user">
						<a href="#">Navi-Item 2</a>
					</DBNavigationItem>
					<DBNavigationItem :disabled="true">
						<a href="#">Navi-Item 3</a>
					</DBNavigationItem>
				</DBMainNavigation>
			</div>
		</template>
	</DefaultComponent>
</template>
