// showcases/react-showcase/src/components/textarea/index.tsx
import { DBTextarea } from '@components';
import type { DBTextareaProps } from '@components/src/components/textarea/model';
import { useState } from 'react';
import defaultComponentVariants from '../../../../shared/textarea.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getTextarea = ({
	cols,
	disabled,
	message,
	label,
	placeholder,
	rows,
	value,
	readOnly,
	required,
	children,
	variant,
	showLabel,
	showMessage,
	validMessage,
	validation,
	invalidMessage,
	fieldSizing,
	showResizer,
	showRequiredAsterisk
}: DBTextareaProps) => {
	const [dynamicValue, setDynamicValue] = useState<string>(value);
	return (
		<DBTextarea
			cols={cols}
			showRequiredAsterisk={showRequiredAsterisk}
			disabled={disabled}
			showLabel={showLabel}
			message={message}
			label={label}
			variant={variant}
			readOnly={readOnly}
			onChange={(event) => {
				setDynamicValue(event.target.value);
			}}
			required={required}
			placeholder={placeholder ?? children}
			rows={rows}
			value={dynamicValue}
			showMessage={showMessage}
			invalidMessage={invalidMessage}
			validMessage={validMessage}
			validation={validation}
			showResizer={showResizer}
			fieldSizing={fieldSizing}
		/>
	);
};

const TextareaComponent = (props: BaseComponentProps) => {
	return (
		<>
			<DefaultComponent
				title="DBTextarea"
				variants={getVariants(
					defaultComponentVariants,
					getTextarea,
					props.slotCode
				)}></DefaultComponent>
		</>
	);
};

export default TextareaComponent;

// showcases/vue-showcase/src/components/textarea/Textarea.vue
<script setup lang="ts">
import { DBTextarea } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/textarea.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBTextarea" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTextarea
				:showRequiredAsterisk="exampleProps?.showRequiredAsterisk"
				:cols="exampleProps?.cols"
				:disabled="exampleProps?.disabled"
				:show-label="exampleProps?.showLabel"
				:message="exampleProps?.message"
				:required="exampleProps?.required"
				:readOnly="exampleProps?.readOnly"
				:label="exampleProps?.label"
				:placeholder="exampleProps?.placeholder || exampleName"
				:rows="exampleProps?.rows"
				:value="exampleProps?.value"
				:variant="exampleProps?.variant"
				:showMessage="exampleProps?.showMessage"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:validation="exampleProps?.validation"
				:showResizer="exampleProps?.showResizer"
				:fieldSizing="exampleProps?.fieldSizing"
			></DBTextarea>
		</template>
	</DefaultComponent>
</template>
