// showcases/angular-showcase/src/app/components/checkbox/checkbox.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBCheckbox, DBInfotext } from '@db-ux/ngx-core-components/src';
import defaultComponentVariants from '../../../../../shared/checkbox.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-checkbox',
	templateUrl: './checkbox.component.html',
	standalone: true,
	imports: [
		environment.webComponents
			? [DefaultComponent]
			: [DefaultComponent, DBCheckbox, DBInfotext]
	],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class CheckboxComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBCheckbox"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-checkbox
			[label]="exampleProps?.label"
			[disabled]="exampleProps?.disabled"
			[checked]="exampleProps?.checked"
			[value]="exampleProps?.value"
			[required]="exampleProps?.required"
			[indeterminate]="exampleProps?.indeterminate"
			[showLabel]="exampleProps?.showLabel"
			[validation]="exampleProps?.validation"
			[invalidMessage]="exampleProps?.invalidMessage"
			[validMessage]="exampleProps?.validMessage"
			[showRequiredAsterisk]="exampleProps?.showRequiredAsterisk"
			[size]="exampleProps?.size"
			>{{ exampleName }}</db-checkbox
		>
		@if (
			exampleProps?.showLabel !== undefined &&
			exampleProps?.showLabel !== null &&
			!exampleProps?.showLabel
		) {
			<db-infotext
				semantic="informational"
				size="small"
				[showIcon]="false"
			>
				{{ exampleName }}
			</db-infotext>
		}
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/checkbox/Checkbox.vue
<script setup lang="ts">
import { DBCheckbox, DBInfotext } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/checkbox.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBCheckbox" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBCheckbox
				:showRequiredAsterisk="exampleProps?.showRequiredAsterisk"
				:label="exampleProps?.label"
				:variant="exampleProps?.variant"
				:show-label="exampleProps?.showLabel"
				:options="exampleProps?.options"
				:checked="exampleProps?.checked"
				:disabled="exampleProps?.disabled"
				:value="exampleProps?.value"
				:required="exampleProps?.required"
				:validation="exampleProps?.validation"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:indeterminate="exampleProps?.indeterminate"
				:size="exampleProps?.size"
				>{{ exampleName }}</DBCheckbox
			>

			<template
				v-if="
					exampleProps?.showLabel !== undefined &&
					!exampleProps?.showLabel
				"
			>
				<DBInfotext
					semantic="informational"
					size="small"
					:showIcon="false"
				>
					{{ exampleName }}
				</DBInfotext>
			</template>
		</template>
	</DefaultComponent>
</template>
