// showcases/vue-showcase/src/components/tab-item/TabItem.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tab-item.json";
import { DBTabItem } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTabItem" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTabItem
				:active="exampleProps.active"
				:noText="exampleProps.noText"
				:icon="exampleProps.icon"
				:iconAfter="exampleProps.iconAfter"
				:disabled="exampleProps.disabled"
			>
				{{ exampleName }}
			</DBTabItem>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/tab-item/index.tsx
import { DBTabItem } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/tab-item.json';
import type { DBTabItemProps } from '../../../../../output/react/src/components/tab-item/model';
import { getVariants } from '../data';

const getTab = ({
	children,
	active,
	noText,
	icon,
	iconAfter,
	disabled
}: DBTabItemProps) => (
	<DBTabItem
		active={active}
		noText={noText}
		icon={icon}
		iconAfter={iconAfter}
		disabled={disabled}>
		{children}
	</DBTabItem>
);

const TabItemComponent = () => {
	return (
		<DefaultComponent
			title="DBTabItem"
			variants={getVariants(
				defaultComponentVariants,
				getTab
			)}></DefaultComponent>
	);
};

export default TabItemComponent;
