// showcases/angular-showcase/src/app/components/navigation/navigation.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
	DBInfotext,
	DBNavigation,
	DBNavigationItem,
	DBNavigationItemGroup
} from '@components';
import defaultComponentVariants from '../../../../../shared/navigation.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-navigation',
	templateUrl: './navigation.component.html',
	imports: [
		environment.webComponents
			? [DefaultComponent]
			: [
					DefaultComponent,
					DBNavigation,
					DBNavigationItem,
					DBNavigationItemGroup,
					DBInfotext
				]
	],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : [],
	standalone: true
})
export class NavigationComponent {
	variants = defaultComponentVariants;

	getId = (name: string): string =>
		`${name.replaceAll(/\W/g, '_').toLowerCase()}`;
}

<app-default-component
	title="DBNavigation"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<div>
			<db-infotext
				[id]="getId(exampleName)"
				size="small"
				semantic="informational"
				icon="none"
			>
				{{ exampleName }}
			</db-infotext>
			<db-navigation [labelledBy]="getId(exampleName)">
				<db-navigation-item [active]="true">
					<ng-container *dbNavigationContent>
						Navi-Item 1
					</ng-container>
					<ng-container sub-navigation>
						<db-navigation-item [active]="true">
							<ng-container *dbNavigationContent>
								Sub-Navi-Item 1
							</ng-container>
							<ng-container sub-navigation>
								<db-navigation-item [active]="true">
									<ng-container *dbNavigationContent>
										<a href="#">Sub-Sub-Navi-Item 1</a>
									</ng-container>
								</db-navigation-item>
								<db-navigation-item>
									<ng-container *dbNavigationContent>
										<a href="#">Sub-Sub-Navi-Item 2</a>
									</ng-container>
								</db-navigation-item>
							</ng-container>
						</db-navigation-item>
						<db-navigation-item>
							<ng-container *dbNavigationContent>
								<a href="#">Sub-Navi-Item 2</a>
							</ng-container>
						</db-navigation-item>
					</ng-container>
				</db-navigation-item>
				<db-navigation-item icon="person">
					<ng-container *dbNavigationContent>
						<a href="#">Navi-Item 2</a>
					</ng-container>
				</db-navigation-item>
				<db-navigation-item [disabled]="true">
					<ng-container *dbNavigationContent>
						<a href="#">Navi-Item 3</a>
					</ng-container>
				</db-navigation-item>
			</db-navigation>
		</div>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/navigation/Navigation.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/navigation.json";
import {
	DBInfotext,
	DBNavigation,
	DBNavigationItem
} from "../../../../../output/vue/src";

const getId = (name?: string): string =>
	`${name?.replaceAll(/\W/g, "_").toLowerCase()}`;
</script>

<template>
	<DefaultComponent title="DBNavigation" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<div>
				<DBInfotext
					:id="getId(exampleName)"
					size="small"
					semantic="informational"
					icon="none"
				>
					{{ exampleName }}
				</DBInfotext>
				<DBNavigation :labelledBy="getId(exampleName)">
					<DBNavigationItem :active="true">
						Navi-Item 1
						<template v-slot:sub-navigation>
							<DBNavigationItem :active="true">
								Sub-Navi-Item 1

								<template v-slot:sub-navigation>
									<DBNavigationItem :active="true">
										<a href="#">Sub-Sub-Navi-Item 1</a>
									</DBNavigationItem>
									<DBNavigationItem>
										<a href="#">Sub-Sub-Navi-Item 2</a>
									</DBNavigationItem>
								</template>
							</DBNavigationItem>
							<DBNavigationItem>
								<a href="#">Sub-Navi-Item 2</a>
							</DBNavigationItem>
						</template>
					</DBNavigationItem>
					<DBNavigationItem icon="person">
						<a href="#">Navi-Item 2</a>
					</DBNavigationItem>
					<DBNavigationItem :disabled="true">
						<a href="#">Navi-Item 3</a>
					</DBNavigationItem>
				</DBNavigation>
			</div>
		</template>
	</DefaultComponent>
</template>
