// showcases/vue-showcase/src/App.vue
<script setup lang="ts">
import {
	DBControlPanelBrand,
	DBControlPanelDesktop,
	DBControlPanelMobile,
	DBControlPanelNavigation,
	DBShell,
	DBShellContent,
	DBShellSubNavigation
} from "@components";
import NavItemComponent from "./NavItemComponent.vue";

import { useLayout } from "./composables/use-layout";
import MetaNavigation from "./control-panel/MetaNavigation.vue";
import PrimaryActions from "./control-panel/PrimaryActions.vue";
import SecondaryActions from "./control-panel/SecondaryActions.vue";
import Page from "./page/Page.vue";

const { page, fullscreen, classNames, sortedNavigation, settings, shell } =
	useLayout();
</script>

<template>
	<div
		v-if="page || fullscreen"
		:class="`fullscreen-container ${classNames}`"
	>
		<router-view></router-view>
	</div>
	<Page v-else-if="!shell" />
	<DBShell
		v-if="!page && !fullscreen && shell"
		fadeIn
		:controlPanelDesktopPosition="settings.controlPanelDesktopPosition"
		:controlPanelMobilePosition="settings.controlPanelMobilePosition"
		:subNavigationDesktopPosition="settings.subNavigationDesktopPosition"
		:subNavigationMobilePosition="settings.subNavigationMobilePosition"
		:show-sub-navigation="settings.subNavigation === 'true'"
	>
		<DBShellSubNavigation>
			<DBControlPanelNavigation
				:variant="settings.subNavigationVariant"
				aria-label="sub navigation"
			>
				<template v-for="item of sortedNavigation">
					<NavItemComponent :navItem="item"></NavItemComponent>
				</template>
			</DBControlPanelNavigation>
		</DBShellSubNavigation>
		<DBControlPanelDesktop>
			<template v-slot:brand>
				<DBControlPanelBrand>Showcase</DBControlPanelBrand>
			</template>
			<DBControlPanelNavigation
				:variant="settings.navigationDesktopVariant"
				aria-label="main navigation desktop"
			>
				<template v-for="item of sortedNavigation">
					<NavItemComponent :navItem="item"></NavItemComponent>
				</template>
			</DBControlPanelNavigation>
			<template v-slot:primary-actions>
				<PrimaryActions />
			</template>
			<template v-slot:secondary-actions>
				<SecondaryActions />
			</template>
			<template v-slot:meta>
				<MetaNavigation />
			</template>
		</DBControlPanelDesktop>
		<DBControlPanelMobile drawerHeaderText="Showcase">
			<template v-slot:brand>
				<DBControlPanelBrand>Showcase</DBControlPanelBrand>
			</template>
			<DBControlPanelNavigation
				:variant="settings.navigationMobileVariant"
				aria-label="main navigation mobile"
			>
				<template v-for="item of sortedNavigation">
					<NavItemComponent :navItem="item"></NavItemComponent>
				</template>
			</DBControlPanelNavigation>
			<template v-slot:primary-actions>
				<PrimaryActions />
			</template>
			<template v-slot:secondary-actions>
				<SecondaryActions />
			</template>
			<template v-slot:meta>
				<MetaNavigation />
			</template>
		</DBControlPanelMobile>
		<DBShellContent :class="classNames">
			<router-view></router-view>
		</DBShellContent>
	</DBShell>
</template>

// showcases/next-showcase/pages/_app.tsx
import {
	DBControlPanelBrand,
	DBControlPanelDesktop,
	DBControlPanelMobile,
	DBShell,
	DBShellContent,
	DBShellSubNavigation
} from '@components';
import type { AppProps } from 'next/app';
import { useId } from 'react';
import MetaNavigation from '../../react-showcase/src/control-panel/meta-navigation';
import PrimaryActions from '../../react-showcase/src/control-panel/primary-actions';
import SecondaryActions from '../../react-showcase/src/control-panel/secondary-actions';
import useQuery from '../../react-showcase/src/hooks/use-query';
import Navigation from '../../react-showcase/src/navigation';
import '../../showcase-styles.css';
import '../styles/global.css';

const App = ({ Component, pageProps }: AppProps) => {
	const controlPanelDesktopId = useId();
	const controlPanelMobileId = useId();
	const shellId = useId();

	const {
		density,
		setDensity,
		color,
		setColor,
		page,
		fullscreen,
		setSettings,
		settings
	} = useQuery();

	if (page ?? fullscreen) {
		return (
			<div data-density={density} className={`db-color-${color}`}>
				<Component {...pageProps} />
			</div>
		);
	}

	return (
		<DBShell
			fadeIn
			controlPanelDesktopPosition={settings.controlPanelDesktopPosition}
			controlPanelMobilePosition={settings.controlPanelMobilePosition}
			subNavigationDesktopPosition={settings.subNavigationDesktopPosition}
			subNavigationMobilePosition={settings.subNavigationMobilePosition}
			showSubNavigation={settings.subNavigation === 'true'}>
			<DBShellSubNavigation id={shellId}>
				<Navigation
					variant={settings.subNavigationVariant}
					aria-label="sub navigation"
				/>
			</DBShellSubNavigation>
			<DBControlPanelMobile
				id={controlPanelMobileId}
				drawerHeaderText="Showcase"
				brand={<DBControlPanelBrand data-logo="db-systel" />}
				primaryActions={
					<PrimaryActions
						color={color}
						settings={settings}
						density={density}
						onSettingsChange={setSettings}
						onColorChange={setColor}
						onDensityChange={setDensity}
					/>
				}
				secondaryActions={<SecondaryActions />}
				metaNavigation={<MetaNavigation />}>
				<Navigation variant={settings.navigationMobileVariant} />
			</DBControlPanelMobile>
			<DBControlPanelDesktop
				id={controlPanelDesktopId}
				brand={<DBControlPanelBrand data-logo="db-systel" />}
				metaNavigation={<MetaNavigation />}
				primaryActions={
					<PrimaryActions
						color={color}
						settings={settings}
						density={density}
						onSettingsChange={setSettings}
						onColorChange={setColor}
						onDensityChange={setDensity}
					/>
				}
				secondaryActions={<SecondaryActions />}>
				<Navigation variant={settings.navigationDesktopVariant} />
			</DBControlPanelDesktop>
			<DBShellContent data-density={density} className={`db-${color}`}>
				<Component {...pageProps} />
			</DBShellContent>
		</DBShell>
	);
};

export default App;
