// storybooks/react-storybook/src/templates/table-kitchen-sink/components/DebouncedInput.tsx
import {DBInput} from '@components';
import {
	type ChangeEvent,
	type FC,
	type InputHTMLAttributes,
	useEffect,
	useState,
} from 'react';

type Props = {
	label: string;
	placeholder: string;
	value: string | number;
	onChange: (value: string | number) => void;
	debounce?: number;
} & Omit<InputHTMLAttributes<HTMLInputElement>, 'onChange'>;

export const DebouncedInput: FC<Props> = ({
	value: initialValue,
	onChange,
	debounce = 500,
	label,
	placeholder,
}) => {
	const [value, setValue] = useState<number | string>(initialValue);

	const handleInputChange = (event: ChangeEvent<HTMLInputElement>) =>
		setValue(event.target.value);

	useEffect(() => {
		setValue(initialValue);
	}, [initialValue]);

	useEffect(() => {
		const timeout = setTimeout(() => {
			onChange(value);
		}, debounce);

		return () => clearTimeout(timeout);
	}, [value]);

	return (
		<DBInput
			variant="floating"
			label={label}
			placeholder={placeholder}
			value={value}
			onChange={handleInputChange}
		/>
	);
};

export default DebouncedInput;

// storybooks/vue-storybook/src/templates/table-kitchen-sink/components/DebouncedInput.vue
<script setup lang="ts">
import { DBInput } from "@components";
import { ref, watch } from "vue";

interface Props {
	label: string;
	placeholder: string;
	modelValue: string | number;
	debounce?: number;
}

const props = withDefaults(defineProps<Props>(), {
	debounce: 500
});

const emit = defineEmits<{
	"update:modelValue": [value: string | number];
}>();

const value = ref<string | number>(props.modelValue);

watch(
	() => props.modelValue,
	(newVal) => {
		value.value = newVal;
	}
);

let timeout: ReturnType<typeof setTimeout>;
watch(value, (newVal) => {
	clearTimeout(timeout);
	timeout = setTimeout(() => {
		emit("update:modelValue", newVal);
	}, props.debounce);
});
</script>

<template>
	<DBInput
		variant="floating"
		:label="label"
		:placeholder="placeholder"
		v-model="value"
	/>
</template>
