// storybooks/react-storybook/src/templates/table-kitchen-sink/components/TableControls.tsx
import { DBCard, DBCustomSelect, DBStack } from '@components';
import type { StockFeatures, Table } from '@tanstack/react-table';
import DebouncedInput from './DebouncedInput';

interface TableControlsProps {
	table: Table<StockFeatures, any>;
	globalFilter: string;
	setGlobalFilter: (value: string) => void;
}

export const TableControls = ({
	table,
	globalFilter,
	setGlobalFilter
}: TableControlsProps) => {
	return (
		<DBCard>
			<DBStack>
				<DebouncedInput
					value={globalFilter ?? ''}
					onChange={(value) => setGlobalFilter(String(value))}
					className="mx-1 p-2 font-lg shadow border border-block"
					placeholder="Search all columns..."
					label="Search"
				/>
				<DBCustomSelect
					label="Show Columns"
					placeholder="Show Columns"
					multiple
					values={table
						.getAllLeafColumns()
						.filter((column) => column.getIsVisible())
						.map((column) => column.id)}
					options={table.getAllLeafColumns().map((column) => {
						return { id: column.id, value: column.id };
					})}
					selectAllLabel="Toggle All"
					onOptionSelected={(values) => {
						table.getAllLeafColumns().forEach((column) => {
							column.toggleVisibility(values.includes(column.id));
						});
					}}></DBCustomSelect>
			</DBStack>
		</DBCard>
	);
};

export default TableControls;

// storybooks/vue-storybook/src/templates/table-kitchen-sink/components/TableControls.vue
<script setup lang="ts">
import { DBCard, DBCustomSelect, DBStack } from "@components";
import type { StockFeatures, Table } from "@tanstack/vue-table";
import { computed, defineEmits, defineProps } from "vue";
import DebouncedInput from "./DebouncedInput.vue";

interface Props {
	table: Table<StockFeatures, any>;
	globalFilter: string;
}

const props = defineProps<Props>();
const emit = defineEmits<{
	"update:globalFilter": [value: string];
}>();

const visibleColumns = computed(() =>
	props.table
		.getAllLeafColumns()
		.filter((column) => column.getIsVisible())
		.map((column) => column.id)
);

const columnOptions = computed(() =>
	props.table
		.getAllLeafColumns()
		.map((column) => ({ id: column.id, value: column.id }))
);

const handleColumnSelection = (values: string[]) => {
	props.table.getAllLeafColumns().forEach((column) => {
		column.toggleVisibility(values.includes(column.id));
	});
};
</script>

<template>
	<DBCard>
		<DBStack>
			<DebouncedInput
				:modelValue="globalFilter ?? ''"
				@update:modelValue="emit('update:globalFilter', String($event))"
				placeholder="Search all columns..."
				label="Search"
			/>
			<DBCustomSelect
				label="Show Columns"
				placeholder="Show Columns"
				multiple
				:values="visibleColumns"
				:options="columnOptions"
				selectAllLabel="Toggle All"
				@optionSelected="handleColumnSelection"
			/>
		</DBStack>
	</DBCard>
</template>
