// showcases/vue-showcase/src/components/custom-select/CustomSelect.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/custom-select.json";
import { DBCustomSelect, DBInfotext } from "../../../../../output/vue/src";
import { CustomSelectOptionType } from "@db-ux/core-components/src/components/custom-select/model";

const log = (values: string[]) => {
	// eslint-disable-next-line no-alert
	console.log(values);
};

const getAriaLabel = (exampleProps, exampleName): string => {
	return `${exampleProps.id}-${exampleName}`;
};

const getTransformSelectedLabels = (selectedOptions?: any): string => {
	return selectedOptions.map((option: any) => option.value.at(option.value.length - 1)).join(", ");
};

const getSearchFilter = (option: CustomSelectOptionType, _: string): boolean => option.value === "Option 1";
</script>

<template>
	<DefaultComponent title="DBCustomSelect" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
			<DBInfotext v-if="exampleProps?.info" size="small" semantic="informational">
				{{ exampleName }}
			</DBInfotext>

			<i v-if="exampleProps?.lineBreak" class="line-break" />

			<DBCustomSelect
				v-if="!exampleProps?.lineBreak && !exampleProps?.info"
				:ariaListLabel="getAriaLabel(exampleProps, exampleName)"
				:disabled="exampleProps?.disabled"
				:icon="exampleProps?.icon"
				:showMessage="exampleProps?.showMessage"
				:showIcon="exampleProps?.showIcon"
				:dropdownWidth="exampleProps?.dropdownWidth"
				:showClearSelection="exampleProps?.showClearSelection"
				:showSelectAll="exampleProps?.showSelectAll"
				:showSearch="exampleProps?.showSearch"
				:showLoading="exampleProps?.showLoading"
				:showNoResults="exampleProps?.showNoResults"
				:multiple="exampleProps?.multiple"
				:loadingText="exampleProps?.loadingText"
				:noResultsText="exampleProps?.noResultsText ?? 'No matching filter'"
				:label="exampleName"
				:options="exampleProps?.options"
				:variant="exampleProps?.variant"
				:message="exampleProps?.message"
				:required="exampleProps?.required"
				:placeholder="exampleProps?.placeholder"
				:showLabel="exampleProps?.showLabel"
				:placement="exampleProps?.placement"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:validation="exampleProps?.validation"
				selectAllLabel="Select all"
				searchLabel="Search"
				:searchValue="exampleProps?.searchValue"
				:selectedLabels="exampleProps?.selectedLabels"
				:transformSelectedLabels="exampleProps?.transformSelectedLabels ? getTransformSelectedLabels : undefined"
				:searchFilter="exampleProps?.searchFilter ? getSearchFilter : undefined"
				:selectedType="exampleProps?.selectedType"
				:formFieldWidth="exampleProps?.formFieldWidth"
				:on-option-selected="(values) => log(values)"
			/>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/custom-select/custom-select.component.ts
import { Component } from '@angular/core';
import { CustomSelectOptionType } from '@db-ux/core-components/src/components/custom-select/model';
import {
	DBCustomSelect,
	DBInfotext
} from '../../../../../../output/angular/src';
import defaultComponentVariants from '../../../../../shared/custom-select.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-custom-select',
	templateUrl: './custom-select.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBInfotext, DBCustomSelect],
	standalone: true
})
export class CustomSelectComponent {
	variants = defaultComponentVariants;
	protected readonly console = console;

	getAriaLabel(exampleProps: any, exampleName: string): string {
		return `${exampleProps.id}-${exampleName}`;
	}

	getTransformSelectedLabels(selectedOptions?: any): string {
		return selectedOptions
			.map((option: any) => option.value.at(-1))
			.join(', ');
	}

	getSearchFilter(option: CustomSelectOptionType, _: string): boolean {
		return option.value === 'Option 1';
	}
}

<app-default-component
	title="DBCustomSelect"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		@if (exampleProps?.info) {
			<db-infotext size="small" semantic="informational">
				{{ exampleName }}
			</db-infotext>
		} @else if (exampleProps?.lineBreak) {
			<i class="line-break"></i>
		} @else {
			<db-custom-select
				[showRequiredAsterisk]="exampleProps?.showRequiredAsterisk"
				[listLabel]="getAriaLabel(exampleProps, exampleName)"
				[disabled]="exampleProps?.disabled"
				[showMessage]="exampleProps?.showMessage"
				[icon]="exampleProps?.icon"
				[showIcon]="exampleProps?.showIcon"
				[dropdownWidth]="exampleProps?.dropdownWidth"
				[showClearSelection]="exampleProps?.showClearSelection"
				[showSelectAll]="exampleProps?.showSelectAll"
				[showSearch]="exampleProps?.showSearch"
				[showLoading]="exampleProps?.showLoading"
				[showNoResults]="exampleProps?.showNoResults"
				[multiple]="exampleProps?.multiple"
				[loadingText]="exampleProps?.loadingText"
				[noResultsText]="
					exampleProps?.noResultsText ?? 'No matching filter'
				"
				[label]="exampleName"
				[options]="exampleProps?.options"
				[variant]="exampleProps?.variant"
				[message]="exampleProps?.message"
				[required]="exampleProps?.required"
				[placeholder]="exampleProps?.placeholder"
				[showLabel]="exampleProps?.showLabel"
				[placement]="exampleProps?.placement"
				[selectAllLabel]="'Select all'"
				[searchLabel]="'Search'"
				[searchValue]="exampleProps?.searchValue"
				[selectedLabels]="exampleProps?.selectedLabels"
				[selectedPrefix]="'Selected'"
				[transformSelectedLabels]="
					exampleProps?.transformSelectedLabels
						? getTransformSelectedLabels
						: undefined
				"
				[searchFilter]="
					exampleProps?.searchFilter ? getSearchFilter : undefined
				"
				[selectedType]="exampleProps?.selectedType"
				[formFieldWidth]="exampleProps?.formFieldWidth"
				[invalidMessage]="exampleProps?.invalidMessage"
				[validMessage]="exampleProps?.validMessage"
				[validation]="exampleProps?.validation"
				(optionSelected)="console.log($event)"
				[removeTagsTexts]="exampleProps?.removeTagsTexts"
			></db-custom-select>
		}
	</ng-template>
</app-default-component>
