// showcases/vue-showcase/src/components/checkbox/Checkbox.vue
<script setup lang="ts">
import { DBCheckbox, DBInfotext } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/checkbox.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBCheckbox" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBCheckbox
				:showRequiredAsterisk="exampleProps?.showRequiredAsterisk"
				:label="exampleProps?.label"
				:variant="exampleProps?.variant"
				:show-label="exampleProps?.showLabel"
				:options="exampleProps?.options"
				:checked="exampleProps?.checked"
				:disabled="exampleProps?.disabled"
				:value="exampleProps?.value"
				:required="exampleProps?.required"
				:validation="exampleProps?.validation"
				:invalidMessage="exampleProps?.invalidMessage"
				:validMessage="exampleProps?.validMessage"
				:indeterminate="exampleProps?.indeterminate"
				:size="exampleProps?.size"
				>{{ exampleName }}</DBCheckbox
			>

			<template
				v-if="
					exampleProps?.showLabel !== undefined &&
					!exampleProps?.showLabel
				"
			>
				<DBInfotext
					semantic="informational"
					size="small"
					:showIcon="false"
				>
					{{ exampleName }}
				</DBInfotext>
			</template>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/checkbox/index.tsx
import { DBCheckbox, DBInfotext, getBoolean } from '@components';
import { type DBCheckboxProps } from '@components/src/components/checkbox/model';
import defaultComponentVariants from '../../../../shared/checkbox.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getCheckbox = ({
	label,
	size,
	name,
	checked,
	required,
	children,
	disabled,
	indeterminate,
	variant,
	showLabel,
	validation,
	invalidMessage,
	validMessage,
	showRequiredAsterisk
}: DBCheckboxProps) => (
	<>
		<DBCheckbox
			label={label}
			size={size}
			name={name}
			defaultChecked={getBoolean(checked)}
			invalidMessage={invalidMessage}
			validMessage={validMessage}
			showRequiredAsterisk={showRequiredAsterisk}
			required={required}
			disabled={disabled}
			variant={variant}
			showLabel={showLabel}
			indeterminate={indeterminate}
			validation={validation}>
			{children}
		</DBCheckbox>
		{showLabel !== undefined && !showLabel && (
			<DBInfotext size="small" semantic="informational" showIcon={false}>
				{children}
			</DBInfotext>
		)}
	</>
);

const CheckboxComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title={'DBCheckbox'}
			variants={getVariants(
				defaultComponentVariants,
				getCheckbox,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default CheckboxComponent;
