// showcases/react-showcase/src/components/tabs/index.tsx
import { DBTabs, DBTabList, DBTabItem, DBTabPanel, DBInfotext } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/tabs.json';
import type { DBTabsProps } from '../../../../../output/react/src/components/tabs/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getTabs = ({
	children,
	orientation,
	width,
	alignment,
	overflow,
	behavior,
	initialSelectedMode,
	initialSelectedIndex
}: DBTabsProps & { overflow: boolean }) => (
	<div className="w-full">
		<DBInfotext icon="none" size="small" semantic="informational">
			{children}:
		</DBInfotext>
		<DBTabs
			orientation={orientation}
			width={width}
			alignment={alignment}
			behavior={behavior}
			initialSelectedIndex={initialSelectedIndex}
			initialSelectedMode={initialSelectedMode}
			arrowScrollDistance={75}>
			<DBTabList>
				<DBTabItem>Test 1</DBTabItem>
				<DBTabItem>Test 2</DBTabItem>
				<DBTabItem>Test 3</DBTabItem>
				{overflow && (
					<>
						<DBTabItem>Test 4</DBTabItem>
						<DBTabItem>Test 5</DBTabItem>
					</>
				)}
			</DBTabList>
			<DBTabPanel>Tab Panel 1</DBTabPanel>
			<DBTabPanel>Tab Panel 2</DBTabPanel>
			<DBTabPanel>Tab Panel 3</DBTabPanel>
			{overflow && (
				<>
					<DBTabPanel>Tab Panel 4</DBTabPanel>
					<DBTabPanel>Tab Panel 5</DBTabPanel>
				</>
			)}
		</DBTabs>
	</div>
);

const TabsComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBTabs"
			subComponent={props.subComponent}
			variants={getVariants(defaultComponentVariants, getTabs, props.slotCode)}></DefaultComponent>
	);
};

export default TabsComponent;

// showcases/vue-showcase/src/components/tabs/Tabs.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tabs.json";
import { DBTabs, DBInfotext, DBTabList, DBTabItem, DBTabPanel } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBTabs" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
			<div class="w-full">
				<DBInfotext icon="none" size="small" semantic="informational"> {{ exampleName }}: </DBInfotext>
				<DBTabs
					:orientation="exampleProps?.orientation"
					:width="exampleProps?.width"
					:alignment="exampleProps?.alignment"
					:behavior="exampleProps?.behavior"
					:initialSelectedIndex="exampleProps?.initialSelectedIndex"
					:initialSelectedMode="exampleProps?.initialSelectedMode"
					:arrowScrollDistance="75"
				>
					<DBTabList>
						<DBTabItem> Test 1 </DBTabItem>
						<DBTabItem> Test 2 </DBTabItem>
						<DBTabItem> Test 3 </DBTabItem>
						<template v-if="exampleProps?.overflow">
							<DBTabItem> Test 4 </DBTabItem>
							<DBTabItem> Test 5 </DBTabItem>
						</template>
					</DBTabList>
					<DBTabPanel> Tab Panel 1 </DBTabPanel>
					<DBTabPanel> Tab Panel 2 </DBTabPanel>
					<DBTabPanel> Tab Panel 3 </DBTabPanel>
					<template v-if="exampleProps?.overflow">
						<DBTabPanel> Tab Panel 4 </DBTabPanel>
						<DBTabPanel> Tab Panel 5 </DBTabPanel>
					</template>
				</DBTabs>
			</div>
		</template>
	</DefaultComponent>
</template>
