// showcases/vue-showcase/src/components/card/Card.vue
<script setup lang="ts">
import { DBCard } from "../../../../../output/vue/src";
import defaultComponentVariants from "../../../../shared/card.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBCard" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<button v-if="exampleProps?.behavior === 'interactive'">
				<DBCard
					:behavior="exampleProps?.behavior"
					:elevationLevel="exampleProps?.elevationLevel"
					:spacing="exampleProps?.spacing"
				>
					<strong>{{ exampleName }}</strong>
				</DBCard>
			</button>
			<DBCard
				v-if="exampleProps?.behavior !== 'interactive'"
				:behavior="exampleProps?.behavior"
				:elevationLevel="exampleProps?.elevationLevel"
				:spacing="exampleProps?.spacing"
			>
				<strong>{{ exampleName }}</strong>
			</DBCard>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/card/index.tsx
import { DBCard } from '../../../../../output/react/src';
import type { DBCardProps } from '../../../../../output/react/src/components/card/model';
import defaultComponentVariants from '../../../../shared/card.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getCard = ({
	behavior,
	children,
	spacing,
	elevationLevel
}: DBCardProps) => {
	const card = (
		<DBCard
			behavior={behavior}
			spacing={spacing}
			elevationLevel={elevationLevel}>
			<strong>{children}</strong>
		</DBCard>
	);

	return behavior === 'interactive' ? (
		<button type="button">
			{card}
		</button>
	) : (
		card
	);
};

const CardComponent = (properties: BaseComponentProps) => (
	<DefaultComponent
		title={'DBCard'}
		variants={getVariants(
			defaultComponentVariants,
			getCard,
			properties.slotCode
		)}></DefaultComponent>
);

export default CardComponent;
