// showcases/vue-showcase/src/components/footer/Footer.vue
<script setup lang="ts">
import { DBFooter } from "../../../../../output/vue/src";
import defaultComponentVariants from "../../../../shared/footer.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<div class="footer-page">
		<DefaultComponent title="DBFooter" :variants="defaultComponentVariants">
			<template #example="{ exampleProps, exampleName, exampleContent }">
				<DBFooter
					:showCopyright="exampleProps?.showCopyright ?? true"
					:showMain="exampleProps?.showMain ?? true"
					:showMeta="exampleProps?.showMeta ?? true"
					:width="exampleProps?.width"
				>
					<template #main>
						<span>{{ exampleContent ?? exampleName }}</span>
					</template>
				</DBFooter>
			</template>
		</DefaultComponent>
	</div>
</template>

// showcases/react-showcase/src/components/footer/index.tsx
import { DBFooter } from '../../../../../output/react/src';
import defaultComponentVariants from '../../../../shared/footer.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getFooter = ({
	children,
	showCopyright,
	showMain,
	showMeta,
	width
}: any) => (
	<DBFooter
		showCopyright={showCopyright ?? true}
		showMain={showMain ?? true}
		showMeta={showMeta ?? true}
		width={width}
		main={<span>{children}</span>}
	/>
);

const FooterComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBFooter"
			variants={getVariants(
				defaultComponentVariants,
				getFooter,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default FooterComponent;
