// showcases/react-showcase/src/components/section/index.tsx
import { DBCard, DBSection } from '../../../../../output/react/src';
import { type DBSectionProps } from '../../../../../output/react/src/components/section/model';
import defaultComponentVariants from '../../../../shared/section.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getSection = ({ width, spacing, children, id }: DBSectionProps) => (
	<DBSection
		className="db-color-informational db-bg-color-basic-level-2  section-card-container"
		spacing={spacing}
		width={width}
		id={id}>
		<DBCard>{children}</DBCard>
		<DBCard>{children}</DBCard>
		<DBCard>{children}</DBCard>
		<DBCard>{children}</DBCard>
	</DBSection>
);

const SectionComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title={'DBSection'}
			variants={getVariants(
				defaultComponentVariants,
				getSection,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default SectionComponent;

// showcases/vue-showcase/src/components/section/Section.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/section.json";
import { DBSection, DBCard } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBSection" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
			<DBSection
				class="db-color-informational db-bg-color-basic-level-2 section-card-container"
				:spacing="exampleProps?.spacing"
				:width="exampleProps?.width"
			>
				<DBCard>{{ exampleName }}</DBCard>
				<DBCard>{{ exampleName }}</DBCard>
				<DBCard>{{ exampleName }}</DBCard>
				<DBCard>{{ exampleName }}</DBCard>
			</DBSection>
		</template>
	</DefaultComponent>
</template>
