// showcases/angular-showcase/src/app/components/section/section.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBCard, DBSection } from '@db-ux/ngx-core-components/src';
import defaultComponentVariants from '../../../../../shared/section.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-section',
	templateUrl: './section.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBSection, DBCard],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : [],
	standalone: true
})
export class SectionComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBSection"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-section
			class="db-color-informational db-bg-color-basic-level-2 section-card-container"
			[spacing]="exampleProps?.spacing"
			[width]="exampleProps?.width"
			[id]="exampleProps?.id"
		>
			<db-card>{{ exampleName }}</db-card>
			<db-card>{{ exampleName }}</db-card>
			<db-card>{{ exampleName }}</db-card>
			<db-card>{{ exampleName }}</db-card>
		</db-section>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/section/Section.vue
<script setup lang="ts">
import { DBCard, DBSection } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/section.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBSection" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBSection
				class="db-color-informational db-bg-color-basic-level-2 section-card-container"
				:spacing="exampleProps?.spacing"
				:width="exampleProps?.width"
				:id="exampleProps?.id"
			>
				<DBCard>{{ exampleName }}</DBCard>
				<DBCard>{{ exampleName }}</DBCard>
				<DBCard>{{ exampleName }}</DBCard>
				<DBCard>{{ exampleName }}</DBCard>
			</DBSection>
		</template>
	</DefaultComponent>
</template>
