// showcases/vue-showcase/src/components/control-panel-desktop/ControlPanelDesktop.vue
<script setup lang="ts">
import {
	DBButton,
	DBControlPanelBrand,
	DBControlPanelDesktop,
	DBControlPanelMetaNavigation,
	DBControlPanelPrimaryActions,
	DBControlPanelSecondaryActions,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from "@components";
import defaultComponentVariants from "../../../../shared/control-panel-desktop.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBHeader" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBControlPanelDesktop
				:width="exampleProps?.width"
				:orientation="exampleProps?.orientation ?? 'horizontal'"
			>
				<template v-slot:brand>
					<DBControlPanelBrand>
						<template v-if="exampleProps?.withName ?? true">
							DBHeader
						</template>
					</DBControlPanelBrand>
				</template>
				<template v-if="exampleProps?.withNavigation ?? true">
					<DBNavigation :aria-label="exampleName">
						<DBNavigationItem icon="x_placeholder">
							<a href="#">{{ exampleName }}</a>
						</DBNavigationItem>
						<DBNavigationItem icon="x_placeholder" :disabled="true">
							<a href="#">{{ exampleName }} disabled</a>
						</DBNavigationItem>
					</DBNavigation>
				</template>
				<template v-slot:primary-actions>
					<template v-if="exampleProps?.withPrimary ?? true">
						<DBControlPanelPrimaryActions>
							<DBButton
								icon="magnifying_glass"
								variant="ghost"
								noText
							>
								Search
							</DBButton>
						</DBControlPanelPrimaryActions>
					</template>
				</template>
				<template v-slot:secondary-actions>
					<template v-if="exampleProps?.withSecondary ?? true">
						<DBControlPanelSecondaryActions>
							<DBButton
								icon="x_placeholder"
								variant="ghost"
								noText
							>
								Profile
							</DBButton>
							<DBButton
								icon="x_placeholder"
								variant="ghost"
								noText
							>
								Notification
							</DBButton>
							<DBButton
								icon="x_placeholder"
								variant="ghost"
								noText
							>
								Help
							</DBButton>
						</DBControlPanelSecondaryActions>
					</template>
				</template>
				<template v-slot:meta-navigation>
					<template v-if="exampleProps?.withMeta ?? true">
						<DBControlPanelMetaNavigation>
							<DBLink href="#">Imprint</DBLink>
							<DBLink href="#">Help</DBLink>
						</DBControlPanelMetaNavigation>
					</template>
				</template>
			</DBControlPanelDesktop>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/control-panel-desktop/control-panel-desktop.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
	DBButton,
	DBControlPanelBrand,
	DBControlPanelDesktop,
	DBControlPanelMetaNavigation,
	DBControlPanelPrimaryActions,
	DBControlPanelSecondaryActions,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from '@components';
import defaultComponentVariants from '../../../../../shared/control-panel-desktop.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-control-panel-desktop',
	templateUrl: './control-panel-desktop.component.html',
	imports: [
		environment.webComponents
			? [DefaultComponent]
			: [
					DefaultComponent,
					DBControlPanelDesktop,
					DBControlPanelBrand,
					DBControlPanelMetaNavigation,
					DBNavigation,
					DBNavigationItem,
					DBControlPanelPrimaryActions,
					DBControlPanelSecondaryActions,
					DBButton,
					DBLink
				]
	],
	standalone: true,
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class ControlPanelDesktopComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBControlPanelDesktop"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-control-panel-desktop
			[width]="exampleProps?.width"
			[orientation]="exampleProps?.orientation ?? 'horizontal'"
		>
			<db-control-panel-brand brand slot="brand">
				@if (exampleProps?.withName ?? true) {
					DBHeader
				}
			</db-control-panel-brand>
			@if (exampleProps?.withNavigation ?? true) {
				<db-navigation [attr.aria-label]="exampleName">
					<db-navigation-item icon="x_placeholder">
						<a href="#">{{ exampleName }} </a>
					</db-navigation-item>
					<db-navigation-item icon="x_placeholder" [disabled]="true">
						<a href="#">{{ exampleName }} disabled </a>
					</db-navigation-item>
				</db-navigation>
			}
			<ng-container meta-navigation>
				@if (exampleProps?.withMeta ?? true) {
					<db-control-panel-meta-navigation slot="metaNavigation">
						<db-link href="#">Imprint</db-link>
						<db-link href="#">Help</db-link>
					</db-control-panel-meta-navigation>
				}
			</ng-container>
			<ng-container primary-actions>
				@if (exampleProps?.withPrimary ?? true) {
					<db-control-panel-primary-actions slot="primaryActions">
						<db-button
							icon="magnifying_glass"
							variant="ghost"
							[noText]="true"
						>
							Search
						</db-button>
					</db-control-panel-primary-actions>
				}
			</ng-container>
			<ng-container secondary-actions>
				@if (exampleProps?.withSecondary ?? true) {
					<db-control-panel-secondary-actions slot="secondaryActions">
						<db-button
							icon="x_placeholder"
							variant="ghost"
							[noText]="true"
						>
							Profile
						</db-button>
						<db-button
							icon="x_placeholder"
							variant="ghost"
							[noText]="true"
						>
							Notification
						</db-button>
						<db-button
							icon="x_placeholder"
							variant="ghost"
							[noText]="true"
						>
							Help
						</db-button>
					</db-control-panel-secondary-actions>
				}
			</ng-container>
		</db-control-panel-desktop>
	</ng-template>
</app-default-component>
