// showcases/vue-showcase/src/components/tab-panel/TabPanel.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tab-panel.json";
import { DBTabPanel } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTabPanel" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
            <DBTabPanel>{{exampleName}}</DBTabPanel>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/tab-panel/tab-panel.component.ts
import { Component } from '@angular/core';

import defaultComponentVariants from '../../../../../shared/tab-panel.json';

@Component({
	selector: 'app-tab-panel',
	templateUrl: './tab-panel.component.html'
})
export class TabPanelComponent {
	variants = defaultComponentVariants;
}



<app-default-component
	title="DBTabPanel"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-tab-panel>{{exampleName}}</db-tab-panel>
	</ng-template>
</app-default-component>
