// showcases/angular-showcase/src/app/components/popover/popover.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBButton, DBPopover } from '@db-ux/ngx-core-components/src';
import defaultComponentVariants from '../../../../../shared/popover.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-popover',
	templateUrl: './popover.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBPopover, DBButton],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : [],
	standalone: true
})
export class PopoverComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBPopover"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-popover
			[width]="exampleProps.width"
			[gap]="exampleProps.gap"
			[spacing]="exampleProps.spacing"
			[placement]="exampleProps.placement"
			[animation]="exampleProps.animation"
			[delay]="exampleProps.delay"
			[id]="exampleProps.id"
		>
			<db-button trigger [describedbyid]="exampleProps.id">
				{{ exampleName }}
			</db-button>
			@if (exampleProps.content) {
				{{ exampleProps.content }}
			} @else {
				<ul class="popover-list">
					<li>Popover Custom Item 1</li>
					<li>Popover Custom Item 2</li>
					<li>
						<db-button>Popover Custom Item 3</db-button>
					</li>
				</ul>
			}
		</db-popover>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/popover/Popover.vue
<script setup lang="ts">
import { DBButton, DBPopover } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/popover.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBPopover" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBPopover
				:width="exampleProps?.width"
				:gap="exampleProps?.gap"
				:spacing="exampleProps?.spacing"
				:placement="exampleProps?.placement"
				:animation="exampleProps?.animation"
				:delay="exampleProps?.delay"
				:id="exampleProps?.id"
			>
				<template v-slot:trigger>
					<DBButton>
						{{ exampleName }}
					</DBButton>
				</template>
				<template v-if="exampleProps?.content">{{
					exampleProps?.content
				}}</template>
				<template v-if="!exampleProps?.content">
					<ul class="popover-list">
						<li>Popover Custom Item 1</li>
						<li>Popover Custom Item 2</li>
					</ul>
					<DBButton>Popover Custom Item 3</DBButton>
				</template>
			</DBPopover>
		</template>
	</DefaultComponent>
</template>
