// showcases/react-showcase/src/components/divider/index.tsx
import { DBDivider, DBInfotext } from '@components';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/divider.json';
import { type DBDividerProps } from '@components/src/components/divider/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getDivider = ({ variant, emphasis, children, width }: DBDividerProps) => (
	<>
		<DBInfotext size="small" semantic="informational">
			{children}
		</DBInfotext>
		<DBDivider variant={variant} emphasis={emphasis} width={width} />
	</>
);

const DividerComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBDivider"
			variants={getVariants(
				defaultComponentVariants,
				getDivider,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default DividerComponent;

// showcases/vue-showcase/src/components/divider/Divider.vue
<script setup lang="ts">
import { DBDivider, DBInfotext } from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/divider.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBDivider" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext size="small" semantic="informational">
				{{ exampleName }}</DBInfotext
			>
			<DBDivider
				:variant="exampleProps?.variant"
				:emphasis="exampleProps?.emphasis"
				:width="exampleProps?.width"
			/>
		</template>
	</DefaultComponent>
</template>
