// showcases/angular-showcase/src/app/components/divider/divider.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
	DBDivider,
	DBInfotext
} from '../../../../../../packages/ngx-core-components/src';
import defaultComponentVariants from '../../../../../shared/divider.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-divider',
	templateUrl: './divider.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBDivider, DBInfotext],
	standalone: true,
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class DividerComponent {
	variants = defaultComponentVariants;
}

<app-default-component title="DBDivider" [variants]="variants" [exampleTemplate]="exampleTemplate">
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-infotext size="small" semantic="informational"> {{ exampleName }}</db-infotext>
		<db-divider [variant]="exampleProps?.variant" [emphasis]="exampleProps?.emphasis" [width]="exampleProps?.width"> </db-divider>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/divider/Divider.vue
<script setup lang="ts">
import {
	DBDivider,
	DBInfotext
} from "../../../../../packages/v-core-components/src";
import defaultComponentVariants from "../../../../shared/divider.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBDivider" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext size="small" semantic="informational">
				{{ exampleName }}</DBInfotext
			>
			<DBDivider
				:variant="exampleProps?.variant"
				:emphasis="exampleProps?.emphasis"
				:width="exampleProps?.width"
			/>
		</template>
	</DefaultComponent>
</template>
