// showcases/angular-showcase/src/app/components/tab-list/tab-list.component.ts
import { Component } from '@angular/core';

import defaultComponentVariants from '../../../../../shared/tab-list.json';

@Component({
	selector: 'app-tab-list',
	templateUrl: './tab-list.component.html'
})
export class TabListComponent {
	variants = defaultComponentVariants;
}



<app-default-component
	title="DBTabList"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-tab-list>{{exampleName}}</db-tab-list>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/tab-list/TabList.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tab-list.json";
import { DBTabList } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTabList" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
            <DBTabList>{{exampleName}}</DBTabList>
		</template>
	</DefaultComponent>
</template>
