// showcases/vue-showcase/src/components/tabs/Tabs.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tabs.json";
import {
	DBTabs,
	DBInfotext,
	DBTabList,
	DBTab,
	DBTabPanel
} from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTabs" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<div class="w-full">
				<DBInfotext icon="none" size="small" variant="informational">
					{{ exampleName }}:
				</DBInfotext>
				<DBTabs
					:orientation="exampleProps.orientation"
					:width="exampleProps.width"
					:alignment="exampleProps.alignment"
					:behaviour="exampleProps.behaviour"
					:initialSelectedIndex="exampleProps.initialSelectedIndex"
					:initialSelectedMode="exampleProps.initialSelectedMode"
					:arrowScrollDistance="75"
				>
					<DBTabList>
						<DBTab :name="exampleName" :index="0"> Test 1 </DBTab>
						<DBTab :name="exampleName" :index="1"> Test 2 </DBTab>
						<DBTab :name="exampleName" :index="2"> Test 3 </DBTab>
						<template v-if="exampleProps.overflow">
							<DBTab :name="exampleName" :index="3">
								Test 4
							</DBTab>
							<DBTab :name="exampleName" :index="4">
								Test 5
							</DBTab></template
						>
					</DBTabList>
					<DBTabPanel :name="exampleName" :index="0">
						Tab Panel 1
					</DBTabPanel>
					<DBTabPanel :name="exampleName" :index="1">
						Tab Panel 2
					</DBTabPanel>
					<DBTabPanel :name="exampleName" :index="2">
						Tab Panel 3
					</DBTabPanel>
					<template v-if="exampleProps.overflow">
						<DBTabPanel :name="exampleName" :index="3">
							Tab Panel 4
						</DBTabPanel>
						<DBTabPanel :name="exampleName" :index="4">
							Tab Panel 5
						</DBTabPanel>
					</template>
				</DBTabs>
			</div>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/tabs/tabs.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/tabs.json';
import { DefaultComponent } from '../default.component';
import {
	DBInfotext,
	DBTabItem,
	DBTabList,
	DBTabPanel,
	DBTabs
} from '../../../../../../output/angular/src';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-tabs',
	templateUrl: './tabs.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [
				DefaultComponent,
				DBTabs,
				DBTabItem,
				DBTabList,
				DBTabPanel,
				DBInfotext
			],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : [],
	standalone: true
})
export class TabsComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBTabs"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<div class="w-full">
			<db-infotext icon="none" size="small" variant="informational">
				{{ exampleName }}:
			</db-infotext>
			<db-tabs
				[orientation]="exampleProps.orientation"
				[width]="exampleProps.width"
				[alignment]="exampleProps.alignment"
				[behaviour]="exampleProps.behaviour"
				[initialSelectedIndex]="exampleProps.initialSelectedIndex"
				[initialSelectedMode]="exampleProps.initialSelectedMode"
				[arrowScrollDistance]="75"
			>
				<db-tab-list>
					<db-tab [name]="exampleName" [index]="0">Test 1</db-tab>
					<db-tab [name]="exampleName" [index]="1">Test 2</db-tab>
					<db-tab [name]="exampleName" [index]="2">Test 3</db-tab>
					<ng-container *ngIf="exampleProps.overflow">
						<db-tab [name]="exampleName" [index]="3">Test 4</db-tab>
						<db-tab [name]="exampleName" [index]="4">Test 5</db-tab>
					</ng-container>
				</db-tab-list>
				<db-tab-panel [name]="exampleName" [index]="0">
					Tab Panel 1
				</db-tab-panel>
				<db-tab-panel [name]="exampleName" [index]="1">
					Tab Panel 2
				</db-tab-panel>
				<db-tab-panel [name]="exampleName" [index]="2">
					Tab Panel 3
				</db-tab-panel>
				<ng-container *ngIf="exampleProps.overflow">
					<db-tab-panel [name]="exampleName" [index]="3">
						Tab Panel 4
					</db-tab-panel>
					<db-tab-panel [name]="exampleName" [index]="4">
						Tab Panel 5
					</db-tab-panel>
				</ng-container>
			</db-tabs>
		</div>
	</ng-template>
</app-default-component>
