// showcases/vue-showcase/src/components/badge/Badge.vue
<script setup lang="ts">
import {
	DBBadge,
	DBButton,
	DBIcon,
	DBInfotext
} from "@db-ux/v-core-components/src";
import defaultComponentVariants from "../../../../shared/badge.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent title="DBBadge" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<i class="line-break" v-if="exampleProps?.lineBreak" />
			<template v-if="!exampleProps?.lineBreak">
				<template
					v-if="!exampleProps?.placement && !exampleProps?.example"
				>
					<DBBadge
						:semantic="exampleProps?.semantic"
						:emphasis="exampleProps?.emphasis"
						:size="exampleProps?.size"
					>
						{{ exampleProps?.noContent ? "" : exampleName }}
					</DBBadge>
					<DBInfotext
						v-if="exampleProps?.noContent"
						semantic="informational"
						size="small"
						icon="none"
					>
						{{ exampleName }}
					</DBInfotext>
				</template>

				<template
					v-if="
						exampleProps?.placement &&
						exampleProps?.placement !== 'inline' &&
						!exampleProps?.example
					"
				>
					<DBButton
						icon="x_placeholder"
						variant="outlined"
						:noText="true"
					>
						<DBBadge
							emphasis="strong"
							semantic="critical"
							size="small"
							:placement="exampleProps?.placement"
						>
						</DBBadge>
						{{ exampleName }}
					</DBButton>
					<DBInfotext
						semantic="informational"
						size="small"
						icon="none"
					>
						{{ exampleName }}
					</DBInfotext>
				</template>

				<template v-if="exampleProps?.placement === 'inline'">
					<div class="badge-inline-container">
						<DBIcon icon="x_placeholder"></DBIcon>
						<span>{{ exampleName }}</span>
						<DBBadge
							size="small"
							emphasis="strong"
							semantic="critical"
						>
							Label
						</DBBadge>
						<DBIcon icon="error"></DBIcon>
					</div>
				</template>

				<template v-if="exampleProps?.example === 'icon'">
					<DBBadge
						semantic="critical"
						emphasis="strong"
						:size="exampleProps?.size"
					>
						<DBIcon icon="x_placeholder">{{ exampleName }}</DBIcon>
					</DBBadge>
					<DBInfotext
						semantic="informational"
						size="small"
						icon="none"
					>
						{{ exampleName }}
					</DBInfotext>
				</template>

				<template v-if="exampleProps?.example === 'number'">
					<DBBadge semantic="successful">9</DBBadge>
					<DBBadge semantic="informational">12</DBBadge>
					<DBBadge semantic="warning">123</DBBadge>
					<DBBadge
						size="small"
						emphasis="strong"
						semantic="successful"
					>
						9
					</DBBadge>
					<DBBadge
						size="small"
						emphasis="strong"
						semantic="informational"
					>
						12
					</DBBadge>
					<DBBadge size="small" emphasis="strong" semantic="warning">
						123
					</DBBadge>
					<DBInfotext
						semantic="informational"
						size="small"
						icon="none"
					>
						{{ exampleName }}
					</DBInfotext>
				</template></template
			>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/badge/badge.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
	DBBadge,
	DBButton,
	DBIcon,
	DBInfotext
} from '@components';
import defaultComponentVariants from '../../../../../shared/badge.json';
import { DefaultComponent } from '../default.component';
import { environment } from '../../../environments/environment';

@Component({
	selector: 'app-badge',
	templateUrl: './badge.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBBadge, DBInfotext, DBButton, DBIcon],
	standalone: true,
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : []
})
export class BadgeComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBBadge"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		@if (exampleProps?.lineBreak) {
			<i class="line-break"></i>
		} @else {
			@if (!exampleProps?.placement && !exampleProps?.example) {
				<db-badge
					[semantic]="exampleProps?.semantic"
					[emphasis]="exampleProps?.emphasis"
					[size]="exampleProps?.size"
					>{{ exampleProps?.noContent ? "" : exampleName }}</db-badge
				>
				@if (exampleProps?.noContent) {
					<db-infotext
						semantic="informational"
						size="small"
						icon="none"
					>
						{{ exampleName }}
					</db-infotext>
				}
			}

			@if (
				exampleProps?.placement &&
				exampleProps?.placement !== "inline" &&
				!exampleProps?.example
			) {
				<db-button
					icon="x_placeholder"
					variant="outlined"
					[noText]="true"
				>
					<db-badge
						emphasis="strong"
						semantic="critical"
						size="small"
						[placement]="exampleProps?.placement"
					></db-badge>
					{{ exampleName }}
				</db-button>
				<db-infotext semantic="informational" size="small" icon="none">
					{{ exampleName }}
				</db-infotext>
			}

			@if (exampleProps?.placement === "inline") {
				<div class="badge-inline-container">
					<db-icon icon="x_placeholder"></db-icon>
					<span>{{ exampleName }}</span>
					<db-badge
						size="small"
						emphasis="strong"
						semantic="critical"
					>
						Label
					</db-badge>
					<db-icon icon="error"></db-icon>
				</div>
			}

			@if (exampleProps?.example === "icon") {
				<db-badge
					semantic="critical"
					emphasis="strong"
					[size]="exampleProps?.size"
				>
					<db-icon icon="x_placeholder">{{ exampleName }}</db-icon>
				</db-badge>
				<db-infotext semantic="informational" size="small" icon="none">
					{{ exampleName }}
				</db-infotext>
			}

			@if (exampleProps?.example === "number") {
				<db-badge semantic="successful">9</db-badge>
				<db-badge semantic="informational">12</db-badge>
				<db-badge semantic="warning">123</db-badge>
				<db-badge size="small" emphasis="strong" semantic="successful">
					9
				</db-badge>
				<db-badge
					size="small"
					emphasis="strong"
					semantic="informational"
				>
					12
				</db-badge>
				<db-badge size="small" emphasis="strong" semantic="warning">
					123
				</db-badge>
				<db-infotext semantic="informational" size="small" icon="none">
					{{ exampleName }}
				</db-infotext>
			}
		}
	</ng-template>
</app-default-component>
