// showcases/vue-showcase/src/control-panel/Actions1.vue
<script setup lang="ts">
import {
	DBButton,
	DBControlPanelActions1,
	DBDivider,
	DBDrawer,
	DBDrawerHeader,
	DBSelect,
	DBTooltip,
	DENSITIES,
	SEMANTICS
} from "@components";
import { ref } from "vue";
import { defaultSettingsMapping } from "../../../settings";
import { useLayout } from "../composables/use-layout";

const { density, color, onChange, settings } = useLayout();

const sendSettings = (event: any, key: string) => {
	onChange(
		{
			...settings.value,
			[key]: event?.target?.value
		},
		"settings"
	);
};

const open = ref(false);
</script>

<template>
	<DBControlPanelActions1>
		<DBDrawer :open="open" @close="() => (open = false)"
			><template v-slot:header>
				<DBDrawerHeader>Settings</DBDrawerHeader></template
			>
			<DBSelect
				label="Density"
				variant="floating"
				:value="density"
				@change="onChange($event, 'density')"
			>
				<option v-for="ton of DENSITIES" :value="ton">
					{{ ton }}
				</option>
			</DBSelect>
			<DBSelect
				label="Color"
				variant="floating"
				:value="color"
				@change="onChange($event, 'color')"
			>
				<option v-for="col of SEMANTICS" :value="col">
					{{ col }}
				</option>
			</DBSelect>
			<DBDivider />
			<template
				v-for="([key, value], index) of Object.entries(
					defaultSettingsMapping
				)"
			>
				<DBSelect
					:label="key"
					variant="floating"
					:value="settings[key]"
					@change="sendSettings($event, key)"
				>
					<option v-for="col of value" :value="col">
						{{ col }}
					</option>
				</DBSelect>
				<template v-if="index === 1 || index === 3"
					><DBDivider
				/></template>
			</template>
		</DBDrawer>
		<DBButton
			icon="gear_wheel"
			variant="ghost"
			no-text
			@click="() => (open = true)"
		>
			Settings
			<DBTooltip>Settings</DBTooltip>
		</DBButton>
	</DBControlPanelActions1>
</template>

// showcases/angular-showcase/src/app/control-panel/actions-1/actions-1.component.ts
import { Component, ElementRef, input, signal, viewChild } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import {
	DBButton,
	DBControlPanelActions1,
	DBDivider,
	DBDrawer,
	DBDrawerHeader,
	DBSelect,
	DBTooltip,
	DENSITIES,
	DENSITY,
	SEMANTIC,
	SEMANTICS
} from '@components';
import {
	DefaultSettings,
	defaultSettings,
	defaultSettingsMapping
} from '../../../../../settings';

@Component({
	selector: 'app-actions-1',
	schemas: [],
	imports: [
		DBControlPanelActions1,
		DBButton,
		DBDrawer,
		DBSelect,
		ReactiveFormsModule,
		DBTooltip,
		DBDivider,
		DBDrawerHeader
	],
	templateUrl: './actions-1.component.html'
})
export class Actions1Component {
	defaultSettingsMapping = Object.entries(defaultSettingsMapping);

	metaRef = viewChild<ElementRef>('metaRef');

	densities = DENSITIES;
	colors = SEMANTICS;

	density = input<string>(DENSITY.REGULAR);
	color = input<string>(SEMANTIC.NEUTRAL);
	settings = input<DefaultSettings>(defaultSettings);

	open = signal<boolean>(false);

	constructor(
		private readonly router: Router,
		private readonly route: ActivatedRoute
	) {}

	changeSettings = (event: any, key: string) => {
		const changedSettings: any = {
			...this.settings(),
			[key]: event.target.value
		};
		void this.onChange('settings', changedSettings);
	};

	onChange = async (key: string, value: any) => {
		const queryParameters: any = {};

		switch (key) {
			case 'density': {
				queryParameters[key] = value.target.value;

				break;
			}

			case 'color': {
				queryParameters[key] = value.target.value;

				break;
			}

			case 'settings': {
				queryParameters.settings = JSON.stringify(value);

				break;
			}
			// No default
		}

		await this.router.navigate([], {
			relativeTo: this.route,
			queryParams: queryParameters,
			queryParamsHandling: 'merge'
		});
	};
}

<db-control-panel-actions-1 #metaRef>
	<db-drawer (close)="open.set(false)" [open]="open()">
		<db-drawer-header header>Settings</db-drawer-header>
		<db-select
			(change)="onChange('density', $event)"
			[value]="density()"
			label="Density"
			variant="floating"
		>
			@for (t of densities; track t) {
				<option>
					{{ t }}
				</option>
			}
		</db-select>
		<db-select
			(change)="onChange('color', $event)"
			[value]="color()"
			#colorRef
			label="Color"
			variant="floating"
		>
			@for (c of colors; track c) {
				<option>
					{{ c }}
				</option>
			}
		</db-select>
		<db-divider></db-divider>

		@for (
			array of defaultSettingsMapping;
			track array[0];
			let idx = $index
		) {
			<db-select
				(change)="changeSettings($event, array[0])"
				[label]="array[0]"
				[value]="settings()[array[0]]"
				variant="floating"
			>
				@for (v of array[1]; track v) {
					<option>
						{{ v }}
					</option>
				}
			</db-select>
			@if (idx === 1 || idx === 3) {
				<db-divider></db-divider>
			}
		}
	</db-drawer>
	<db-button
		(click)="open.set(true)"
		[noText]="true"
		icon="gear_wheel"
		variant="ghost"
	>
		Settings
		<db-tooltip> Settings </db-tooltip>
	</db-button>
</db-control-panel-actions-1>
