// showcases/react-showcase/src/components/control-panel-mobile/index.tsx
import {
	DBButton,
	DBControlPanelBrand,
	DBControlPanelFlatIconNavigation,
	DBControlPanelMetaNavigation,
	DBControlPanelMobile,
	DBControlPanelPrimaryActions,
	DBControlPanelSecondaryActions,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from '@components';
import type { DBControlPanelMobileProps } from '@components/src/components/control-panel-mobile/model';
import defaultComponentVariants from '../../../../shared/control-panel-mobile.json';
import type { BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getControlPanelMobile = ({
	children,
	withNavigation = true,
	withName = true,
	withPrimary = true,
	withSecondary = true,
	withMeta = true,
	noText = false,
	position = 'top',
	variant
}: DBControlPanelMobileProps & {
	withName: boolean;
	withPrimary: boolean;
	withSecondary: boolean;
	withMeta: boolean;
	withNavigation: boolean;
	noText: boolean;
}) => (
	<DBControlPanelMobile
		position={position}
		drawerHeadlinePlain="DBHeader"
		variant={variant}
		brand={
			<DBControlPanelBrand title="DBHeader">
				{withName && 'DBHeader'}
			</DBControlPanelBrand>
		}
		metaNavigation={
			withMeta && (
				<DBControlPanelMetaNavigation>
					<DBLink href="#">Imprint</DBLink>
					<DBLink href="#">Help</DBLink>
				</DBControlPanelMetaNavigation>
			)
		}
		primaryActions={
			withPrimary && (
				<DBControlPanelPrimaryActions>
					<DBButton icon="magnifying_glass" variant="ghost" noText>
						Search
					</DBButton>
				</DBControlPanelPrimaryActions>
			)
		}
		secondaryActions={
			withSecondary && (
				<DBControlPanelSecondaryActions>
					<DBButton icon="x_placeholder" variant="ghost" noText>
						Profile
					</DBButton>
					<DBButton icon="x_placeholder" variant="ghost" noText>
						Notification
					</DBButton>
					<DBButton icon="x_placeholder" variant="ghost" noText>
						Help
					</DBButton>
				</DBControlPanelSecondaryActions>
			)
		}
		flatIconNavigation={
			<DBControlPanelFlatIconNavigation noText={noText}>
				<DBNavigation aria-label={children}>
					<DBNavigationItem icon="x_placeholder">
						<a href="#">{children}</a>
					</DBNavigationItem>
					<DBNavigationItem icon="x_placeholder" disabled>
						<a href="#">{children} disabled</a>
					</DBNavigationItem>
					<DBNavigationItem icon="x_placeholder">
						<a href="#">{children} long</a>
					</DBNavigationItem>
				</DBNavigation>
			</DBControlPanelFlatIconNavigation>
		}>
		{withNavigation && (
			<DBNavigation aria-label={children}>
				<DBNavigationItem icon="x_placeholder">
					<a href="#">{children}</a>
				</DBNavigationItem>
				<DBNavigationItem icon="x_placeholder" disabled>
					<a href="#">{children} disabled</a>
				</DBNavigationItem>
			</DBNavigation>
		)}
	</DBControlPanelMobile>
);

const ControlPanelMobileComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBControlPanelMobile"
			variants={getVariants(
				defaultComponentVariants,
				getControlPanelMobile
			)}></DefaultComponent>
	);
};

export default ControlPanelMobileComponent;

// showcases/vue-showcase/src/components/control-panel-mobile/ControlPanelMobile.vue
<script setup lang="ts">
import {
	DBButton,
	DBControlPanelBrand,
	DBControlPanelFlatIconNavigation,
	DBControlPanelMetaNavigation,
	DBControlPanelMobile,
	DBControlPanelPrimaryActions,
	DBControlPanelSecondaryActions,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from "@components";
import defaultComponentVariants from "../../../../shared/control-panel-mobile.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent
		title="DBControlPanelMobile"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBControlPanelMobile
				:position="exampleProps?.position ?? 'top'"
				:variant="exampleProps?.variant ?? 'drawer'"
				drawer-headline-plain="DBHeader"
			>
				<template v-slot:brand>
					<DBControlPanelBrand>
						<template v-if="exampleProps?.withName ?? true">
							DBHeader
						</template>
					</DBControlPanelBrand>
				</template>
				<template v-if="exampleProps?.withNavigation ?? true">
					<DBNavigation :aria-label="exampleName">
						<DBNavigationItem icon="x_placeholder">
							<a href="#">{{ exampleName }}</a>
						</DBNavigationItem>
						<DBNavigationItem icon="x_placeholder" :disabled="true">
							<a href="#">{{ exampleName }} disabled</a>
						</DBNavigationItem>
					</DBNavigation>
				</template>
				<template v-slot:primary-actions>
					<template v-if="exampleProps?.withPrimary ?? true">
						<DBControlPanelPrimaryActions>
							<DBButton
								icon="magnifying_glass"
								variant="ghost"
								noText
							>
								Search
							</DBButton>
						</DBControlPanelPrimaryActions>
					</template>
				</template>
				<template v-slot:secondary-actions>
					<template v-if="exampleProps?.withSecondary ?? true">
						<DBControlPanelSecondaryActions>
							<DBButton
								icon="x_placeholder"
								variant="ghost"
								noText
							>
								Profile
							</DBButton>
							<DBButton
								icon="x_placeholder"
								variant="ghost"
								noText
							>
								Notification
							</DBButton>
							<DBButton
								icon="x_placeholder"
								variant="ghost"
								noText
							>
								Help
							</DBButton>
						</DBControlPanelSecondaryActions>
					</template>
				</template>
				<template v-slot:meta-navigation>
					<template v-if="exampleProps?.withMeta ?? true">
						<DBControlPanelMetaNavigation>
							<DBLink href="#">Imprint</DBLink>
							<DBLink href="#">Help</DBLink>
						</DBControlPanelMetaNavigation>
					</template>
				</template>
				<template v-slot:flat-icon-navigation>
					<DBControlPanelFlatIconNavigation
						:no-text="exampleProps?.noText"
					>
						<DBNavigation :aria-label="exampleName">
							<DBNavigationItem icon="x_placeholder">
								<a href="#">{{ exampleName }}</a>
							</DBNavigationItem>
							<DBNavigationItem
								icon="x_placeholder"
								:disabled="true"
							>
								<a href="#">{{ exampleName }} disabled</a>
							</DBNavigationItem>
							<DBNavigationItem icon="x_placeholder">
								<a href="#">{{ exampleName }} long</a>
							</DBNavigationItem>
						</DBNavigation></DBControlPanelFlatIconNavigation
					>
				</template>
			</DBControlPanelMobile>
		</template>
	</DefaultComponent>
</template>
