// showcases/angular-showcase/src/app/components/control-panel-mobile/control-panel-mobile.component.ts
import { Component } from '@angular/core';

import {
	DBButton,
	DBControlPanelBrand,
	DBControlPanelFlatIconNavigation,
	DBControlPanelMetaNavigation,
	DBControlPanelMobile,
	DBControlPanelPrimaryActions,
	DBControlPanelSecondaryActions,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from '@components';
import defaultComponentVariants from '../../../../../shared/control-panel-mobile.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-control-panel-mobile',
	templateUrl: './control-panel-mobile.component.html',
	imports: [
		environment.webComponents
			? [DefaultComponent]
			: [
					DefaultComponent,
					DBControlPanelMobile,
					DBControlPanelBrand,
					DBControlPanelMetaNavigation,
					DBControlPanelFlatIconNavigation,
					DBNavigation,
					DBNavigationItem,
					DBControlPanelPrimaryActions,
					DBControlPanelSecondaryActions,
					DBButton,
					DBLink
				]
	],
	standalone: true
})
export class ControlPanelMobileComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBControlPanelMobile"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-control-panel-mobile
			[position]="exampleProps?.position ?? 'top'"
			drawerHeadlinePlain="DBHeader"
			[variant]="exampleProps?.variant ?? 'drawer'"
		>
			<db-control-panel-brand brand slot="brand">
				@if (exampleProps?.withName ?? true) {
					DBHeader
				}
			</db-control-panel-brand>
			@if (exampleProps?.withNavigation ?? true) {
				<db-navigation [attr.aria-label]="exampleName">
					<db-navigation-item icon="x_placeholder">
						<a href="#">{{ exampleName }} </a>
					</db-navigation-item>
					<db-navigation-item icon="x_placeholder" [disabled]="true">
						<a href="#">{{ exampleName }} disabled </a>
					</db-navigation-item>
				</db-navigation>
			}
			<ng-container flat-icon-navigation>
				<db-control-panel-flat-icon-navigation
					slot="flatIconNavigation"
					[noText]="exampleProps?.noText"
				>
					<db-navigation [attr.aria-label]="exampleName">
						<db-navigation-item icon="x_placeholder">
							<a href="#">{{ exampleName }} </a>
						</db-navigation-item>
						<db-navigation-item
							icon="x_placeholder"
							[disabled]="true"
						>
							<a href="#">{{ exampleName }} disabled </a>
						</db-navigation-item>
						<db-navigation-item icon="x_placeholder">
							<a href="#">{{ exampleName }} long</a>
						</db-navigation-item>
					</db-navigation>
				</db-control-panel-flat-icon-navigation>
			</ng-container>
			<ng-container meta-navigation>
				@if (exampleProps?.withMeta ?? true) {
					<db-control-panel-meta-navigation slot="metaNavigation">
						<db-link href="#">Imprint</db-link>
						<db-link href="#">Help</db-link>
					</db-control-panel-meta-navigation>
				}
			</ng-container>
			<ng-container primary-actions>
				@if (exampleProps?.withPrimary ?? true) {
					<db-control-panel-primary-actions slot="primaryActions">
						<db-button
							icon="magnifying_glass"
							variant="ghost"
							[noText]="true"
						>
							Search
						</db-button>
					</db-control-panel-primary-actions>
				}
			</ng-container>
			<ng-container secondary-actions>
				@if (exampleProps?.withSecondary ?? true) {
					<db-control-panel-secondary-actions slot="secondaryActions">
						<db-button
							icon="x_placeholder"
							variant="ghost"
							[noText]="true"
						>
							Profile
						</db-button>
						<db-button
							icon="x_placeholder"
							variant="ghost"
							[noText]="true"
						>
							Notification
						</db-button>
						<db-button
							icon="x_placeholder"
							variant="ghost"
							[noText]="true"
						>
							Help
						</db-button>
					</db-control-panel-secondary-actions>
				}
			</ng-container>
		</db-control-panel-mobile>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/control-panel-mobile/ControlPanelMobile.vue
<script setup lang="ts">
import {
	DBButton,
	DBControlPanelBrand,
	DBControlPanelFlatIconNavigation,
	DBControlPanelMetaNavigation,
	DBControlPanelMobile,
	DBControlPanelPrimaryActions,
	DBControlPanelSecondaryActions,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from "@components";
import defaultComponentVariants from "../../../../shared/control-panel-mobile.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<DefaultComponent
		title="DBControlPanelMobile"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBControlPanelMobile
				:position="exampleProps?.position ?? 'top'"
				:variant="exampleProps?.variant ?? 'drawer'"
				drawer-headline-plain="DBHeader"
			>
				<template v-slot:brand>
					<DBControlPanelBrand>
						<template v-if="exampleProps?.withName ?? true">
							DBHeader
						</template>
					</DBControlPanelBrand>
				</template>
				<template v-if="exampleProps?.withNavigation ?? true">
					<DBNavigation :aria-label="exampleName">
						<DBNavigationItem icon="x_placeholder">
							<a href="#">{{ exampleName }}</a>
						</DBNavigationItem>
						<DBNavigationItem icon="x_placeholder" :disabled="true">
							<a href="#">{{ exampleName }} disabled</a>
						</DBNavigationItem>
					</DBNavigation>
				</template>
				<template v-slot:primary-actions>
					<template v-if="exampleProps?.withPrimary ?? true">
						<DBControlPanelPrimaryActions>
							<DBButton
								icon="magnifying_glass"
								variant="ghost"
								noText
							>
								Search
							</DBButton>
						</DBControlPanelPrimaryActions>
					</template>
				</template>
				<template v-slot:secondary-actions>
					<template v-if="exampleProps?.withSecondary ?? true">
						<DBControlPanelSecondaryActions>
							<DBButton
								icon="x_placeholder"
								variant="ghost"
								noText
							>
								Profile
							</DBButton>
							<DBButton
								icon="x_placeholder"
								variant="ghost"
								noText
							>
								Notification
							</DBButton>
							<DBButton
								icon="x_placeholder"
								variant="ghost"
								noText
							>
								Help
							</DBButton>
						</DBControlPanelSecondaryActions>
					</template>
				</template>
				<template v-slot:meta-navigation>
					<template v-if="exampleProps?.withMeta ?? true">
						<DBControlPanelMetaNavigation>
							<DBLink href="#">Imprint</DBLink>
							<DBLink href="#">Help</DBLink>
						</DBControlPanelMetaNavigation>
					</template>
				</template>
				<template v-slot:flat-icon-navigation>
					<DBControlPanelFlatIconNavigation
						:no-text="exampleProps?.noText"
					>
						<DBNavigation :aria-label="exampleName">
							<DBNavigationItem icon="x_placeholder">
								<a href="#">{{ exampleName }}</a>
							</DBNavigationItem>
							<DBNavigationItem
								icon="x_placeholder"
								:disabled="true"
							>
								<a href="#">{{ exampleName }} disabled</a>
							</DBNavigationItem>
							<DBNavigationItem icon="x_placeholder">
								<a href="#">{{ exampleName }} long</a>
							</DBNavigationItem>
						</DBNavigation></DBControlPanelFlatIconNavigation
					>
				</template>
			</DBControlPanelMobile>
		</template>
	</DefaultComponent>
</template>
