// showcases/angular-showcase/src/app/components/tag/tag.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBTag } from '../../../../../../output/angular/src';
import defaultComponentVariants from '../../../../../shared/tag.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-tag',
	templateUrl: './tag.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBTag],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : [],
	standalone: true
})
export class TagComponent {
	variants = defaultComponentVariants;
	showAlert = (exampleName: string) => {
		// eslint-disable-next-line no-alert
		alert(exampleName);
	};
}

<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<app-default-component
	title="DBTag"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
	>
		@if (exampleProps?.lineBreak) {
			<i class="line-break"></i>
		} @else {
			<db-tag
				[semantic]="exampleProps?.semantic"
				[icon]="exampleProps?.icon"
				[noText]="exampleProps?.noText"
				[behavior]="exampleProps?.behavior"
				[showCheckState]="exampleProps?.showCheckState"
				[emphasis]="exampleProps?.emphasis"
				[showIcon]="exampleProps?.showIcon"
				[overflow]="exampleProps?.overflow"
				[removeButton]="exampleProps?.removeButton"
				(onRemove)="showAlert(exampleName)"
			>
				@if (exampleProps?.content) {
					<div slot="content" class="default-content-slot">
						Swap Slot
					</div>
				}
				@if (exampleProps?.component === "button") {
					<button>{{ exampleName }}</button>
				}
				@if (exampleProps?.component === "link") {
					<a href="#">
						{{ exampleName }}
					</a>
				}
				@if (exampleProps?.component === "checkbox") {
					<label>
						<input
							type="checkbox"
							[checked]="exampleProps?.checked"
							[disabled]="exampleProps?.disabled"
						/>
						{{ exampleName }}
					</label>
				}
				@if (exampleProps?.component === "radio") {
					<label>
						<input
							type="radio"
							[checked]="exampleProps?.checked"
							[name]="exampleProps?.identifier"
						/>
						{{ exampleName }}
					</label>
				}
				@if (!exampleProps?.component && !exampleProps?.overflow) {
					{{ exampleName }}
				}
				@if (!exampleProps?.component && exampleProps?.overflow) {
					<span>{{ exampleName }}</span>
				}
			</db-tag>
		}
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/tag/Tag.vue
<!--
SPDX-FileCopyrightText: 2025 DB Systel GmbH

SPDX-License-Identifier: Apache-2.0
-->

<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tag.json";
import { DBTag } from "../../../../../output/vue/src";

const showAlert = (exampleName?: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName || "");
};
</script>

<template>
	<DefaultComponent title="DBTag" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<i class="line-break" v-if="exampleProps?.lineBreak" />
			<DBTag
				v-if="!exampleProps?.lineBreak"
				:semantic="exampleProps?.semantic"
				:icon="exampleProps?.icon"
				:noText="exampleProps?.noText"
				:behavior="exampleProps?.behavior"
				:emphasis="exampleProps?.emphasis"
				:showIcon="exampleProps?.showIcon"
				:showCheckState="exampleProps?.showCheckState"
				:overflow="exampleProps?.overflow"
				:removeButton="exampleProps?.removeButton"
				@remove="showAlert(exampleName)"
			>
				<div
					v-if="exampleProps?.content"
					slot="content"
					class="default-content-slot"
				>
					Swap Slot
				</div>

				<button v-if="exampleProps?.component === 'button'">
					{{ exampleName }}
				</button>
				<a v-if="exampleProps?.component === 'link'" href="#">
					{{ exampleName }}
				</a>
				<label v-if="exampleProps?.component === 'checkbox'">
					<input
						type="checkbox"
						:disabled="exampleProps?.disabled"
						:checked="exampleProps?.checked"
					/>
					{{ exampleName }}
				</label>

				<label v-if="exampleProps?.component === 'radio'">
					<input
						type="radio"
						:checked="exampleProps?.checked"
						:name="exampleProps?.identifier"
					/>
					{{ exampleName }}
				</label>
				<template
					v-if="
						exampleProps?.component !== 'button' &&
						exampleProps?.component !== 'link' &&
						exampleProps?.component !== 'checkbox' &&
						exampleProps?.component !== 'radio' &&
						!exampleProps?.overflow
					"
				>
					{{ exampleName }}
				</template>
				<template
					v-if="
						exampleProps?.component !== 'button' &&
						exampleProps?.component !== 'link' &&
						exampleProps?.component !== 'checkbox' &&
						exampleProps?.component !== 'radio' &&
						exampleProps?.overflow
					"
				>
					<span>{{ exampleName }}</span>
				</template>
			</DBTag>
		</template>
	</DefaultComponent>
</template>
