// showcases/vue-showcase/src/components/badge/Badge.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/badge.json";
import {
	DBBadge,
	DBIcon,
	DBButton,
	DBInfotext
} from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBBadge" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<i class="line-break" v-if="exampleProps?.lineBreak" />
			<template v-if="!exampleProps?.lineBreak">
				<template
					v-if="!exampleProps?.placement && !exampleProps?.example"
				>
					<DBBadge
						:semantic="exampleProps?.semantic"
						:emphasis="exampleProps?.emphasis"
						:size="exampleProps?.size"
					>
						{{ exampleProps?.noContent ? "" : exampleName }}
					</DBBadge>
					<DBInfotext
						v-if="exampleProps?.noContent"
						semantic="informational"
						size="small"
						icon="none"
					>
						{{ exampleName }}
					</DBInfotext>
				</template>

				<template
					v-if="
						exampleProps?.placement &&
						exampleProps?.placement !== 'inline' &&
						!exampleProps?.example
					"
				>
					<DBButton
						icon="x_placeholder"
						variant="outlined"
						:noText="true"
					>
						<DBBadge
							emphasis="strong"
							semantic="critical"
							size="small"
							:placement="exampleProps?.placement"
						>
						</DBBadge>
						{{ exampleName }}
					</DBButton>
					<DBInfotext
						semantic="informational"
						size="small"
						icon="none"
					>
						{{ exampleName }}
					</DBInfotext>
				</template>

				<template v-if="exampleProps?.placement === 'inline'">
					<div class="badge-inline-container">
						<DBIcon icon="x_placeholder"></DBIcon>
						<span>{{ exampleName }}</span>
						<DBBadge
							size="small"
							emphasis="strong"
							semantic="critical"
						>
							Label
						</DBBadge>
						<DBIcon icon="error"></DBIcon>
					</div>
				</template>

				<template v-if="exampleProps?.example === 'icon'">
					<DBBadge
						semantic="critical"
						emphasis="strong"
						:size="exampleProps?.size"
					>
						<DBIcon icon="x_placeholder">{{ exampleName }}</DBIcon>
					</DBBadge>
					<DBInfotext
						semantic="informational"
						size="small"
						icon="none"
					>
						{{ exampleName }}
					</DBInfotext>
				</template>

				<template v-if="exampleProps?.example === 'number'">
					<DBBadge semantic="successful">9</DBBadge>
					<DBBadge semantic="informational">12</DBBadge>
					<DBBadge semantic="warning">123</DBBadge>
					<DBBadge
						size="small"
						emphasis="strong"
						semantic="successful"
					>
						9
					</DBBadge>
					<DBBadge
						size="small"
						emphasis="strong"
						semantic="informational"
					>
						12
					</DBBadge>
					<DBBadge size="small" emphasis="strong" semantic="warning">
						123
					</DBBadge>
					<DBInfotext
						semantic="informational"
						size="small"
						icon="none"
					>
						{{ exampleName }}
					</DBInfotext>
				</template></template
			>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/badge/index.tsx
import {
	DBBadge,
	DBButton,
	DBIcon,
	DBInfotext
} from '../../../../../output/react/src';
import type { DBBadgeProps } from '../../../../../output/react/src/components/badge/model';
import defaultComponentVariants from '../../../../shared/badge.json';
import { type BaseComponentProps } from '../base-component-data';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

const getBadge = ({
	children,
	semantic,
	emphasis,
	noContent,
	size,
	placement,
	example,
	lineBreak
}: DBBadgeProps & {
	noContent: boolean;
	example: string;
	lineBreak?: boolean;
}) => {
	if (lineBreak) {
		return <i className="line-break" />;
	}

	return (
		<>
			{!placement && !example && (
				<>
					<DBBadge
						semantic={semantic}
						emphasis={emphasis}
						size={size}>
						{noContent ? '' : children}
					</DBBadge>
					{noContent && (
						<DBInfotext
							semantic="informational"
							size="small"
							icon="none">
							{children}
						</DBInfotext>
					)}
				</>
			)}

			{placement && placement !== 'inline' && !example && (
				<>
					<DBButton icon="x_placeholder" variant="outlined" noText>
						<DBBadge
							size="small"
							emphasis="strong"
							semantic="critical"
							placement={placement}></DBBadge>
						{children}
					</DBButton>
					<DBInfotext
						semantic="informational"
						size="small"
						icon="none">
						{children}
					</DBInfotext>
				</>
			)}

			{placement === 'inline' && (
				<>
					<div className="badge-inline-container">
						<DBIcon icon="x_placeholder" />
						<span>{children}</span>
						<DBBadge
							size="small"
							emphasis="strong"
							semantic="critical">
							Label
						</DBBadge>
						<DBIcon icon="error" />
					</div>
				</>
			)}

			{example === 'icon' && (
				<>
					<DBBadge semantic="critical" emphasis="strong" size={size}>
						<DBIcon icon="x_placeholder">{children}</DBIcon>
					</DBBadge>
					<DBInfotext
						semantic="informational"
						size="small"
						icon="none">
						{children}
					</DBInfotext>
				</>
			)}

			{example === 'number' && (
				<>
					<DBBadge semantic="successful">9</DBBadge>
					<DBBadge semantic="informational">12</DBBadge>
					<DBBadge semantic="warning">123</DBBadge>
					<DBBadge
						size="small"
						emphasis="strong"
						semantic="successful">
						9
					</DBBadge>
					<DBBadge
						size="small"
						emphasis="strong"
						semantic="informational">
						12
					</DBBadge>
					<DBBadge size="small" emphasis="strong" semantic="warning">
						123
					</DBBadge>
					<DBInfotext
						semantic="informational"
						size="small"
						icon="none">
						{children}
					</DBInfotext>
				</>
			)}
		</>
	);
};

const BadgeComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBBadge"
			variants={getVariants(
				defaultComponentVariants,
				getBadge,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default BadgeComponent;
