// showcases/vue-showcase/src/components/breadcrumb/breadcrumb.vue
<script setup lang="ts">
// TODO: Uncomment after build-outputs
// import { DBBreadcrumb } from "../../../../../output/vue/src";
import defaultComponentVariants from "../../../../shared/breadcrumb.json";
import DefaultComponent from "../DefaultComponent.vue";

// Temporary placeholder component
const DBBreadcrumb = "nav";
</script>

<template>
	<DefaultComponent title="DBBreadcrumb" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<component
				:is="DBBreadcrumb"
				:class="['db-breadcrumb', exampleProps?.className]"
				:data-size="exampleProps?.size"
				:data-separator="exampleProps?.separator"
				aria-label="breadcrumb"
			>
				<ol class="db-breadcrumb-list" role="list">
					<li
						v-for="(item, index) in exampleProps?.children"
						:key="index"
						:aria-current="item.ariaCurrent"
					>
						<a v-if="item.href" :href="item.href">{{
							item.text
						}}</a>
						<span v-else>{{ item.text }}</span>
					</li>
				</ol>
			</component>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/breadcrumb/index.tsx
import { DBBreadcrumb } from '../../../../../output/react/src';
import defaultComponentVariants from '../../../../shared/breadcrumb.json';
import { getVariants } from '../data';
import DefaultComponent from '../default-component';

type BreadcrumbItem = {
	href?: string;
	text: string;
	ariaCurrent?: 'page' | undefined;
};

type BreadcrumbExampleProps = {
	children?: BreadcrumbItem[];
	size?: 'small' | 'medium';
	className?: string;
	separator?: 'chevron' | 'slash';
};

const getBreadcrumb = ({
	children,
	size,
	className,
	separator
}: BreadcrumbExampleProps) => (
	<DBBreadcrumb size={size} className={className} separator={separator}>
		{children && Array.isArray(children)
			? children.map((item, index) =>
					item.href ? (
						<li key={index}>
							<a href={item.href}>{item.text}</a>
						</li>
					) : (
						<li key={index} aria-current={item.ariaCurrent as any}>
							<span>{item.text}</span>
						</li>
					)
				)
			: children}
	</DBBreadcrumb>
);

type BreadcrumbComponentProps = {
	slotCode?: Record<string, React.FC>;
};

const BreadcrumbComponent = (props: BreadcrumbComponentProps) => (
	<DefaultComponent
		title="DBBreadcrumb"
		variants={getVariants(
			defaultComponentVariants,
			getBreadcrumb,
			props.slotCode
		)}></DefaultComponent>
);

export default BreadcrumbComponent;
