// showcases/angular-showcase/src/app/components/footer/footer.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DBFooter } from '../../../../../../output/angular/src';
import defaultComponentVariants from '../../../../../shared/footer.json';
import { environment } from '../../../environments/environment';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-footer',
	templateUrl: './footer.component.html',
	imports: environment.webComponents
		? [DefaultComponent]
		: [DefaultComponent, DBFooter],
	schemas: environment.webComponents ? [CUSTOM_ELEMENTS_SCHEMA] : [],
	standalone: true
})
export class FooterComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBFooter"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleContent="exampleContent"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-footer
			[showCopyright]="exampleProps?.showCopyright ?? true"
			[showMain]="exampleProps?.showMain ?? true"
			[showMeta]="exampleProps?.showMeta ?? true"
			[width]="exampleProps?.width"
		>
			<div main>
				{{ exampleContent ?? exampleName }}
			</div>
			<div meta>
				Legal Links
			</div>
		</db-footer>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/footer/Footer.vue
<script setup lang="ts">
import { DBFooter } from "../../../../../output/vue/src";
import defaultComponentVariants from "../../../../shared/footer.json";
import DefaultComponent from "../DefaultComponent.vue";
</script>

<template>
	<div class="footer-page">
		<DefaultComponent title="DBFooter" :variants="defaultComponentVariants">
			<template #example="{ exampleProps, exampleName, exampleContent }">
				<DBFooter
					:showCopyright="exampleProps?.showCopyright ?? true"
					:showMain="exampleProps?.showMain ?? true"
					:showMeta="exampleProps?.showMeta ?? true"
					:width="exampleProps?.width"
				>
					<template #main>
						<span>{{ exampleContent ?? exampleName }}</span>
					</template>
				</DBFooter>
			</template>
		</DefaultComponent>
	</div>
</template>
